HTML і CSS практика: Hooli-style Popup
kottans/frontend-2022-homeworks pull request #102
Opened 2022-08-09 10:54 UTC by loki13btz

### HTML і CSS практика: Hooli-style Popup

[Demo](https://loki13btz.github.io/Hooli-style-Popup/) |
[Code base](https://github.com/loki13btz/Hooli-style-Popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-13 09:18 UTC, A-Ostrovnyy requested changes
Good work!
See my comments below.

2022-08-14 12:30 UTC, loki13btz commented
@A-Ostrovnyy PR updated, take a look please)

2022-08-14 14:30 UTC, A-Ostrovnyy requested changes
Good work!

2022-08-14 14:30 UTC, A-Ostrovnyy commented on submissions/loki13btz/html-css-popup/index.html
> +                <li><a href="#" class="menu-item">Mail</a></li>
Avoid links jumping on hover [watch video](https://share.vidyard.com/watch/hYhiY3ma8czAXmnR73ypa6?)

2022-08-14 14:30 UTC, A-Ostrovnyy commented on submissions/loki13btz/html-css-popup/index.html
> +                <li><label for="popupCheckbox" class="menu-item popup-shower"><img class="popup-icon"
Add `cursor: pointer` to all interactive elements.
Also, the user must have the ability to open a popup using keyboard.

2022-08-14 14:30 UTC, A-Ostrovnyy commented on submissions/loki13btz/html-css-popup/index.html
> +                <label for="buttonCheckbox" class="open-button">More</label>
Add styles on hover and focus states.
Also, add `cursor: pointer`

2022-08-21 12:45 UTC, loki13btz commented
@A-Ostrovnyy PR updated, take a look please)

2022-08-21 16:54 UTC, A-Ostrovnyy approved these changes
Well done!

2022-08-21 16:54 UTC, merged