App Popup
kottans/frontend-2022-homeworks pull request #103
Opened 2022-08-09 13:56 UTC by OlexiyDobroskok

### HTML і CSS практика: Hooli-style Popupe

[Demo](https://olexiydobroskok.github.io/app__Popup/ |
[Code base](https://github.com/OlexiyDobroskok/app__Popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-14 14:43 UTC, A-Ostrovnyy requested changes
Awesome!

2022-08-14 14:43 UTC, A-Ostrovnyy commented on submissions/OlexiyDobroskok/app-Popup/index.html
> +                        alt="user"
Read how and when to populate alt attribute value [Как правильно написать alt-текст](https://htmlacademy.ru/blog/articles/alt-text)

2022-08-14 14:43 UTC, A-Ostrovnyy commented on submissions/OlexiyDobroskok/app-Popup/index.html
> +            <li class="menu__item"><a href="#" class="menu__link">Foto</a></li>
```suggestion
            <li class="menu__item"><a href="#" class="menu__link">Photo</a></li>
```

2022-08-14 14:43 UTC, A-Ostrovnyy commented on submissions/OlexiyDobroskok/app-Popup/index.html
> +                  </label>
Check your markup in [validator](https://validator.w3.org/)

2022-08-14 14:43 UTC, A-Ostrovnyy commented on submissions/OlexiyDobroskok/app-Popup/index.html
> +                    tabindex="0"
This line makes no sense because input already has focus by default.

2022-08-15 09:30 UTC, A-Ostrovnyy commented
@OlexiyDobroskok Why did you close PR?

2022-08-15 09:39 UTC, OlexiyDobroskok commented
i have some problem with git, i can open again?

2022-08-15 16:48 UTC, A-Ostrovnyy approved these changes
Well done!

2022-08-15 16:48 UTC, merged

2022-08-15 16:53 UTC, OlexiyDobroskok commented
> 

Thnx =)