HTML-CSS-Popup
kottans/frontend-2022-homeworks pull request #115
Opened 2022-08-10 14:00 UTC by natayakovleva

### HTML-CSS-Popup

[Demo](https://natayakovleva.github.io/HTML-CSS-popup/) |
[Code base](https://github.com/natayakovleva/HTML-CSS-popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-16 11:24 UTC, natayakovleva commented
Hello. Sorry for not answering immediately. I thought the answer would come to the mail. And I was busy with the next task. 
Tell me please, now I need to modify the lists according to the recommendations and re-send the PR again?

2022-08-16 16:11 UTC, A-Ostrovnyy requested changes
Good work!
About what to do next: 
1. Make changes to your repository(not this one) with popup task.
2. Update demo on GitHub pages.
3. Update files in current PR with files from your repository(item 1).
4. Push changes, it automatically updates PR.

2022-08-17 19:32 UTC, natayakovleva commented
Hi. Thank you for your comments. I hope I fixed everything)

2022-08-18 14:16 UTC, A-Ostrovnyy requested changes
Good progress!

2022-08-18 14:16 UTC, A-Ostrovnyy commented on submissions/natayakovleva/HTML-CSS-popup/index.html
> +                </div>
Logically it's a link)

2022-08-18 14:16 UTC, A-Ostrovnyy commented on submissions/natayakovleva/HTML-CSS-popup/index.html
> +          <li><a href="#" class="header__link"><img class="header__link-img" src="./img/bell.png" alt="link-bell"></a></li>
Read how and when to populate alt attribute value [Как правильно написать alt-текст](https://htmlacademy.ru/blog/articles/alt-text)

2022-08-18 20:03 UTC, natayakovleva commented
Hi. I made changes and thanks for the article)

2022-08-19 07:12 UTC, A-Ostrovnyy requested changes
One last issue)

2022-08-19 07:12 UTC, A-Ostrovnyy commented on submissions/natayakovleva/HTML-CSS-popup/index.html
> +          <li><a href="#" class="header__link"><img class="header__link-img" src="./img/bell.png" alt="Go to notifications page"></a></li>
One of the points in the provided article is no need to populate `alt` attribute for decorative images. Icon is a decorative image)

2022-08-22 19:21 UTC, natayakovleva commented
Hi and thanks for your help.
Honestly, I was thinking of it as a link, not a button, so I didn’t think to delete it(
Sorry for the delay - family problems

2022-08-22 19:34 UTC, A-Ostrovnyy approved these changes
Well done!

2022-08-22 19:34 UTC, merged

2022-08-23 19:21 UTC, natayakovleva commented
Thanks for your help))