Frogger
kottans/frontend-2022-homeworks pull request #119
Opened 2022-08-11 15:41 UTC by OlStani

### Frogger game

[Demo](https://olstani.github.io/frontend-nanodegree-arcade-game/) |
[Code base](https://github.com/OlStani/frontend-nanodegree-arcade-game)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-15 22:20 UTC, OleksiyRudenko requested changes
@OlStani pretty well done.
However we need to follow a principle of class isolation from the outer world. Other minore fixes are also required.
Please check the comments and DoD bot's message below.

2022-08-15 22:20 UTC, OleksiyRudenko commented on submissions/OlStaniev/frogger-game/app.js
> +            console.log('error');
Remove debugging statements here and elsewhere across the codebase.

2022-08-15 22:20 UTC, OleksiyRudenko commented on submissions/OlStaniev/frogger-game/app.js
> +const allEnemies = [enemy1, enemy2, enemy3]
As a peer developer I am increasing the number of rows on the field by 100. There should be a way to add a hundred more enemies in a loop rather then hardcoding. There is some correlation between enemy's home row and whatever last parameter represented by a magic number means.

BTW, as a peer developer I want to understand what are the semanthics of the magic numbers to be able to contribute to the project.

2022-08-16 13:45 UTC, OleksiyRudenko commented
@OlStani please confirm all requirements posted by bot are fulfilled.
If you gonna fix anything else while making code compliant to the requirements, please also fix semicolons. Their usage is mixed. Stick to a particular style. It matters.

2022-08-16 14:06 UTC, OlStani commented
@OleksiyRudenko 
я на разі не розумію що щє потрібно змінити, єдине що спадає на думку це зробити player i enemy батьківський класс , але не бачу сенс у цьому

2022-08-16 14:12 UTC, OleksiyRudenko commented
1. Було б добре розгорнути, чому не має сенсу.

2. Крім цього Nice To Have реквайрмента [тут](https://github.com/kottans/frontend-2022-homeworks/pull/119#issuecomment-1215924111) на все інше можна поставити галочки?

2022-08-16 14:41 UTC, OlStani commented
@OleksiyRudenko 
Requirements re Constants - в цьому розділі наче все
Requirements re OOP :
1) константу з класу прибрав
2) я не розумію що тут треба зробити 
3) я зроблю батьківський клас
4) я поки не розумію, але спробую сам розібратись
Most common mistakes: не бачу де в мене така помилка

2022-08-16 14:52 UTC, OleksiyRudenko commented
@OlStani 

> 2. я не розумію що тут треба зробити
> ...
>    Most common mistakes: не бачу де в мене така помилка

Це чекліст для самоперевірки. Не обов'язково мати проблему в коді. Якщо ревайрмент дотриманий і проблеми нема, то просто "ставиш галочку".

Я теж не пам'ятаю, щоб там в коді були такі проблеми. Але завдяки чек-лісту нарозповсюдженіших проблем можна дізнатись про "граблі", на які можна легко наступити.

Пінгани, коли внесеш всі зміни, які запланував.

2022-08-16 15:54 UTC, OlStani commented
@OleksiyRudenko 
я прочитав статтю https://developer.mozilla.org/ru/docs/Web/JavaScript/Inheritance_and_the_prototype_chain
але все одно не розумію навіщо це:  class extension is implemented using Subclass.prototype = Object.create(Superclass.prototype), not Subclass.prototype = new Superclass(params);

2022-08-16 16:15 UTC, OleksiyRudenko commented
@OlStani 

> @OleksiyRudenko я прочитав статтю https://developer.mozilla.org/ru/docs/Web/JavaScript/Inheritance_and_the_prototype_chain але все одно не розумію навіщо це: class extension is implemented using Subclass.prototype = Object.create(Superclass.prototype), not Subclass.prototype = new Superclass(params);

In brief, `Object.create(Superclass.prototype)` truly binds child class with the super class. Which means that the child class really refers to the superclass' properties. Also proper binding helps to backtrace connections in a complex hierarchy. The latter just creates a copy object of the superclass - with all its properties and methods. Besides a child class becomes a child of a particular instance of the Superclass, not of the Superclass "prototypical" object. Imagine  your project uses 100s of subclasses and 1000s of instances at any given moment of time.  You are tasked to add another 50 child classes and 1000 of instances in the air. You will want to implement this in more efficient way rather than be blamed for the performance issues you may have avoided. Yes, you can suggest to switch to ES6 syntax, but it is up to the project architect to decide, and meanwhile you will have to accomplish your assignment.

You may find these explanations more informative:
- https://stackoverflow.com/questions/18547693/why-use-object-create-for-prototype-when-extending-an-object
- a deeper insight: https://blog.bitsrc.io/javascript-prototype-chains-and-inheritance-382ce1c0f3f3

2022-08-16 16:59 UTC, OlStani commented
@OleksiyRudenko 
поясни будь-ласка що я маю зробити, бо я не розумію

2022-08-16 17:12 UTC, OleksiyRudenko commented
Якщо ти використовуєш наслідування, то його треба робити вказаним способом. Якщо не будуєш ієрархію класів, то не треба нічого з цим робити. Або я не зрозумів запитання.

2022-08-16 17:21 UTC, OlStani commented
@OleksiyRudenko 
ясно , наче все. додав зміни

2022-08-16 17:27 UTC, OleksiyRudenko approved these changes
@OlStani great job!

Recommendation: set up prettier and eslint plugins on your IDE for them to do all the dirty code styling work for you. Tune them per your preferences, semicolons usage in particular.

2022-08-16 17:27 UTC, merged