add file for hoolie-popup task
kottans/frontend-2022-homeworks pull request #127
Opened 2022-08-11 23:08 UTC by maksimsergeev97

### HTML і CSS практика: Hooli-style Popup
[Demo](https://maksimsergeev97.github.io/Hooli-style-popup) | [Code base](https://github.com/maksimsergeev97/Hooli-style-popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-17 19:13 UTC, maksimsergeev97 commented
Hey! 
my code has been validated. 
I took into account all the tips from common mistakes when writing code

2022-08-18 17:01 UTC, A-Ostrovnyy requested changes
Awesome work!
See my comments below.

2022-08-18 17:01 UTC, A-Ostrovnyy commented on submissions/maksimsergeev97/hoolie-style-popup/index.html
> +                            </label>
Add styles on `:focus` state)

2022-08-18 17:01 UTC, A-Ostrovnyy commented on submissions/maksimsergeev97/hoolie-style-popup/index.html
> +                    <ul class="popup__wrapper">
Fix popup position on the mobile version 
![image](https://user-images.githubusercontent.com/16196199/185452901-2ffbb057-82cf-4fb1-960a-3d86816718bb.png)

2022-08-19 21:47 UTC, maksimsergeev97 commented
Hey! Thanks for the review! Code fixed!

2022-08-21 16:38 UTC, A-Ostrovnyy requested changes
Good prgress!

2022-08-21 16:38 UTC, A-Ostrovnyy commented on submissions/maksimsergeev97/hoolie-style-popup/index.html
> +                        <li><a class="popup__link__item" href="#"><img class="popup__icon" src="icons/news.png" alt="news icon"><span>News</span></a></li>
Read how and when to populate alt attribute value [Как правильно написать alt-текст](https://htmlacademy.ru/blog/articles/alt-text)

2022-08-21 16:38 UTC, A-Ostrovnyy commented on submissions/maksimsergeev97/index.html
> +<!DOCTYPE html>
This file is redundant, also, all files must be in the task folder. Remove this file.

2022-08-22 09:07 UTC, maksimsergeev97 commented
Hey! Thanks for the help ! Fixed. I ask for a review, again :)

2022-08-24 16:47 UTC, A-Ostrovnyy approved these changes
Well done!

2022-08-24 16:47 UTC, merged