add task popup DmitryHniezdilov
kottans/frontend-2022-homeworks pull request #131
Opened 2022-08-12 16:38 UTC by DmitryHniezdilov

### HTML-CSS-Popup

[Demo](https://https://dmitryhniezdilov.github.io/task-popup/) |
[Code base](https://github.com/DmitryHniezdilov/task-popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-13 06:41 UTC, zonzujiro commented
You should have a possibility to open menu with Space button!

2022-08-13 09:50 UTC, DmitryHniezdilov commented
Hi. Sorry for that this simple bug, I never fixed this bug before, and check only using tab.

Please, review.

2022-08-18 17:27 UTC, A-Ostrovnyy requested changes
Good work!

2022-08-18 17:27 UTC, A-Ostrovnyy commented on submissions/DmitryHniezdilov/task-html-css-popup/css/style.css
> +.popup__input,
Watch [the video](https://www.youtube.com/watch?v=E6kLaaQFctU&t=413s) to find out how to hide the checkbox in the right way.

2022-08-18 17:27 UTC, A-Ostrovnyy commented on submissions/DmitryHniezdilov/task-html-css-popup/index.html
> +                            <input class="popup__input" id="popup" type="checkbox" tabindex="1">
Your markup will work fine without `tabindex` attribute.

2022-08-19 11:52 UTC, DmitryHniezdilov commented
Thanks for the review. It will help me to check the code more carefully in the future.

2022-08-19 14:37 UTC, A-Ostrovnyy approved these changes
Well done!

2022-08-19 14:37 UTC, merged

2022-08-19 16:24 UTC, DmitryHniezdilov commented
Thank you!