Friends App
kottans/frontend-2022-homeworks pull request #134
Opened 2022-08-12 20:31 UTC by kovalov

### Friends App

[Demo](https://kovalov.github.io/kottans-friends-app/) |
[Code base](https://github.com/kovalov/kottans-friends-app)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-13 05:56 UTC, zonzujiro commented
<img width="287" alt="image" src="https://user-images.githubusercontent.com/2997359/184470764-5517ca45-46ae-440c-aec0-158484e3663b.png">

And how you sorting the same data by name and by age? 🤔

2022-08-13 05:57 UTC, zonzujiro commented
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/2997359/184470791-ff2ee111-c3f9-4bf8-b541-d1ee8f0ac6a0.png">

Looks like age sorting doesn't work.

Also, you should render age on cards :)

2022-08-13 05:58 UTC, zonzujiro commented
Also, be sure that you don't have [common mistakes](https://kottans.org/documentation/docs/doc/code-review#friends-app)

2022-08-13 06:13 UTC, kovalov commented
> <img width="1122" alt="image" src="https://user-images.githubusercontent.com/2997359/184470791-ff2ee111-c3f9-4bf8-b541-d1ee8f0ac6a0.png">
> 
> Looks like age sorting doesn't work.
> 
> Also, you should render age on cards :)
> 

Age is showing near the full name. Should I implement it another way?

2022-08-14 17:54 UTC, kovalov commented
Have rewrite the code according to common mistakes list. Please check.

2022-08-18 08:56 UTC, zonzujiro approved these changes
LGTM

2022-08-20 15:39 UTC, zonzujiro requested changes

2022-08-20 15:39 UTC, zonzujiro commented on submissions/kovalov/friends-app/app.js
> +// const formSearchInputElement = document.querySelector(
:) Leftover?

2022-08-20 15:39 UTC, zonzujiro commented on submissions/kovalov/friends-app/app.js
> +  if (value === 'ageAscending' || value === 'ageDescending') {
No need to call function if will do nothing.

Instead you can have object with keys from your values of inputs and values of object from sorters.

2022-08-20 15:39 UTC, zonzujiro commented on submissions/kovalov/friends-app/app.js
> +  const { value: searchValue } = formElement.search;
Looks like you're using values as names for inputs :)

2022-08-20 15:41 UTC, zonzujiro commented on submissions/kovalov/friends-app/app.js
> +  const { value: searchValue } = formElement.search;
Ah, no. All good

2022-08-20 20:06 UTC, zonzujiro approved these changes
Great job!

2022-08-20 20:07 UTC, merged