Popup api task
kottans/frontend-2022-homeworks pull request #151
Opened 2022-08-14 15:11 UTC by Conversee12

### HTML&CSS_Popup

[Demo](https://conversee12.github.io/Hooli-style-Popup/) |
[Code base](https://github.com/Conversee12/Hooli-style-Popup.git)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-16 19:07 UTC, Conversee12 commented
I fixed space at the end files. I didn't see common mistakes, please, let me know if something needs to be changed.

2022-08-21 12:30 UTC, artem-trubin requested changes
Hi! Great job. Let's improve it a little.

Your `More` button doesn't have any visual reaction when you get to it by going through all elements with the keyboard. Also, it should disappear when the `More` menu is opened.

Another thing, please be consistent with your code styling, make equal amounts of empty lines between code block, etc.

2022-08-21 12:30 UTC, artem-trubin commented on submissions/Conversee12/HTML&CSS Popup/style.css
> +
Two empty lines.

2022-08-21 12:30 UTC, artem-trubin commented on submissions/Conversee12/HTML&CSS Popup/style.css
> +
Empty line.

2022-08-24 14:34 UTC, artem-trubin commented
Well done!

2022-08-24 14:35 UTC, merged