HTML-CSS Popup
kottans/frontend-2022-homeworks pull request #155
Opened 2022-08-15 06:57 UTC by v4voloshyn

### HTML-CSS Popup

[Demo](https://v4voloshyn.github.io/popup-kottans/) |
[Code base](https://github.com/v4voloshyn/popup-kottans)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-16 21:30 UTC, v4voloshyn commented
I'm pretty sure that it's everything alright with my code. But nobody is perfect :)

P.S. I found some bug in my code, but can do you? 😁

2022-08-21 20:09 UTC, kasionio requested changes
Nice job, good design! Try to make a self-review and optimize the code ;) And take a look at the comments below

2022-08-21 20:09 UTC, kasionio commented on submissions/v4voloshyn/html-css-popup/styles.css
> +	text-transform: capitalize;
seems you did it manually :)

2022-08-21 20:09 UTC, kasionio commented on submissions/v4voloshyn/html-css-popup/styles.css
> +	/* experemental feature >| */
this is a good comment 👍

2022-08-21 20:09 UTC, kasionio commented on submissions/v4voloshyn/html-css-popup/styles.css
> +	box-shadow: rgb(173, 20, 110) 0px 5px 10px;
first dimensions, them color

2022-08-21 20:09 UTC, kasionio commented on submissions/v4voloshyn/html-css-popup/styles.css
> +.popup-list {
one class and so many properties 😞  Please try to optimize your code, it is not easy to review. You can refactor and simplify it, some of the properties are redundant

2022-09-11 21:14 UTC, closed without merging