DOM homework
kottans/frontend-2022-homeworks pull request #163
Opened 2022-08-15 18:14 UTC by bmukha

[Demo](https://bmukha.github.io/kottans-dom/) |
[Code base](https://github.com/bmukha/kottans-dom)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-24 13:18 UTC, madmaxWMFU requested changes
Good work. See some comments below.

2022-08-24 13:18 UTC, madmaxWMFU commented on submissions/bmukha/dom/app.js
> +        <img class="hero-portrait_img" src="./img/${heroClass}.webp" alt="heroportrait" />
Read and try [dectruction](https://javascript.info/destructuring-assignment)

2022-08-24 13:18 UTC, madmaxWMFU commented on submissions/bmukha/dom/app.js
> +  const randomNumber = Math.floor(Math.random() * 9);
A magic number. Use a `const` of array length.

2022-08-24 13:18 UTC, madmaxWMFU commented on submissions/bmukha/dom/index.html
> +            <div id="demonhunter" class="hero-info">
It is a link. Maybe you can use the tag `<a></a>`

2022-08-24 13:18 UTC, madmaxWMFU commented on submissions/bmukha/dom/app.js
> +    (item) => item.class.toLowerCase().split(' ').join('') === hero
In your list of heroes one hero with class consists of two words. Maybe you rename and write less code? It only for discussion. How do you think?

2022-08-24 17:05 UTC, bmukha commented
First of all, thx for the feedback, I appreciate it a lot. Regarding Demon Hunter, the only hero with two words in a class name. Well, he was very problematic to deal with from the beginning. I've tried to simplify that class name in the code everywhere I could, but it should definitely stay intact on the main page. People will try to find me if I misspell one of the Word of Warcraft classes intentionally, you know ) Another possible solution I can think of from the top of my head is to use something like data- in my HTML as hero's class name container, but I don't think it worth the effort to make this change just to get rid of a couple of lines of code. All the other issues that you've pointed out, have been addressed. Please, re-review.

2022-08-24 20:09 UTC, madmaxWMFU requested changes

2022-08-24 20:09 UTC, madmaxWMFU commented on submissions/bmukha/dom/app.js
> +    (item) => item.heroClass.toLowerCase().split(' ').join('') === hero
The variable `info` hasn't correct information.
`const infoHero = heroes.find(heroe => {})`

2022-08-24 20:09 UTC, madmaxWMFU commented on submissions/bmukha/dom/app.js
> +  const hero = event.target.parentElement.id;
You read and changed the code used destruction. In this part, you also can try this. 
`document.querySelector('.menu').addEventListener('click', ({target}) => {}`

2022-08-24 20:12 UTC, madmaxWMFU commented on submissions/bmukha/dom/app.js
> +document.querySelector('.menu').addEventListener('click', (event) => {
Maybe is a better to set the listener on element 'list'

2022-08-24 20:31 UTC, madmaxWMFU commented
Correct me if I'm slightly wrong.
First of all, a dataset is a good option for saving some information that we may need to work with.
Second, you already have a static menu with the names of the heroes. That is, in your array, the `heroClass` property would be better called `heroId`. The user would not be able to see it, it is unlikely that he would crawl into the source code. When you check, you compare the id attribute of the element with the array property 
```javascript
const hero = event.target.parentElement.id;  // demonhunter
...
//item.heroClass.toLowerCase().split(' ').join('')
// Demon Hunter -> demonhunter -> ['demon', hunter] -> demonhunter
item.heroClass.toLowerCase().split(' ').join('') === hero // demonhunter == demonhunter
...

```

2022-08-25 15:03 UTC, bmukha commented
Tnx again for the suggestions. It kinda stuck in my head from the beginning of the project, that I use all those hero class names in the dynamic part of the page. Apparently, I am not. Of course, it makes perfect sense to just rename stuff in my array and get rid of all the string manipulation code altogether. Shame on me for not noticing this. So, I've changed the code to address this and all the other suggestions. Please, take a look.

2022-08-25 15:09 UTC, madmaxWMFU approved these changes
Great, I approve of your work. Good luck with future tasks!
```
const getContent = ({ target }) => {
  content.innerHTML = renderHero(
    heroes.find((item) => item.heroId === target.parentElement.id)
  );
}
document.querySelector('.list').addEventListener('click', );

const init = () => {
  const randomNumber = Math.floor(Math.random() * heroes.length);
  content.innerHTML = renderHero(heroes[randomNumber]);
}

document.addEventListener('DOMContentLoaded', init);
```

2022-08-25 15:13 UTC, merged