Tiny JS World
kottans/frontend-2022-homeworks pull request #165
Opened 2022-08-15 21:46 UTC by vovan-zt

### Tiny JS World

[Demo](https://vovan-zt.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/vovan-zt/a-tiny-JS-world)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-15 23:07 UTC, OleksiyRudenko requested changes
@vovan-zt nice start.
Needs a couple of improvements though.

2022-08-15 23:07 UTC, OleksiyRudenko commented on submissions/vovan-zt/Tiny_JS_World/index.js
> +});
As a peer developer on this project I am tasked to add non-printable properties.

Please fix this fragment accordingly.

Also make sure you have consistency as to semicolons. This fragment and a fragment below look like a cut-out from somewhere else in these regards.

2022-08-15 23:07 UTC, OleksiyRudenko commented on submissions/vovan-zt/Tiny_JS_World/index.js
> +   species: "man",
Men and women are same species.

2022-08-15 23:07 UTC, OleksiyRudenko commented on submissions/vovan-zt/Tiny_JS_World/index.js
> +const objName = [dog, cat, woman, man, catWoman];
`objName` is confusing variable name. It contains living beings rather than objects, and also lists inhabitants rather than their names.

2022-08-16 19:27 UTC, vovan-zt commented on submissions/vovan-zt/Tiny_JS_World/index.js
> +   species: "man",
Исправлю

2022-08-16 19:28 UTC, vovan-zt commented on submissions/vovan-zt/Tiny_JS_World/index.js
> +const objName = [dog, cat, woman, man, catWoman];
Исправлю на  WorldInhabitant

2022-08-16 19:34 UTC, vovan-zt commented on submissions/vovan-zt/Tiny_JS_World/index.js
> +   species: "man",
тогда по логике собака и кот должны быть animal

2022-08-16 19:50 UTC, OleksiyRudenko commented on submissions/vovan-zt/Tiny_JS_World/index.js
> +   species: "man",
Dogs and cats are definitely different species.

2022-08-16 20:41 UTC, vovan-zt commented on submissions/vovan-zt/Tiny_JS_World/index.js
> +});
Последовательность в отношении точки с запятой ошибок не увидел.  Хотелось автоматически все свойства вытягивать с объектов, жаль что вам не понравилось:) 
В первую очередь стараюсь чтоб поставленная задача заработала, поэтому часто оставляю не очень красиво отформатированный код, это моя ошибка, постараюсь в будущем как-то это пофиксить:)

Фрагмент исправил  чтоб коллега мог добавлять непечатаемые свойства.

2022-08-16 21:06 UTC, OleksiyRudenko requested changes
@vovan-zt still some room for improvement.

Also please make species descriptions consistent.

Humans are also animals. Dogs and cats belong to different species.

2022-08-16 21:06 UTC, OleksiyRudenko commented on submissions/vovan-zt/Tiny_JS_World/index.js
> +   return arr;
`Array#map` will make `let arr ... return arr` fragment a oneliner. You won't even need the `return` statement and function body brackets.

Also callback defined here receives a single every time, not a set of keys.

2022-08-16 21:06 UTC, OleksiyRudenko commented on submissions/vovan-zt/Tiny_JS_World/index.js
> +const objPrint = WorldInhabitant.map((obj) => {
`obj` in `objPrint` and `obj` parameter per se are too generic.
Avoid generic names unless you design a multipurpose method for a library.

2022-08-20 18:45 UTC, OleksiyRudenko requested changes
> Avoid generic names unless you design a multipurpose method for a library.

`object`, `item`, `element`, `array`, `key` are bad generic names. Whatever doesn't describe domain entities is not good enough.

`inhabitant`, `cat`, `name`, `species` are good domain specific names.

Please stick to this principle at all times. The code is written for other people. Good naming helps other people better understand your code and thus collaborate in more efficient ways. Especially if codebase grows big.

2022-08-20 19:47 UTC, vovan-zt commented
I will try not to make such mistakes in the future.

2022-08-20 20:26 UTC, OleksiyRudenko approved these changes
@vovan-zt grat job!

2022-08-20 20:26 UTC, merged