finish project
kottans/frontend-2022-homeworks pull request #192
Opened 2022-08-16 17:43 UTC by supert111

### popup-html-css

[Demo](https://supert111.github.io/popup-html-css/) |
[Code base](https://github.com/supert111/popup-html-css)

2022-08-16 19:25 UTC, supert111 commented
Hello, initially I did not see in the documentation what structure. There are no errors in validation.

2022-08-16 22:17 UTC, supert111 commented
Please Re-request review

2022-08-22 17:16 UTC, A-Ostrovnyy requested changes
Good work!

2022-08-22 17:16 UTC, A-Ostrovnyy commented on submissions/supert111/html-css-popup/index.html
> +                </label>
The menu icon is a part of navigation too, put it into list.

2022-08-22 17:16 UTC, A-Ostrovnyy commented on submissions/supert111/html-css-popup/index.html
> +                                    <img class="popupImg" src="images/calendar.png" alt="calendar" width="40">
Read how and when to populate alt attribute value [Как правильно написать alt-текст](https://htmlacademy.ru/blog/articles/alt-text)

2022-08-28 12:30 UTC, A-Ostrovnyy requested changes
One last issue.

2022-08-28 12:30 UTC, A-Ostrovnyy commented on submissions/supert111/html-css-popup/index.html
> +                                                <img class="popupImg" src="images/collection.png" alt="icon-collection" width="40">
You have text inside your links + icons are decorative images so `alt` attribute should be empty

2022-08-29 06:09 UTC, A-Ostrovnyy approved these changes
Well done!

2022-08-29 06:09 UTC, merged