MPG-task
kottans/frontend-2022-homeworks pull request #195
Opened 2022-08-16 21:42 UTC by the-darkesttt

### Memory Pair Game task

[Demo](https://the-darkesttt.github.io/memory-pair-game/) |
[Code base](https://github.com/the-darkesttt/memory-pair-game)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-16 21:54 UTC, OleksiyRudenko commented
@the-darkesttt looks nice. 
This is not a code review though.

How about posting a link to the demo in the students' chat and collecting feedback re usability etc?

2022-08-17 22:56 UTC, OleksiyRudenko commented
@the-darkesttt very smooth gameplay and a lot better UX. I like it.

Disclaimer: This is not a code review though.

2022-08-24 19:37 UTC, A-Ostrovnyy requested changes
Good work!

2022-08-26 06:18 UTC, A-Ostrovnyy requested changes
Good progress!

2022-08-26 06:18 UTC, A-Ostrovnyy commented on submissions/the-darkesttt/memory-pair-game/js/newApp.js
> +}
Get a full string of cards using the `reduce` array method and pass it directly to the destination(line 132). With this approach variable `cardsItems` is redundant.

2022-08-26 06:18 UTC, A-Ostrovnyy commented on submissions/the-darkesttt/memory-pair-game/js/newApp.js
> +let cardSprites = [
Move all constants and variable declarations to the top of the file. if they are on the root level.

2022-08-26 06:18 UTC, A-Ostrovnyy commented on submissions/the-darkesttt/memory-pair-game/js/newApp.js
> +const restartButton = document.querySelector('#restart-btn');
Move all constants and variable declarations to the top of the file. if they are on the root level.

2022-08-26 06:18 UTC, A-Ostrovnyy commented on submissions/the-darkesttt/memory-pair-game/js/newApp.js
> +function createCard(card) {
Combine it with `createCards` function

2022-09-07 17:10 UTC, the-darkesttt commented
Thank you for your suggestions!

2022-09-07 17:59 UTC, A-Ostrovnyy approved these changes
Well done!

2022-09-07 18:00 UTC, merged