memory cards game
kottans/frontend-2022-homeworks pull request #199
Opened 2022-08-17 12:02 UTC by semenjob

[Demo](https://semenjob.github.io/pair-game/) |
[Code base](https://github.com/semenjob/pair-game)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-17 12:23 UTC, OleksiyRudenko commented
Being a fan of MPG I tried it.

It would be nice to see all cards without need to scroll. Would be great if you could apply learnings from past tasks to make UX better...

Also, at some point I clicked randomly and here is what has happened:

![image](https://user-images.githubusercontent.com/8686631/185116954-12fbee24-2927-4ce9-b8c3-418912fa2378.png)

2022-08-18 09:12 UTC, OleksiyRudenko commented
A lot better UX now 👍 

Disclaimer: this is not a code review feedback.

2022-08-22 09:42 UTC, dromix commented on submissions/semenjob/memoryCards/game-logic.js
> +};
```suggestion
const toggleMemoryCard = (card) => card?.classList.toggle("flip");
```

2022-08-22 09:55 UTC, dromix commented on submissions/semenjob/memoryCards/game-logic.js
> +        firstCards = null;
I would suggest to create some structure for pairCards like
```javascript
class PairCards {
  firstCard;
  secondCard; // or even provide linked-list structure if memory card can be more than 2 pairs

  setFirstCards(card) {
    this.firstCard = card;
  }

  setSecondCard(card) {
    this.secondCard = card;
  }

  check() {} // validates that cards are equel
  reset() {} // toggle cards to init state
}
```
Usage example:
```javascript
const pair = new PairCards();
pair.setFirstCard(card);
pair.setSecondCard(card);

const isEquel = pair.check();
if (!isEquel) pair.reset();
```

2022-08-30 18:41 UTC, kasionio commented
Seems it is not working well 
![image](https://user-images.githubusercontent.com/21179601/187517186-7d8325c3-e16e-4357-958a-bafb97f24a56.png)

2022-09-03 12:31 UTC, A-Ostrovnyy requested changes
Good work!

2022-09-03 12:31 UTC, A-Ostrovnyy commented on submissions/semenjob/memoryCards/game-logic.js
> +    cards.append(card);
At this line, you append a card on each iteration, avoid that pattern. 
Use `append` method, which can add several elements in one operation

2022-09-03 12:31 UTC, A-Ostrovnyy commented on submissions/semenjob/memoryCards/game-logic.js
> +        console.log("winGame");
Remove console.log

2022-09-03 12:31 UTC, A-Ostrovnyy commented on submissions/semenjob/memoryCards/game-logic.js
> +      const isEquel = pair.check();
Looks like it's typo)

2022-09-03 12:31 UTC, A-Ostrovnyy commented on submissions/semenjob/memoryCards/game-logic.js
> +  const cardsLength = 6;
Is this a magic number?)

2022-09-03 12:31 UTC, A-Ostrovnyy commented on submissions/semenjob/memoryCards/game-logic.js
> +});
```suggestion
document.addEventListener("DOMContentLoaded", startGame);
```

2022-09-03 12:31 UTC, A-Ostrovnyy commented on submissions/semenjob/memoryCards/game-logic.js
> +        addClassBlock(this.cards);
You use function outside your class. One of the main principles of OOP is Encapsulation: all methods of the class must be inside this class.

2022-09-24 20:10 UTC, closed without merging