Add html-css-popup
kottans/frontend-2022-homeworks pull request #203
Opened 2022-08-17 18:53 UTC by misshatsker

### html-css-popup

[Demo](https://misshatsker.github.io/hooli-style-popup/) |
[Code base](https://github.com/misshatsker/hooli-style-popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-23 11:02 UTC, HannaSyn requested changes
Cute work! See my comment below to improve it

2022-08-23 11:02 UTC, HannaSyn commented on submissions/misshatsker/html-css-popup/index.css
> +.link:hover, .link:focus, .profile-link:focus {
It is better to start every class name after coma from a new line

2022-08-23 19:43 UTC, misshatsker commented
@HannaSyn thanks a lot for your review! Could you please take a look at my changes/fixes?

2022-08-25 15:27 UTC, HannaSyn commented
Looks great 🤩

2022-08-25 15:27 UTC, merged