Frogger-game
kottans/frontend-2022-homeworks pull request #204
Opened 2022-08-17 19:08 UTC by zhenyakornilov

### Object-Oriented JS - Frogger-game

[Demo](https://zhenyakornilov.github.io/kottans-frogger-game-oop/) |
[Code base](https://github.com/zhenyakornilov/kottans-frogger-game-oop)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-18 11:43 UTC, zhenyakornilov commented
### Covered some common mistakes:
1. Class **Enemy** do not refer to global **player** variable, **player** passed to **Enemy** constructor instead.
2. **Enemy** **update()** method do not call **checkOverlap()** method inside. Moved **checkOverlap()** method to **updateEntities** function in **engine.js** instead.

2022-08-20 18:53 UTC, OleksiyRudenko commented
> 2\. **Enemy** **update()** method do not call **checkOverlap()** method inside. Moved **checkOverlap()** method to **updateEntities** function in **engine.js** instead.

Please bring it back to the `app.js` for the sake of code review scope. It can perfectly be a part of Enemy class (as it is specific to Enemy behaviour), just needs to be a method on its own.

2022-08-20 18:58 UTC, OleksiyRudenko requested changes
@zhenyakornilov very well coded!

Apart of bringing collision checking function back as mentioned above, let's add more semantics to the constants so that peer developers were able to **read** what every number means and implement changes quickly when needed.

2022-08-20 18:58 UTC, OleksiyRudenko commented on submissions/zhenyakornilov/frogger-game/app.js
> +        this.x = GAME_BOARD_WIDTH + 10;
WHat is `10` here and across the codebase? I guess `-10` is the same but just negative. If true then having `OFFSET = 10` and referring to it as `OFFSET` and `-OFFSET` would be fine.
Of course `OFFSET` word doesn't explain it application, so invent a better name.

2022-08-20 18:58 UTC, OleksiyRudenko commented on submissions/zhenyakornilov/frogger-game/app.js
> +      this.player.x < this.x + 60 &&
What is `60`?

2022-08-20 19:29 UTC, zhenyakornilov commented
Made some changes

2022-08-20 20:35 UTC, OleksiyRudenko requested changes
@zhenyakornilov please go through your code and extrapolate previous comments re magic numbers to all other similar situations in your code.
Do not expect a reviewer to "red pen" every single tiny bug in the code. Own it truly.

2022-08-21 14:14 UTC, zhenyakornilov commented
It seems to be a bit better now.

2022-08-21 15:21 UTC, OleksiyRudenko approved these changes
@zhenyakornilov a really good job!

Hint on naming in graphic environments:
In regular structures like matrices, game fields (which are also matrices) elements' coordinates are defined by row (or column), matrix row height (or matrix column width), and offset.
So, for e.g. `y = verticalOffset + row * rowHeight`.  Items to place into the matrix may have their own individual offsets (like in this game where visual part has offsets against its pixel representation).
So having defined offsets, widths and heights it is possible to calculate any coordinates based on row and column index.

2022-08-21 15:21 UTC, merged