Html css popup
kottans/frontend-2022-homeworks pull request #205
Opened 2022-08-17 19:44 UTC by Maksym-Perepelytsia

### Hooli-style Popup

[Demo](https://maksym-perepelytsia.github.io/html-css-popup/) |
[Code base](https://github.com/Maksym-Perepelytsia/html-css-popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-18 10:18 UTC, Maksym-Perepelytsia commented
I changed some CSS code because the 'More Cats' focus styles weren't working.

2022-08-23 11:10 UTC, HannaSyn requested changes
You did good job!
Please, see my comments below

2022-08-23 11:10 UTC, HannaSyn commented on submissions/Maksym-Perepelytsia/html-css-popup/index.html
> +                            <img src="img/popup-button.png" alt="popup icon" width="24" height="24">
For icons it's better set an empty alt attribute, read more [here](https://accessibility.psu.edu/images/imageshtml/#empty)

2022-08-23 11:10 UTC, HannaSyn commented on submissions/Maksym-Perepelytsia/html-css-popup/style.css
> +#more-cats-checkbox{
You have class names on this elements, why do you styling by id? It is better to use class names for styling, and ids for js

2022-08-23 11:10 UTC, HannaSyn commented on submissions/Maksym-Perepelytsia/html-css-popup/style.css
> +.popup__menu__item img {
Please, avoid styling by tags [link](https://frontstuff.io/you-need-to-stop-targeting-tags-in-css)

2022-08-23 11:10 UTC, HannaSyn commented on submissions/Maksym-Perepelytsia/html-css-popup/style.css
> +@media screen and (max-width:380px){
```suggestion
@media screen and (max-width:380px) {
```
You forget space here

2022-08-23 11:10 UTC, HannaSyn commented on submissions/Maksym-Perepelytsia/html-css-popup/style.css
> +        left:15px;
```suggestion
        left: 15px;
```
You forget space here

2022-08-23 11:10 UTC, HannaSyn commented on submissions/Maksym-Perepelytsia/html-css-popup/style.css
> +    cursor:pointer;
```suggestion
    cursor: pointer;
```
You forget space here

2022-08-23 11:10 UTC, HannaSyn commented on submissions/Maksym-Perepelytsia/html-css-popup/style.css
> +    position:absolute;
```suggestion
    position: absolute;
```
You forget space here

2022-08-23 13:03 UTC, Maksym-Perepelytsia commented
@HannaSyn Thank you for your feedback. Please, review my latest edits according to your comments.

2022-08-23 13:33 UTC, Maksym-Perepelytsia reviewed
Alt attributes are now empty.
In the CSS file, id selectors changed to class selectors.
Styling by tags was replaced with styling by classes.
And I fixed the missing spaces.

2022-08-25 15:25 UTC, merged

2022-08-25 15:31 UTC, Maksym-Perepelytsia commented
Thank you very much.
Have a nice day 🙂