Html css popup
kottans/frontend-2022-homeworks pull request #206
Opened 2022-08-17 20:06 UTC by Serge044

### HTML-CSS-Popup

[Demo](https://serge044.github.io/HTML-CSS-Popup/) |
[Code base](https://github.com/Serge044/HTML-CSS-Popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-23 11:30 UTC, HannaSyn requested changes
Wow, you did a great work, I almost don't have comments, well done! 
See few comments to make it little better

2022-08-23 11:30 UTC, HannaSyn commented on submissions/Serge044/HTML-CSS-Popup/index.html
> +                                        <img src="images/kottans-calendar.png" alt="Calendar" class="popup__icons">
For icons it's better set an empty alt attribute, read more [here](https://accessibility.psu.edu/images/imageshtml/#empty)

2022-08-23 11:30 UTC, HannaSyn commented on submissions/Serge044/HTML-CSS-Popup/index.html
> +                        <a href="#Mail" class="main__nav-buttons mail"><span
Please, read more about [BEM](https://en.bem.info/methodology/)
I don't see class name of block `main__nav`

2022-08-25 16:23 UTC, Serge044 commented
Thanks for your review! I made the changes and it should be better now.

2022-08-29 10:16 UTC, merged