taskPopup
kottans/frontend-2022-homeworks pull request #209
Opened 2022-08-18 08:51 UTC by Olha3001

_**УВАЖНО прочитайте і виконайте всі інструкції нижче перед тим як подати код на рев'ю.**_
1. Відформатуйте код, виправте неправильні відступи, видаліть непотрібні рядки, додайте пустий рядок у кінці кожного файлу, щоб ревʼюверу було зручно читати ваш код. Відформатувати код можна за допомогою [Prettier](https://prettier.io/playground). 
1. Перевірте свій код на наявність [типових помилок](https://kottans.org/documentation/docs/doc/code-review/#typical-mistakes). Пройдіться по всім пунктам відповідно до вашого завдання і виправте знайдені помилки.
1. Опублікуйте свою програму на [сторінках GitHub](https://github.com/kottans/frontend-2021-homeworks/blob/main/publish-your-app.md).
1. Переконайтеся, що назва вашого PR містить назву завдання.
1. Ваш код розміщено у бранчі, створеній спеціально для цього завдання (не `main`, не `master`, не бранча для іншого завдання).
1. Додайте тільки ті файли, які необхідні для рев'ю (код, CSS, HTML, які написані вами; не додавайте картинки, бо це робить репозиторій важким і відволікає рев'юерів)
1. Відредагуйте це повідомлення, як описано в наступних пунктах.
1. Змініть відповідно назву завдання та посилання нижче.
1. Видаліть весь текст вище із цим рядком включно.

### task name

[Demo](https://your-username.github.io/app-repo-name) |
[Code base](https://github.com/your-username/app-repo-name)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-18 10:16 UTC, Olha3001 commented
Corrected

2022-08-18 11:35 UTC, Olha3001 commented
verified

2022-08-23 18:42 UTC, A-Ostrovnyy requested changes
Good work!

2022-08-23 18:42 UTC, A-Ostrovnyy commented on submissions/Olha3001/Poppy/index.html
> +      <img src="./img-check/favicon.png" alt="" class="icon-nav-link check-icon_s logo" tabindex="1" >
The logo should be a link and leads users to the home page.

2022-08-23 18:42 UTC, A-Ostrovnyy commented on submissions/Olha3001/Poppy/index.html
> +    <title>Document</title>
Add propper page title

2022-08-23 18:42 UTC, A-Ostrovnyy commented on submissions/Olha3001/Poppy/index.html
> +        <li class="popup-menu">
Fix code indentation, use [Prettier](https://prettier.io/) for it.

2022-08-23 18:42 UTC, A-Ostrovnyy commented on submissions/Olha3001/Poppy/index.html
> +            <a href="#" class="check-item link" tabindex="0" ><img src="./img-check/calendar.png" alt="calendar" class="check-icons " >
`tabindex="0"` on interactive element makes no sense.

2022-08-23 18:42 UTC, A-Ostrovnyy commented on submissions/Olha3001/Poppy/index.html
> +            <a href="#" class="check-item link"><img src="./img-check/blogs.png" alt="blogs" class="check-icons" >
Read how and when to populate alt attribute value [Как правильно написать alt-текст](https://htmlacademy.ru/blog/articles/alt-text)

2022-08-23 18:42 UTC, A-Ostrovnyy commented on submissions/Olha3001/Poppy/index.html
> +</html>
Add an empty line at the end of each file. [Reason](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline?noredirect=1&lq=1)

2022-08-23 18:42 UTC, A-Ostrovnyy commented on submissions/Olha3001/Poppy/index.html
> +      <nav>
Add mobile version
![image](https://user-images.githubusercontent.com/16196199/186237250-ed01bba1-4e04-456a-abd1-70000cd60c48.png)

2022-08-23 18:42 UTC, A-Ostrovnyy commented on submissions/Olha3001/Poppy/index.html
> +<!DOCTYPE html>
By default your popup is open, it must be closed, also, fix the order of interactive elements.

2022-09-13 20:09 UTC, closed without merging