HTML-CSS-Popup maksymenko
kottans/frontend-2022-homeworks pull request #211
Opened 2022-08-18 10:56 UTC by Meylin-V

### HTML-CSS-Popup

[Demo](https://meylin-v.github.io/html-css-popup/) |
[Code base](https://github.com/Meylin-V/html-css-popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-18 11:18 UTC, Meylin-V commented
I checked common mistakes, it's seems all ok, ready to review

2022-08-27 07:22 UTC, A-Ostrovnyy requested changes
Good work!
Sorry for the late response!

2022-08-27 07:22 UTC, A-Ostrovnyy commented on submissions/maksymenkonat/popup/index.html
> +              </label>
Fix styles on focus state
![image](https://user-images.githubusercontent.com/16196199/187019629-0fe452af-e967-492e-bc1c-d806e105f2d0.png)

2022-08-27 07:22 UTC, A-Ostrovnyy commented on submissions/maksymenkonat/popup/index.html
> +                      <img src="assets/calendar.png" alt="Calendar" />
Read how and when to populate alt attribute value [Как правильно написать alt-текст](https://htmlacademy.ru/blog/articles/alt-text)

2022-08-27 07:22 UTC, A-Ostrovnyy commented on submissions/maksymenkonat/popup/index.html
> +                </label>
This button is not accessible from the keyboard, please fix it. Also, hide this button when the second part of the popup is open. [Watch video](https://share.vidyard.com/watch/AjhUWq8C2dd3PzNAy2eynq?)

2022-08-27 07:22 UTC, A-Ostrovnyy commented on submissions/maksymenkonat/popup/style.css
> + nav {
Avoid styling by HTML tags except if you add base styles. [Reason](https://frontstuff.io/you-need-to-stop-targeting-tags-in-css)

2022-09-17 08:33 UTC, closed without merging