Hooli style popup
kottans/frontend-2022-homeworks pull request #212
Opened 2022-08-18 11:02 UTC by drewzag

### Hooli-style Popup

[Demo](https://drewzag.github.io/hooli-style-popup/) |
[Code base](https://github.com/drewzag/hooli-style-popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-27 07:28 UTC, A-Ostrovnyy requested changes
Good work!
Sorry for the late response.

2022-08-27 07:28 UTC, A-Ostrovnyy commented on submissions/drewzag/hooli-style-popup/index.html
> +            </label>
Please fix styles on focus state: [watch video](https://share.vidyard.com/watch/zy6cyn6ShCLu43EeFyo2Qc?)

2022-08-27 07:28 UTC, A-Ostrovnyy commented on submissions/drewzag/hooli-style-popup/index.html
> +                    <img src="/popup-icons/calendar.png" alt="" class="popup-image" />
Read how and when to populate alt attribute value [Как правильно написать alt-текст](https://htmlacademy.ru/blog/articles/alt-text)

2022-08-27 07:28 UTC, A-Ostrovnyy commented on submissions/drewzag/hooli-style-popup/index.html
> +              </label>
Please fix styles on the focus state to indicate the current position of focus on the page. Watch provided  [video](https://share.vidyard.com/watch/zy6cyn6ShCLu43EeFyo2Qc?)

2022-08-27 07:28 UTC, A-Ostrovnyy commented on submissions/drewzag/hooli-style-popup/style.css
> +.nav {
Avoid styling by HTML tags except if you add base styles. [Reason](https://frontstuff.io/you-need-to-stop-targeting-tags-in-css)

2022-08-29 18:23 UTC, A-Ostrovnyy requested changes
Good progress!

2022-08-29 18:23 UTC, A-Ostrovnyy commented on submissions/drewzag/hooli-style-popup/index.html
> +                alt="open or close popup menu"
DEcorative images no need populated `alt` attribute, icon is a decorative image.)

2022-08-29 18:23 UTC, A-Ostrovnyy commented on submissions/drewzag/hooli-style-popup/index.html
> +            <div class="popup__wrapper">
Please fix mobile version 
![image](https://user-images.githubusercontent.com/16196199/187271354-a11460d8-ab13-4582-80f6-2f4d11ae18d5.png)

2022-08-30 10:12 UTC, drewzag commented
@A-Ostrovnyy I hope, I did it wright this time)
Thank you for reviewing my code

2022-08-31 07:42 UTC, A-Ostrovnyy approved these changes
Well done!

2022-08-31 07:43 UTC, merged