Hooli style popup
kottans/frontend-2022-homeworks pull request #227
Opened 2022-08-19 16:55 UTC by andreymashko7

### Hooli style popup

[Demo](https://andreymashko7.github.io/hooli-style-popup/) |
[Code base](https://github.com/andreymashko7/hooli-style-popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-23 14:54 UTC, andreymashko7 commented
changed html structure according to task, added some mobile styles

2022-08-23 14:55 UTC, andreymashko7 reviewed
changed html structure according to task, added some mobile styles

2022-08-25 15:31 UTC, andreymashko7 reviewed
changed html structure according to task, added some mobile styles

2022-08-27 08:04 UTC, A-Ostrovnyy requested changes
Good work!

2022-08-27 08:04 UTC, A-Ostrovnyy commented on submissions/AndriyM/hooli-style-popup/index.html
> +        <title>Document</title>
Add propper page title

2022-08-27 08:04 UTC, A-Ostrovnyy commented on submissions/AndriyM/hooli-style-popup/index.html
> +                                </label>
Fix position of focused elements
![image](https://user-images.githubusercontent.com/16196199/187021165-ce2bedce-4fe8-48ba-a9ba-9494b14944b8.png)

2022-08-27 08:04 UTC, A-Ostrovnyy commented on submissions/AndriyM/hooli-style-popup/index.html
> +                                        <a href="#" class="popup__link"><img src="./img/blogs.png" width="90" height="60" class="popup__link-img" alt="blog link" /><span class="popup__text">Blog</spa
Read how and when to populate alt attribute value [Как правильно написать alt-текст](https://htmlacademy.ru/blog/articles/alt-text)

2022-08-27 08:04 UTC, A-Ostrovnyy commented on submissions/AndriyM/hooli-style-popup/index.html
> +            <footer class="footer"></footer>
Avoid unused tags

2022-08-28 09:04 UTC, andreymashko7 commented
corrected the last comments

2022-08-28 09:21 UTC, A-Ostrovnyy requested changes
Good progress!

2022-08-28 09:21 UTC, A-Ostrovnyy commented on submissions/AndriyM/hooli-style-popup/index.html
> +                        <ul class="nav__list">
Avoid shifting sibling elements on hover or focus. [Watch video](https://share.vidyard.com/watch/1hbFDzeSZpV3VqPfdwQCgc?)

2022-08-28 09:21 UTC, A-Ostrovnyy commented on submissions/AndriyM/hooli-style-popup/index.html
> +                                        alt="button to subscribe to alerts"
![image](https://user-images.githubusercontent.com/16196199/187066915-6efcce90-0d77-475c-8dac-26bb26ec103c.png)

2022-08-28 09:21 UTC, A-Ostrovnyy commented on submissions/AndriyM/hooli-style-popup/index.html
> +                                        alt=""
Why is this icon without an `alt` value, but the rest icon have an `alt` value?

2022-08-29 20:02 UTC, andreymashko7 commented
I hope it's better now.

2022-08-30 18:12 UTC, A-Ostrovnyy requested changes
Good progress!

2022-08-30 18:12 UTC, A-Ostrovnyy commented on submissions/AndriyM/hooli-style-popup/index.html
> +                                        alt="show menu-popup links"
For decorative images implemented with `img` tag, `alt` attribute value should be an empty value.

2022-08-31 09:06 UTC, andreymashko7 commented
fixed alt

2022-08-31 17:14 UTC, A-Ostrovnyy approved these changes
Well done!

2022-08-31 17:14 UTC, merged