memory-game
kottans/frontend-2022-homeworks pull request #228
Opened 2022-08-19 18:31 UTC by KonstantinOkhorzin

### Memory – Pair Game

[Demo](https://konstantinokhorzin.github.io/memory-game/) |
[Code base](https://github.com/KonstantinOkhorzin/memory-game)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-28 14:21 UTC, artem-trubin commented
Hi! There is an easily reproducible bug: if you click a lot of cards fast it just starts opening them all and you can win by clicking all of them. Please fix it before further code review.

2022-08-29 09:58 UTC, KonstantinOkhorzin commented
I fixed this.bug. Please, review.

2022-09-06 13:59 UTC, artem-trubin requested changes
Hi! Nice work! Let's make it even better! Check comments below.

2022-09-06 13:59 UTC, artem-trubin commented on submissions/KostiantynOkhorzin/memory-game/css/style.css
> +  font-family: Arial, Helvetica, sans-serif;
You already establish styles for `*`, why not do it there?

2022-09-06 13:59 UTC, artem-trubin commented on submissions/KostiantynOkhorzin/memory-game/script.js
> +const styleList = {
What is the purpose of this object? You don't use it in the `render()` method of a `GameCard` on line 35.

2022-09-06 13:59 UTC, artem-trubin commented on submissions/KostiantynOkhorzin/memory-game/script.js
> +                })
Why does flipping a correct pair of cards doesn't count as a `playerStep`?

2022-09-06 13:59 UTC, artem-trubin commented on submissions/KostiantynOkhorzin/memory-game/script.js
> +
Two empty lines

2022-09-06 13:59 UTC, artem-trubin commented on submissions/KostiantynOkhorzin/memory-game/script.js
> +const flippingCards = (e) => {
Strange name. I believe something like `handleCardFlip` should be more appropriate.

2022-09-06 17:23 UTC, KonstantinOkhorzin commented
I fixed all. Please, check the changes.

2022-09-08 13:57 UTC, artem-trubin requested changes
Great changes. There are some more comments below, please check them.

2022-09-08 13:57 UTC, artem-trubin commented on submissions/KostiantynOkhorzin/memory-game/css/style.css
> +@media (max-width: 425px) {
You already have a breakpoint of `425px` on the line 56. Just place this code there, no need to create separate `@media` blocks for the same width.

2022-09-08 13:57 UTC, artem-trubin commented on submissions/KostiantynOkhorzin/memory-game/script.js
> +const dataImgs = [
You store each item twice here. It doesn't make any sense and should be done in JS.

2022-09-08 13:57 UTC, artem-trubin commented on submissions/KostiantynOkhorzin/memory-game/script.js
> +    if (target.classList.contains(styleList.card)) {
When you see such a situation where you have a whole function body wrapped in one `if`, you can invert its condition and return if that happens instead. That allows you to remove the extra indentation for the whole function and make it more readable. Like this:

```js
if (!target.classList.contains(styleList.card)) return
// ...
```

2022-09-08 13:57 UTC, artem-trubin commented on submissions/KostiantynOkhorzin/memory-game/script.js
> +            if (selectedCards[0].dataset.name === selectedCards[1].dataset.name) {
This block (lines 61-74) has some repeating code. Try to figure out how you can shorten it.

2022-09-08 15:57 UTC, artem-trubin commented on submissions/KostiantynOkhorzin/memory-game/script.js
> +const dataImgs = [
You should only store unique items here and double them in your code.

2022-09-09 15:16 UTC, KonstantinOkhorzin commented
I fixed all. Please, check the changes.

2022-09-10 13:06 UTC, artem-trubin approved these changes
Good job!

2022-09-10 13:06 UTC, merged