Html css popup
kottans/frontend-2022-homeworks pull request #231
Opened 2022-08-20 11:37 UTC by vl-shevchenko

### html-css-popup

[Demo](https://vl-shevchenko.github.io/popup/) |
[Code base](https://github.com/vl-shevchenko/popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-20 14:57 UTC, vl-shevchenko commented
Hey!
My code has been validated.
I took into account all the tips from common mistakes when writing code.

2022-08-27 08:28 UTC, A-Ostrovnyy requested changes
Awesome design!

2022-08-27 08:28 UTC, A-Ostrovnyy commented on submissions/vl-shevchenko/html-css-popup/style.css
> +.list a{
Avoid styling by HTML tags except if you add base styles. [Reason](https://frontstuff.io/you-need-to-stop-targeting-tags-in-css). Also, avoid too specific CSS selectors. [Read about it](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)

2022-08-27 08:28 UTC, A-Ostrovnyy commented on submissions/vl-shevchenko/html-css-popup/index.html
> +                                        <input tabindex="-1" type="checkbox" id="checkbox_more">
`tabindex="-1"` don't allow to get browser focus and this button is not accessible from the keyboard.

2022-08-27 08:28 UTC, A-Ostrovnyy commented on submissions/vl-shevchenko/html-css-popup/index.html
> +                                </label>
`tabindex="-1"` don't allow to get browser focus and this button is not accessible from the keyboard. Also, `tabindex="0"` makes no sense on interactive elements.

2022-08-27 08:28 UTC, A-Ostrovnyy commented on submissions/vl-shevchenko/html-css-popup/index.html
> +                                        <hr class="more-hr">
Avoid using HTML elements for decorative purposes use CSS for it(pseudoelements, borders, etc)

2022-08-27 11:53 UTC, vl-shevchenko commented
Hey!
Bug fix - done.

2022-08-27 12:12 UTC, A-Ostrovnyy commented
For the future homework when you pushed the changes and they ready for review click `re-request review` button
![image](https://user-images.githubusercontent.com/16196199/187029715-69536c3c-f4b7-4d47-995d-c80d7407d136.png)

2022-08-27 12:18 UTC, A-Ostrovnyy requested changes
Good progress!

2022-08-27 12:18 UTC, A-Ostrovnyy commented on submissions/vl-shevchenko/html-css-popup/index.html
> +                                </label>
What about these `tabindex` attributes, be sure you fix all elements with `tabindex` attribute

2022-08-27 12:18 UTC, A-Ostrovnyy commented on submissions/vl-shevchenko/html-css-popup/style.css
> +#checkbox_knopka {
Avoid transliteration in naming entities.

2022-08-27 12:18 UTC, A-Ostrovnyy commented on submissions/vl-shevchenko/html-css-popup/style.css
> +.list img {
Same story: avoid styling by HTML tags

2022-08-27 19:09 UTC, vl-shevchenko commented
I am fix naming and delete styling by HTML tags.

2022-08-27 19:15 UTC, vl-shevchenko commented
But I see "tabindex"... File index.html in my repo not have "tabindex". 
Why does this happen?

2022-08-27 19:15 UTC, A-Ostrovnyy requested changes
One last issue)

2022-08-27 19:15 UTC, A-Ostrovnyy commented on submissions/vl-shevchenko/html-css-popup/style.css
> +#checkbox_btn:focus ~ label > a {
Avoid styling by HTML tags except if you add base styles. [Reason](https://frontstuff.io/you-need-to-stop-targeting-tags-in-css). Avoid using too specific CSS selectors. [Read more about that](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity).

2022-08-27 19:17 UTC, A-Ostrovnyy commented
> But I see "tabindex"... File index.html in my repo not have "tabindex". Why does this happen?

In what file/repository do you see `tabindex`?

2022-08-27 19:28 UTC, vl-shevchenko commented
> 
 [I see in this rerepository](https://github.com/kottans/frontend-2022-homeworks). in file index.html

 [Screenshot](https://github.com/vl-shevchenko/popup/blob/main/Screenshot%202022-08-27%20221921.jpg)

2022-08-27 19:33 UTC, A-Ostrovnyy commented
The code with red background is a deleted code. To see the final version of your code look to the `Files changed` tab
![image](https://user-images.githubusercontent.com/16196199/187045388-23555530-e632-4f92-97be-e8917ff1a048.png)

2022-08-27 19:47 UTC, vl-shevchenko commented
Sorry please. Thanks for the explanation.

2022-08-28 05:22 UTC, A-Ostrovnyy requested changes
See all unresolved comments
Good progress!

2022-08-28 05:22 UTC, A-Ostrovnyy commented on submissions/vl-shevchenko/html-css-popup/style.css
> +
Avoid too many unused lines in your work.

2022-08-28 12:23 UTC, vl-shevchenko commented
Hey!
I deleted styling by HTML tags and unused lines.

2022-08-28 16:46 UTC, A-Ostrovnyy approved these changes
Well done!

2022-08-28 16:46 UTC, merged