add frogger
kottans/frontend-2022-homeworks pull request #232
Opened 2022-08-20 14:03 UTC by bmukha

### frogger

[Demo](https://bmukha.github.io/frontend-nanodegree-arcade-game/) |
[Code base](https://github.com/bmukha/frontend-nanodegree-arcade-game)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-20 19:20 UTC, OleksiyRudenko requested changes
@bmukha very well done!
Let's improve code semantics and make it more OOP/SOLID principles compliant.

2022-08-20 19:20 UTC, OleksiyRudenko commented on submissions/bmukha/frogger/app.js
> +    this.height = 171;
I think these character width and height are true not only for enemy.
Also 101 is somehow relates to `505` above. Can we reduce number of constants and build some others using calculations?
As a peer developer tasked to amend this world (number of rows, columns, dimensions of tiles/characters) i'd like to change as few number as only possible.

P.S. Check magic numbers here and across entire codebase.

2022-08-20 19:20 UTC, OleksiyRudenko commented on submissions/bmukha/frogger/app.js
> +      player.currY <= this.currY + 85
(1) classes should not not refer to any global variables, like global variable `player`, which is an instance of `Player` class

(referring to global constants and globals provided by the gaming platform like `Resources` is OK);

Hint: pass `Player` instance as an argument to every enemy

(2) Separation of Concerns principle should be followed

(e.g. `update` method does only rendering and doesn't contain any unrelated **inline** code; for example collision check is defined as a dedicated method and only called from inside `update`)

2022-08-20 19:20 UTC, OleksiyRudenko commented on submissions/bmukha/frogger/app.js
> +      currentHolder.innerText = `Current score: ${currentScore}`;
Class shouldn't know anything about environment it operates in (whether it web or node engine).

2022-08-20 19:22 UTC, OleksiyRudenko commented
Oh, sometimes may hero gets killed right after stepping on the rock tile with no enemies close to him.
This effect starts after the first failure.
You may want to look into this bug.

2022-08-20 20:23 UTC, bmukha commented
Tnx for the comments/suggestions I really appreciate it! OOP is totally new territory for me, so, probably, implementing them will take a couple of days. A lot of reading/research needs to be done.

2022-08-30 16:56 UTC, bmukha commented
Hi. So, I made some changes to address the issues you pointed out. I believe I got rid of the respawning bug and improved the collision detection algorithm but it's probably the only things am sure about in all of this. Regarding reducing the number of constants, I succeeded only partially. The width of the field 505 can be derived from tile width 101 multiplied by the number of tiles in a row with no problem. But I failed to find such an apparent relationship on the Y axis. It looks like the real height of the png files is 171, but the step, which makes the game look nice, is 83, and the real height of the canvas is 606, which looks like 6 * 101. It's extremely confusing, I'm not gonna lie. And finally, I made collision detection a separate method and redone a couple more things into classes, but I'm far from sure that all this is correct. Somehow code looks even less clean and more bloated to me. Please, take a look.

2022-09-07 15:30 UTC, OleksiyRudenko approved these changes
@bmukha great job!
Check comments below for consideration.

2022-09-07 15:30 UTC, OleksiyRudenko commented on submissions/bmukha/frogger/app.js
> +  new Enemy(thirdEnemyY, player, env, scoreBoard),
What if I need to add 20 more enemies?
Do I need to define `fourthEnemyY` etc or this `Y`'s are actually y-coords for the field rows?

2022-09-07 15:30 UTC, merged

2022-09-07 16:37 UTC, bmukha commented on submissions/bmukha/frogger/app.js
> +class Environment {
Thank you for your feedback, really appreciate it!