Task Js DOM
kottans/frontend-2022-homeworks pull request #237
Opened 2022-08-20 17:52 UTC by OlexiyDobroskok

### Document Object Model

[Demo](https://olexiydobroskok.github.io/JS__DOM/) |
[Code base](https://github.com/OlexiyDobroskok/JS__DOM)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-24 14:43 UTC, madmaxWMFU requested changes
Good work. See some comments below.

2022-08-24 14:43 UTC, madmaxWMFU commented on submissions/OlexiyDobroskok/task_js_dom/script.js
> +    button.id = "dt" + [i];
Try to use methods of an array (map, reduce, forEach)

2022-08-24 14:43 UTC, madmaxWMFU commented on submissions/OlexiyDobroskok/task_js_dom/script.js
> +aside.className = "sidebar";
The variables must be as constant.

2022-08-24 14:43 UTC, madmaxWMFU commented on submissions/OlexiyDobroskok/task_js_dom/script.js
> +let main = document.querySelector(".content");
Set better naming for variables.
`mainList, btnList ......`

2022-08-24 14:43 UTC, madmaxWMFU commented on submissions/OlexiyDobroskok/task_js_dom/script.js
> +contentCreator(dt0);
Create an initial variable.

2022-08-24 14:43 UTC, madmaxWMFU commented on submissions/OlexiyDobroskok/task_js_dom/script.js
> +  for (let i = 0; i < darkTowerSeries.length; i++) {
I would recommend adding all variables which you create in this function.
Your function gets a parameter, it is good. Try to use a method of array `find` or `filter` to get needed item from array list.

2022-08-24 14:43 UTC, madmaxWMFU commented on submissions/OlexiyDobroskok/task_js_dom/script.js
> +aside.onclick = function (event) {
Use [event delegation](https://javascript.info/event-delegation)

2022-08-25 12:43 UTC, madmaxWMFU requested changes
Add a background style for the text. Because the letters blend into the background image

2022-08-25 12:43 UTC, madmaxWMFU commented on submissions/OlexiyDobroskok/task_js_dom/script.js
> +  let target = event.target;
Must be `const`

2022-08-25 12:43 UTC, madmaxWMFU commented on submissions/OlexiyDobroskok/task_js_dom/script.js
> +    button.innerHTML = darkTowerSeries[index].title;
What is the mean name 'el'? It is better named as 'serie'
```suggestion
    button.innerHTML = el.title;
```

2022-08-25 12:43 UTC, madmaxWMFU commented on submissions/OlexiyDobroskok/task_js_dom/script.js
> +  bookImage.src = contentData[0].photo;
Read about [destruction](https://javascript.info/destructuring-assignment)

2022-08-26 10:57 UTC, madmaxWMFU requested changes

2022-08-26 10:57 UTC, madmaxWMFU commented on submissions/OlexiyDobroskok/task_js_dom/script.js
> +    button.className = "sidebar__button";
Read about [Array.map](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/map) and [array destructuring](https://javascript.info/destructuring-assignment#array-destructuring).
Then you can write your code more simply.

2022-08-26 10:57 UTC, madmaxWMFU commented on submissions/OlexiyDobroskok/task_js_dom/script.js
> +  const [serie] = contentData;
It is not necessary. You are using a filter that has a search result by id.

2022-08-26 10:57 UTC, madmaxWMFU commented on submissions/OlexiyDobroskok/task_js_dom/script.js
> +  console.log(serie);
Delete debug line.

2022-08-26 10:57 UTC, madmaxWMFU commented on submissions/OlexiyDobroskok/task_js_dom/script.js
> +const frontPage = contentCreator(dt0);
Create initial variable with value 'dt0';

2022-08-27 09:47 UTC, madmaxWMFU requested changes

2022-08-27 09:47 UTC, madmaxWMFU commented on submissions/OlexiyDobroskok/task_js_dom/script.js
> +const frontPage = contentCreator(aboutSeries);
```suggestion
contentCreator(aboutSeries);
```

2022-08-27 09:47 UTC, madmaxWMFU commented on submissions/OlexiyDobroskok/task_js_dom/script.js
> +sidebar.addEventListener("click", function (event) {
```suggestion
sidebar.addEventListener("click", function ({ target }) {
```

2022-08-27 09:47 UTC, madmaxWMFU commented on submissions/OlexiyDobroskok/task_js_dom/script.js
> +  const [serie] = darkTowerSeries.filter((serie) => eventBtn.id === serie.id);
```suggestion
  const contentData = darkTowerSeries.filter((serie) => eventBtn.id === serie.id);
  const [{ title, quote, about, photo, alt }] = contentData;
```

2022-08-27 09:47 UTC, madmaxWMFU commented on submissions/OlexiyDobroskok/task_js_dom/script.js
> +  return buttonList;
```suggestion
    return darkTowerSeries.map(serie => {
      const { id, title } = serie;
      const btn = document.createElement('button');
      btn.classList.add('sidebar__button');
      btn.id = id;
      btn.innerText = title;
      return btn;
    });
```

2022-08-27 10:23 UTC, OlexiyDobroskok commented
@madmaxWMFU thanks for the help!

2022-08-27 11:43 UTC, madmaxWMFU approved these changes
Great, I approve of your work. Good luck with future tasks!

2022-08-27 11:43 UTC, merged