HTML-CSS-Popup task
kottans/frontend-2022-homeworks pull request #242
Opened 2022-08-21 07:49 UTC by Dovahkiin1991

### HTML-CSS-Popup

[Demo](https://dovahkiin1991.github.io/html-css-popup/) |
[Code base](https://github.com/Dovahkiin1991/html-css-popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-22 06:53 UTC, Dovahkiin1991 commented
Hey, my code meets all requirements.

2022-08-27 08:45 UTC, A-Ostrovnyy requested changes
Good work!

2022-08-27 08:45 UTC, A-Ostrovnyy commented on submissions/Dovahkiin1991/html-css-popup/css/styles.css
> +.navbar__item input:checked ~ .navbar__sub {
Avoid styling by HTML tags except if you add base styles. [Reason](https://frontstuff.io/you-need-to-stop-targeting-tags-in-css)
Also, avoid too specific CSS selectors. [Read about it](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)

2022-08-27 08:45 UTC, A-Ostrovnyy commented on submissions/Dovahkiin1991/html-css-popup/css/styles.css
> +    border: 1px solid transparent;
:fire:

2022-08-27 08:45 UTC, A-Ostrovnyy commented on submissions/Dovahkiin1991/html-css-popup/index.html
> +                                <img src="./images/icons/calendar.png" alt="Calendar Icon">
Read how and when to populate alt attribute value [Как правильно написать alt-текст](https://htmlacademy.ru/blog/articles/alt-text)

2022-08-27 08:45 UTC, A-Ostrovnyy commented on submissions/Dovahkiin1991/html-css-popup/index.html
> +                    <ul class="navbar navbar__sub navbar__sub--icons">
Please fix the popup size, it's hard to understand what content is inside the popup
![image](https://user-images.githubusercontent.com/16196199/187022734-ed4966ae-d1c2-42af-b784-eae43252d4c0.png)

2022-08-27 18:40 UTC, Dovahkiin1991 commented on submissions/Dovahkiin1991/html-css-popup/index.html
> +                                <img src="./images/icons/calendar.png" alt="Calendar Icon">
Removed the word "icon" from icons alt text

2022-08-27 19:10 UTC, A-Ostrovnyy approved these changes
Well done!

2022-08-27 19:10 UTC, merged