HTML and CSS Popup
kottans/frontend-2022-homeworks pull request #253
Opened 2022-08-22 09:13 UTC by MishaDerkach

_**УВАЖНО прочитайте і виконайте всі інструкції нижче перед тим як подати код на рев'ю.**_
1. Відформатуйте код, виправте неправильні відступи, видаліть непотрібні рядки, додайте пустий рядок у кінці кожного файлу, щоб ревʼюверу було зручно читати ваш код. Відформатувати код можна за допомогою [Prettier](https://prettier.io/playground). 
1. Перевірте свій код на наявність [типових помилок](https://kottans.org/documentation/docs/doc/code-review/#typical-mistakes). Пройдіться по всім пунктам відповідно до вашого завдання і виправте знайдені помилки.
1. Опублікуйте свою програму на [сторінках GitHub](https://github.com/kottans/frontend-2021-homeworks/blob/main/publish-your-app.md).
1. Переконайтеся, що назва вашого PR містить назву завдання.
1. Ваш код розміщено у бранчі, створеній спеціально для цього завдання (не `main`, не `master`, не бранча для іншого завдання).
1. Додайте тільки ті файли, які необхідні для рев'ю (код, CSS, HTML, які написані вами; не додавайте картинки, бо це робить репозиторій важким і відволікає рев'юерів)
1. Відредагуйте це повідомлення, як описано в наступних пунктах.
1. Змініть відповідно назву завдання та посилання нижче.
1. Видаліть весь текст вище із цим рядком включно.

### task name

[Demo](https://your-username.github.io/app-repo-name) |
[Code base](https://github.com/your-username/app-repo-name)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-27 09:16 UTC, A-Ostrovnyy requested changes
Good work!

2022-08-27 09:16 UTC, A-Ostrovnyy commented on submissions/MishaDerkach/html-css-popup/index.html
> +        <nav class="nav">
I think you have enough space to put it in one line on mobile)
![image](https://user-images.githubusercontent.com/16196199/187023784-466e3b05-6839-437f-b81e-49025e4c08ec.png)

2022-08-27 09:16 UTC, A-Ostrovnyy commented on submissions/MishaDerkach/html-css-popup/index.html
> +                                    <img src="popup-icons/apps.png" alt="Apps" class="content-list__image">
Read how and when to populate alt attribute value [Как правильно написать alt-текст](https://htmlacademy.ru/blog/articles/alt-text)

2022-08-27 09:17 UTC, A-Ostrovnyy requested changes
Good work!
Sorry for the late response.

2022-09-13 19:32 UTC, MishaDerkach commented
Good evening! I'm so sorry for my late changes in the work. I can't do it earlier. So now modified my popup using your recomendations.

2022-09-14 17:42 UTC, A-Ostrovnyy requested changes
Don't worry about that.
Good progress!

2022-09-14 17:42 UTC, A-Ostrovnyy commented on submissions/MishaDerkach/html-css-popup/index.html
> +                                    <img src="popup-icons/calendar.png" class="content-list__image">
```suggestion
    <img src="popup-icons/calendar.png" class="content-list__image" alt="">
```
`alt` attribute is required `img` attribute

2022-09-15 15:53 UTC, MishaDerkach commented
Good evening. I modified my index.html by your recomendation.

2022-09-15 17:32 UTC, A-Ostrovnyy approved these changes
Well done!

2022-09-15 17:32 UTC, merged

2022-09-15 17:43 UTC, MishaDerkach commented
Thanks!