task-js-oop
kottans/frontend-2022-homeworks pull request #255
Opened 2022-08-22 11:13 UTC by Vlada-khom

### task js-oop

[Demo](https://vlada-khom.github.io/frontend-nanodegree-arcade-game/) |
[Code base](https://github.com/Vlada-khom/frontend-nanodegree-arcade-game)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-23 09:23 UTC, Vlada-khom commented
I have checked my code.

2022-08-25 14:03 UTC, OleksiyRudenko requested changes
@Vlada-khom a really good job!
Need some improvements though.

2022-08-26 14:53 UTC, OleksiyRudenko requested changes
@Vlada-khom good improvement!
Although some issues remain unsolved.
As a peer developer, how I can modify the game by changing as little things as only possible?
If a cell width changes, do I need to also calculate overall field width? I'd prefer the code do this for me.

2022-08-26 14:53 UTC, OleksiyRudenko commented on submissions/Vlada-khom/task-js-oop/app.js
> +let allEnemies = [ROW_FOR_ENEMIES.one, ROW_FOR_ENEMIES.two, ROW_FOR_ENEMIES.three].map(
Why not `ROW_FOR_ENEMIES[1], ...[2], [3]`? A genuine question.

2022-08-26 14:53 UTC, OleksiyRudenko commented on submissions/Vlada-khom/task-js-oop/app.js
> +let player = new Player(X_START_PLAYER, Y_START_PLAYER, count);
Why between Enemy methods definition?

2022-08-26 14:53 UTC, OleksiyRudenko commented on submissions/Vlada-khom/task-js-oop/app.js
> +    allEnemies.forEach((el) => (el.xMove = el.x));
[This comment](https://github.com/kottans/frontend-2022-homeworks/pull/255#discussion_r955001848) remains unaddressed.

2022-08-26 14:53 UTC, OleksiyRudenko commented on submissions/Vlada-khom/task-js-oop/app.js
> +  three: 60
If I add row `four` how do I calculate the required number?

2022-08-26 14:53 UTC, OleksiyRudenko commented on submissions/Vlada-khom/task-js-oop/app.js
> +  height: 400,
Can this be calculated from something more basic and comprehensible?

2022-09-16 18:32 UTC, closed without merging