HTML CSS Popup
kottans/frontend-2022-homeworks pull request #267
Opened 2022-08-22 19:05 UTC by nvklap

### HTML CSS Popup

[Demo](https://nvklap.github.io/hooli-style-popup/) |
[Code base](https://github.com/nvklap/hooli-style-popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-23 12:49 UTC, nvklap commented
I checked the code and didn't find any common mistakes.

2022-08-27 09:50 UTC, A-Ostrovnyy requested changes
Good work!
Sorry for the late response

2022-08-27 09:50 UTC, A-Ostrovnyy commented on submissions/nvklap/popup/css/style.css
> +.logo img {
Avoid styling by HTML tags except if you add base styles. [Reason](https://frontstuff.io/you-need-to-stop-targeting-tags-in-css) Also, avoid too specific CSS selectors. [Read about that](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)

2022-08-27 09:50 UTC, A-Ostrovnyy commented on submissions/nvklap/popup/index.html
> +        </a>
:fire:

2022-08-27 09:50 UTC, A-Ostrovnyy commented on submissions/nvklap/popup/index.html
> +                  </label>
Logically when the second part of popup is open you should hide `More` button)

2022-08-27 15:11 UTC, nvklap commented
Thank you for the feedback. Provided articles have been very insightful. I made several fixes. Please, review my submission again.

2022-08-27 15:43 UTC, A-Ostrovnyy approved these changes
Well done!

2022-08-27 15:43 UTC, merged