Task a Tiny JS World
kottans/frontend-2022-homeworks pull request #271
Opened 2022-08-23 07:13 UTC by OlexiyDobroskok

### A Tiny JS World

[Demo](https://olexiydobroskok.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/OlexiyDobroskok/a-tiny-JS-world)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-28 12:29 UTC, OlexiyDobroskok commented
Made some self-checks to fix most common issues

2022-09-07 14:03 UTC, OleksiyRudenko requested changes
@OlexiyDobroskok quite a decent job done!
Let's polish it.

2022-09-07 14:03 UTC, OleksiyRudenko commented on submissions/OlexiyDobroskok/task_aTinyJsWorld/index.js
> +  return allProperties;
A classic use case for `Array#map`

2022-09-10 14:23 UTC, OlexiyDobroskok commented on submissions/OlexiyDobroskok/task_aTinyJsWorld/index.js
> +  return allProperties;
Done =)

2022-09-10 14:35 UTC, OlexiyDobroskok commented
Made the code a little cleaner :)

2022-09-20 15:53 UTC, OleksiyRudenko approved these changes
@OlexiyDobroskok great job!
CHeck the comment below for a learning to use.

2022-09-20 15:53 UTC, OleksiyRudenko commented on submissions/OlexiyDobroskok/task_aTinyJsWorld/index.js
> +    })
If an arrow function has a single statement and the statement is `return`, you do not need neither surrounding curly braces nor `return` keyword.
Also if an arrow function has exactly one argument parentheses can be skipped.

Compare readability:
```
.map((prop) => {
  return resident[prop];
})

.map(prop => resident[prop])
```

Same refers to the enclosing function in this case. Proper formatting will help to keep nested code radable.

2022-09-20 15:53 UTC, merged