Js-oop frogger game
kottans/frontend-2022-homeworks pull request #282
Opened 2022-08-23 21:10 UTC by HelenGreent

### Object Oriented JS (frogger)

[Demo](https://helengreent.github.io/kottans-frogger-game) |
[Code base](https://github.com/HelenGreent/kottans-frogger-game)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-10-04 17:40 UTC, HelenGreent commented
re-open

2022-10-04 18:43 UTC, OleksiyRudenko commented
We still have irrelevant commits that add code from a different task here
![image](https://user-images.githubusercontent.com/8686631/193900422-4aa30e58-8c1f-4b7c-b7b0-ad9c3a3d9a9d.png)

Check the bot's comments in these regards and fix. Do not ignore bot's suggestion to seek help and ask questions in STudents' chat.

2022-10-09 13:40 UTC, OleksiyRudenko commented
This will delete your earlier submission.
On commecrial projects this is something we want to avoid.
![image](https://user-images.githubusercontent.com/8686631/194760150-b20d8c61-a8be-4d40-93ee-342db2fb7fa0.png)

2022-10-09 13:43 UTC, OleksiyRudenko requested changes
@HelenGreent a pretty decent job done.
Although one improtant issue yet to fix.
And we do not want to remove any code outside the scope of current PR (see the comment above)

2022-10-09 13:43 UTC, OleksiyRudenko commented on submissions/HelenGreent/js-oop/app.js
> +  allEnemies.forEach(function (enemy) {
>     * [ ] classes do not refer to any global variables, like global variable `player`, which is an instance of `Player` class
>      (referring to global constants and globals provided by the gaming platform like `Resources` is OK);
>      Hint: pass `Player` instance as an argument to every enemy

2022-10-09 13:58 UTC, HelenGreent commented
Understand it, but I didn’t find a better way to fix my issue than deleting tiny-js-world from an oop-exercise feature in the current PR. I was thinking about changing history but it didn’t change the mistake

2022-10-09 15:55 UTC, OleksiyRudenko commented
Open a new PR for this, following the contribution instructions.
Learn to fix this type of git-wrokflow mistakes. You will need this on a commercial project. Constribution FAQ section offers a relevant learning material.

2022-10-11 21:37 UTC, HelenGreent commented
> Open a new PR for this, following the contribution instructions. Learn to fix this type of git-wrokflow mistakes. You will need this on a commercial project. Constribution FAQ section offers a relevant learning material.

Should I use "git revert" in this situation and push a new commit which reverts the pushed commits?

2022-10-12 21:58 UTC, HelenGreent commented
> Open a new PR for this, following the contribution instructions. Learn to fix this type of git-wrokflow mistakes. You will need this on a commercial project. Constribution FAQ section offers a relevant learning material.

link to new PR:
https://github.com/kottans/frontend-2022-homeworks/pull/748

2022-10-13 20:34 UTC, closed without merging