Document Object Model
kottans/frontend-2022-homeworks pull request #283
Opened 2022-08-24 07:03 UTC by Yanyshpolska

### Document Object Model

[Demo](https://yanyshpolska.github.io/DOM/) |
[Code base](https://github.com/Yanyshpolska/DOM)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-24 08:04 UTC, Yanyshpolska commented
Hi. I have changed some variables and function names. 
Please review.

2022-08-25 09:13 UTC, madmaxWMFU requested changes
Nice work. See some comments below.

2022-08-25 09:13 UTC, madmaxWMFU commented on submissions/yanyshpolska/dom/js/script.js
> +  listOfTeasNames[i].onclick = doesChangeTea;
Read and use [event delegation](https://javascript.info/event-delegation)

2022-08-25 09:13 UTC, madmaxWMFU commented on submissions/yanyshpolska/dom/js/script.js
> +  descriptionOfTea.innerHTML = objectTea.description;
Don't update elements. Create or append a template with content.

2022-08-25 09:13 UTC, madmaxWMFU commented on submissions/yanyshpolska/dom/js/script.js
> +    (obj) => obj.type === event.srcElement.innerHTML
I recommend using property `event.target`

2022-08-25 16:55 UTC, Yanyshpolska commented
Hi! Thanks for your comments. Reworked as advised. Please review.

2022-08-26 11:47 UTC, madmaxWMFU requested changes

2022-08-26 11:47 UTC, madmaxWMFU commented on submissions/yanyshpolska/dom/js/script.js
> +  const wholeArticle = document.querySelector("article.more");
```suggestion
  const wholeArticle = document.querySelector(".more");
```

2022-08-26 11:47 UTC, madmaxWMFU commented on submissions/yanyshpolska/dom/js/script.js
> +    (obj) => obj.type === event.target.innerHTML
If we have the same name in the result we get more than one type of tea.
Modernize your tea list, and add an `id` or `teaId` property. This field was unique to one type of tea. The id field you can write to a [dataset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset) of the element. Then you can compare the value from the date and the selected element.

2022-08-26 11:47 UTC, madmaxWMFU commented on submissions/yanyshpolska/dom/js/script.js
> +  )[0];
Avoid construction `[ ]`. If you want find one element try  ti use method find.

2022-08-26 11:47 UTC, madmaxWMFU commented on submissions/yanyshpolska/dom/js/script.js
> +createContent(teas[0]);
Create a variable with an initial value.

2022-08-26 12:54 UTC, Yanyshpolska commented
Hi! Thanks for your comments. Reworked as advised. Please review.

2022-08-26 18:57 UTC, madmaxWMFU requested changes

2022-08-26 18:57 UTC, madmaxWMFU commented on submissions/yanyshpolska/dom/js/script.js
> +const initValue = teas[Math.floor(Math.random() * teas.length)];
```suggestion
const getRandomNumber = () => Math.floor(Math.random() * teas.length);
const initValue = getRandomNumber();
createContent(teas[initValue]);
```

2022-08-26 18:57 UTC, madmaxWMFU commented on submissions/yanyshpolska/dom/js/script.js
> +listOfTeasNames.onclick = function (event) {
Use `addEventListener`

2022-08-26 19:26 UTC, Yanyshpolska commented
Reworked as advised. Please review.

2022-08-27 03:59 UTC, madmaxWMFU approved these changes
Great, I approve of your work. Good luck with future tasks!

2022-08-27 04:00 UTC, merged