A Tiny JS World
kottans/frontend-2022-homeworks pull request #288
Opened 2022-08-24 10:53 UTC by Yanyshpolska

### A Tiny JS World

[Demo](https://yanyshpolska.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/Yanyshpolska/a-tiny-JS-world)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-24 15:39 UTC, Yanyshpolska commented
Self-check completed.

2022-08-25 10:35 UTC, OleksiyRudenko requested changes
@Yanyshpolska well done!
One improvement and we are done.

2022-08-25 10:35 UTC, OleksiyRudenko commented on submissions/yanyshpolska/tiny-world/index.js
> +  print(arr.join("; "));
Please use `Array#map` and `Array` methods chaining here. You will find `arr` variable redundant.

2022-08-25 14:39 UTC, OleksiyRudenko approved these changes
@Yanyshpolska great job!

2022-08-25 14:39 UTC, merged