add index.html style.css
kottans/frontend-2022-homeworks pull request #292
Opened 2022-08-24 14:15 UTC by OlgaBarnikova8

### HTML і CSS практика: Hooli-style Popup

[Demo] https://olgabarnikova8.github.io/hooli-style-popup/
[Code base] https://github.com/OlgaBarnikova8/kottans-frontend/tree/main/Popup

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-24 14:16 UTC, OlgaBarnikova8 commented
Пожалуйста проверьте.

2022-08-24 17:02 UTC, OlgaBarnikova8 commented
Please, review.

2022-08-27 10:34 UTC, A-Ostrovnyy requested changes
Good work!

2022-08-27 10:34 UTC, A-Ostrovnyy commented on submissions/OlgaBarnikova/Popup/index.html
> +    <nav class="navigation">
Please fix mobile version
![image](https://user-images.githubusercontent.com/16196199/187026278-517da59d-2bcb-498a-b892-e1c4c5e109d0.png)

2022-08-27 10:34 UTC, A-Ostrovnyy commented on submissions/OlgaBarnikova/Popup/index.html
> +                        <label for="popup-more" class="popup_more_icon">More</label>
Add styles on focus state. Also, hide this button when the second part of the popup is open.

2022-08-27 10:34 UTC, A-Ostrovnyy commented on submissions/OlgaBarnikova/Popup/index.html
> +</html>
Add an empty line at the end of each file. [Reason](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline?noredirect=1&lq=1)

2022-08-27 10:34 UTC, A-Ostrovnyy commented on submissions/OlgaBarnikova/Popup/style.css
> +:focus {
This is an invalid CSS selector: you can't set pseudoclass to nothing, you should provide an element:
```CSS
.block:focus {}

.a:focus {}

*:focus {}
```

2022-08-28 15:55 UTC, OlgaBarnikova8 commented
HTML і CSS практика: Hooli-style Popup
[Demo] https://olgabarnikova8.github.io/hooli-style-popup/
[Code base] https://github.com/OlgaBarnikova8/kottans-frontend/tree/main/Popup

Thanks for your work!
Please, review.

2022-08-29 16:46 UTC, A-Ostrovnyy requested changes
Good progress!

2022-08-29 16:46 UTC, A-Ostrovnyy commented on submissions/OlgaBarnikova/Popup/index.html
> +                        </label>
Users must have the ability to open a popup with a keyboard. [Watch video](https://share.vidyard.com/watch/ZDCPyrd5EAnKvP895smxQc?)

2022-08-29 16:46 UTC, A-Ostrovnyy commented on submissions/OlgaBarnikova/Popup/index.html
> +                            <input type="checkbox" id="popup-more" class="popup_input_more" />
Add styles on focus state, also, hide this button when the second part of the popup is open. [Watch video](https://share.vidyard.com/watch/ZDCPyrd5EAnKvP895smxQc?)

2022-09-01 13:45 UTC, OlgaBarnikova8 commented
HTML і CSS практика: Hooli-style Popup
[Demo](https://olgabarnikova8.github.io/hooli-style-popup/) |
[Code base](https://github.com/OlgaBarnikova8/kottans-frontend/tree/main/Popup)

Thanks for your work!
Please, review.

2022-09-01 16:08 UTC, A-Ostrovnyy approved these changes
Well done!

2022-09-01 16:09 UTC, merged