Frogger task
kottans/frontend-2022-homeworks pull request #299
Opened 2022-08-25 16:05 UTC by Tedzury

### Frogger game

[Demo](https://tedzury.github.io/FroggerGame/) |
[Code base](https://github.com/Tedzury/FroggerGame)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-25 17:06 UTC, Tedzury commented
Good evening! Applied minor fixes after self check. Ready to ask for review :)

2022-08-26 14:59 UTC, OleksiyRudenko requested changes
@Tedzury nice try.

As a peer developer I want to understand what is behind numbers. That is why we use named constants and calculate more complex things from basic and comprehensible ones.

As a peer developer I want to make changes to as few lines of code as possible when needed. That is why we write DRY code.

2022-08-26 14:59 UTC, OleksiyRudenko commented on submissions/Oleksii_Drohachov/Frogger_task/app.js
> +  this.x = -80;
What is -80?

2022-08-26 14:59 UTC, OleksiyRudenko commented on submissions/Oleksii_Drohachov/Frogger_task/app.js
> +  this.height = 60;
Duplication of code. Make code DRY.

2022-08-26 14:59 UTC, OleksiyRudenko commented on submissions/Oleksii_Drohachov/Frogger_task/app.js
> +  this.y = 400;
What are 200 and 400?
The same question to other mystery numbers across the code.

2022-08-27 08:57 UTC, Tedzury commented
Good morning. Made slight refactoring, renamed some variables to better readability, tried to remove repeating for width and height, but failed. Assigned an entity as proto to player and it works, but I can't assing the entity as prototype for enemy, it break the app completely, function update stops working. I think it's because we are putting the enemies in the array and somehow it breaks the main update function.

2022-09-07 14:49 UTC, OleksiyRudenko commented
> Made slight refactoring, renamed some variables to better readability, 
👍 

> tried to remove repeating for width and height, but failed.
👍 

> Assigned an entity as proto to player and it works, but I can't assing the entity as prototype for enemy, it break the app completely, function update stops working. I think it's because we are putting the enemies in the array and somehow it breaks the main update function.

If done properly it should work.
If you try to extend plain object then it will definitely fail. However it is just my hypotheses. Better told on the code.
Consider two options:
(1) Submit the "wrong" code for `Entity` and we will see where it goes
(2) Seek help in Students' chat

2022-09-07 14:54 UTC, OleksiyRudenko requested changes
@Tedzury good progress!
Although code needs further improvements.

2022-09-07 14:54 UTC, OleksiyRudenko commented on submissions/Oleksii_Drohachov/Frogger_task/app.js
> +    this.xAxisPosition = -80;
Still a mistery number? Is it related to `entity.width` somehow?

2022-09-07 14:54 UTC, OleksiyRudenko commented on submissions/Oleksii_Drohachov/Frogger_task/app.js
> +    moveSpeed: 100,
As a peer developer I am tasked to add 5 more enemies.
I want to do it with the least effort possible. The numbers here look mysteriously.
What I see and know is that the play field has clear rows. Ideally, I'd like to define a row for an enemy and let the program calculate pixels.

2022-09-07 14:54 UTC, OleksiyRudenko commented on submissions/Oleksii_Drohachov/Frogger_task/app.js
> +  this.moveYAxis = 90;
Mysterious numbers.

2022-09-07 14:54 UTC, OleksiyRudenko commented on submissions/Oleksii_Drohachov/Frogger_task/app.js
> +    player.win();
What is the way to address object instance properties and methods?
This is not a rhetoric question. You may also want to review the module's theoretical materials.

2022-09-07 14:54 UTC, OleksiyRudenko commented on submissions/Oleksii_Drohachov/Frogger_task/app.js
> +    player.yAxisPosition + player.height > this.yAxisPosition
From the checklist:
> * [ ] classes do not refer to any global variables, like global variable `player`, which is an instance of `Player` class
>      (referring to global constants and globals provided by the gaming platform like `Resources` is OK);
>      Hint: pass `Player` instance as an argument to every enemy

2022-09-11 18:14 UTC, Tedzury commented
Good evening. I asked for help in students chat and found response :) Totally refactored almost everything. Hope, it is what was  needed, if not - sorry for my dumbness :(

2022-09-20 12:32 UTC, OleksiyRudenko requested changes
@Tedzury very good job and great improvement since v1!
Yet a few improvements are required.

2022-09-20 12:32 UTC, OleksiyRudenko commented on submissions/Oleksii_Drohachov/Frogger_task/app.js
> +  if (player.yAxisPosition < 0) {
Why do you refer to a particular `Player` instance here?
Looks weird when you obviously know the proper way of referring to object's properties.

2022-09-20 12:32 UTC, OleksiyRudenko commented on submissions/Oleksii_Drohachov/Frogger_task/app.js
> +    player.respawn();
> classes do not refer to any global variables, like global variable `player`, which is an instance of `Player` class
>  (referring to global constants and globals provided by the gaming platform like `Resources` is OK);
>  Hint: pass `Player` instance as an argument to every enemy

2022-09-20 12:32 UTC, OleksiyRudenko commented on submissions/Oleksii_Drohachov/Frogger_task/app.js
> +    yAxisPosition: thirdEnemyRow,
`firstAnythin`, `secondAnything` etc just like `anything1`, `anything2` clearly calls for an array.
`whatever[1]` or `whatever[natural number - 1]` looks more comprehensible.

Also using arrays will enable `Array` mehods. Imagine you are tasked to add more rows for enemies.

2022-09-20 12:32 UTC, OleksiyRudenko commented on submissions/Oleksii_Drohachov/Frogger_task/app.js
> +const emenyRowsModifier = 0.66;
0.66 looks weird. Do you research as to sprite images characteristics. Do not rely on some else's calculations/numbers, they may be wrong.

2022-09-21 12:48 UTC, Tedzury commented
Good day. Resolved all mistakes, slightly reafactored player and enemy classes to remove interdependence between them. Now passing a player to enemy as argument, and scoreBoards as argument to player. 

And, what took a lot of of energy - refactored allEmenies, now it's result of function, which returns an array of Enemies.

About your comment "0.66 looks weird. Do your own research of sprite images characteristics. Do not rely on some else's calculations/numbers, they may be wrong." - changed this variable to fixed 19 value. Don't know how to get rid of it, because it is just a visual variable, made to center bugs in center of the track, without it they visually fell down from track they are running.  I weren't cheating, found this number only by own visual inspection.

2022-09-26 10:18 UTC, OleksiyRudenko approved these changes
@Tedzury great job done!

2022-09-26 10:18 UTC, merged