popup
kottans/frontend-2022-homeworks pull request #308
Opened 2022-08-26 09:44 UTC by Westerinoo

_**УВАЖНО прочитайте і виконайте всі інструкції нижче перед тим як подати код на рев'ю.**_
1. Відформатуйте код, виправте неправильні відступи, видаліть непотрібні рядки, додайте пустий рядок у кінці кожного файлу, щоб ревʼюверу було зручно читати ваш код. Відформатувати код можна за допомогою [Prettier](https://prettier.io/playground). 
1. Перевірте свій код на наявність [типових помилок](https://kottans.org/documentation/docs/doc/code-review/#typical-mistakes). Пройдіться по всім пунктам відповідно до вашого завдання і виправте знайдені помилки.
1. Опублікуйте свою програму на [сторінках GitHub](https://github.com/kottans/frontend-2021-homeworks/blob/main/publish-your-app.md).
1. Переконайтеся, що назва вашого PR містить назву завдання.
1. Ваш код розміщено у бранчі, створеній спеціально для цього завдання (не `main`, не `master`, не бранча для іншого завдання).
1. Додайте тільки ті файли, які необхідні для рев'ю (код, CSS, HTML, які написані вами; не додавайте картинки, бо це робить репозиторій важким і відволікає рев'юерів)
1. Відредагуйте це повідомлення, як описано в наступних пунктах.
1. Змініть відповідно назву завдання та посилання нижче.
1. Видаліть весь текст вище із цим рядком включно.

### task name

[Demo](https://your-username.github.io/app-repo-name) |
[Code base](https://github.com/your-username/app-repo-name)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-27 13:08 UTC, A-Ostrovnyy requested changes
Good work!

2022-08-27 13:08 UTC, A-Ostrovnyy commented on submissions/Westerinoo/HTML-CSS-popup/index.html
> +    <title>Document</title>
Add proper page title.

2022-08-27 13:08 UTC, A-Ostrovnyy commented on submissions/Westerinoo/HTML-CSS-popup/index.html
> +                            <li class="popup__items"><a href="#"><img  src="./icons/files.png" alt="icon-files" class="icons"><span>files</span></a></li>
Use [Prettier](https://prettier.io/) for formatting code

2022-08-27 13:08 UTC, A-Ostrovnyy commented on submissions/Westerinoo/HTML-CSS-popup/style.css
> +a:focus{
Avoid styling by HTML tags except if you add base styles. [Reason](https://frontstuff.io/you-need-to-stop-targeting-tags-in-css). Avoid using too specific CSS selectors. [Read about it.](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)

2022-08-31 08:05 UTC, Westerinoo reviewed
corrected

2022-08-31 16:40 UTC, A-Ostrovnyy commented on submissions/Westerinoo/HTML-CSS-popup/index.html
> +                            <li class="popup__items"><a href="#"><img  src="./icons/files.png" alt="icon-files" class="icons"><span>files</span></a></li>
Still not fixed :cry:

2022-08-31 16:44 UTC, A-Ostrovnyy requested changes
Good progress!
Please don't resolve the comments. Comments must be resolved by the author.
Also, fix your first message in PR according to [this instraction](https://github.com/kottans/frontend-2022-homeworks/pull/308#issuecomment-1229189200)

2022-08-31 16:44 UTC, A-Ostrovnyy commented on submissions/Westerinoo/HTML-CSS-popup/index.html
> +                                </label>
Add `cursor: pointer` to indicate to the user about an interactive element.

2022-09-02 05:43 UTC, A-Ostrovnyy requested changes
One last issue)

2022-09-02 05:43 UTC, A-Ostrovnyy commented on submissions/Westerinoo/HTML-CSS-popup/index.html
> +                           <li class="popup__items"><a class   ="link-popup" href="#"><img class="icons" src="./icons/calendar.png" alt="icon-calendar"><span>calendar</span></a></li>
For decorative images implemented with `img` tag `alt` attribute must be an empty value. Icons are decorative images. Please set an empty value to `alt` attribute.

2022-09-02 17:11 UTC, A-Ostrovnyy approved these changes
Well done!
For future work don't resolve comments. Comments must be resolved by the author.

2022-09-02 17:11 UTC, merged