Add files from task HTML&CSS Practice
kottans/frontend-2022-homeworks pull request #321
Opened 2022-08-27 07:02 UTC by deveLabR

### HTML & CSS Practice

[Demo](https://develabr.github.io/hooli-style-popup/) |
[Code base](https://github.com/deveLabR/hooli-style-popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-27 07:50 UTC, deveLabR commented
I have finished the self-checks, and I want to believe that it does not sound too presumptuous

2022-08-27 16:06 UTC, A-Ostrovnyy requested changes
Good work!

2022-08-27 16:06 UTC, A-Ostrovnyy commented on submissions/develabr/hooli-style-popup/index.html
> +              <img src="./images/popup-button.png" alt="popup-button" />
Read how and when to populate alt attribute value [Как правильно написать alt-текст](https://htmlacademy.ru/blog/articles/alt-text)

2022-08-27 16:06 UTC, A-Ostrovnyy commented on submissions/develabr/hooli-style-popup/index.html
> +            <div class="menu__popup">
Fix mobile version
![image](https://user-images.githubusercontent.com/16196199/187038315-46681dfc-c951-4712-9bec-1224eec95d5e.png)

2022-08-28 09:13 UTC, A-Ostrovnyy requested changes
One last issue)

2022-08-28 09:13 UTC, A-Ostrovnyy commented on submissions/develabr/hooli-style-popup/index.html
> +                      alt="Calendar icon"
![image](https://user-images.githubusercontent.com/16196199/187066693-7ceb2e44-2d4f-47a1-bbec-0640ea4e8970.png)

2022-08-28 16:27 UTC, A-Ostrovnyy approved these changes
Awesome!

2022-08-28 16:27 UTC, merged