Building a Tiny JS World
kottans/frontend-2022-homeworks pull request #327
Opened 2022-08-27 18:53 UTC by ASTkach

### Tiny JS World

[Demo](https://astkach.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/ASTkach/a-tiny-JS-world/tree/tiny-js)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-28 16:43 UTC, ASTkach commented
I have completed self-check.

2022-09-07 14:06 UTC, OleksiyRudenko requested changes
@ASTkach quite a decent job done!
Let's use contemporary ES6/ES2015 JS features more.

2022-09-07 14:06 UTC, OleksiyRudenko commented on submissions/ASTkach/js-world/index.js
> +           item.friends;
Too much repetition of code (`item.`, `+"; " +`).
You will benefit from `Array#map` and `Array#join` to make code dry.

2022-09-07 14:06 UTC, OleksiyRudenko commented on submissions/ASTkach/js-world/index.js
> +}
A classic use case for `Array#forEach`

2022-09-07 14:06 UTC, OleksiyRudenko commented on submissions/ASTkach/js-world/index.js
> +    return item.species + "; " +
When an arrow function body has a single `return` statement then you do not need neither function body `{}` nor `return`

2022-09-20 12:14 UTC, OleksiyRudenko commented
The approach to handling objects and their props has changed drastically.
You could take some new learnings by following comments from the mentor, which would result in better code than what the majority of other students do.
You are free not to take the challenge.
Let me know if you want to make a step back and implement improvements based on your previous code or want to stick with current "average" implementation.

2022-12-10 08:39 UTC, closed without merging