Dom task
kottans/frontend-2022-homeworks pull request #334
Opened 2022-08-28 17:46 UTC by AriadnaKravchuk

### DOM

[Demo](https://ariadnakravchuk.github.io/DOM) |
[Code base](https://github.com/AriadnaKravchuk/DOM)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-29 11:49 UTC, AriadnaKravchuk commented
I completed self-checks

2022-08-30 09:20 UTC, madmaxWMFU requested changes
Excellent! See some comments below.

2022-08-30 09:20 UTC, madmaxWMFU commented on submissions/AriadnaKravchuk/dom/script.js
> +mainInner.innerHTML = createContent(characters[0]);
Set a variable with an initial value.

2022-08-30 09:20 UTC, madmaxWMFU commented on submissions/AriadnaKravchuk/dom/script.js
> +function createContent(character) {
Read about [destruction](https://javascript.info/destructuring-assignment). Also, use that you can select the first element.

2022-09-01 12:58 UTC, madmaxWMFU commented on submissions/AriadnaKravchuk/dom/script.js
> +const [firstPage] = characters
```suggestion
const [firstPage] = characters;
```

Use [prettier](https://prettier.io/)

2022-09-01 12:58 UTC, madmaxWMFU approved these changes
Great, I approve of your work. Good luck with future tasks!

2022-09-01 12:58 UTC, merged

2022-09-01 13:03 UTC, AriadnaKravchuk commented
> Great, I approve of your work. Good luck with future tasks!

Thanks!