Object Oriented JS
kottans/frontend-2022-homeworks pull request #335
Opened 2022-08-28 19:35 UTC by hisbvdis

### Object Oriented JS

[Demo](https://hisbvdis.github.io/kottans-frontend/pages/task_js_oop) |
[Code base](https://github.com/hisbvdis/kottans-frontend/tree/main/pages/object-oriented-js)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-07 18:43 UTC, hisbvdis commented on submissions/hisbvdis/task_js_oop/app.js
> +    up: () => this.y -= 80,
Заменил на размеры ячеек таблицы.
Коммит: b7b4a30

2022-09-07 18:44 UTC, hisbvdis commented on submissions/hisbvdis/task_js_oop/app.js
> +  new Enemy(field, -100, 225, 300, player),
Добавил функцию генерирования случайных врагов.
Коммит: 3d15d73

2022-09-07 19:16 UTC, OleksiyRudenko commented
Just noticed. This looks no good
![image](https://user-images.githubusercontent.com/8686631/188958951-135b056d-25fa-4351-ad4d-a6d18c9dcc13.png)

It means that PR may remove your earlier submission when merged.
Deletion means deletion. We need rather avoid any changes to unrelated files.

Check [FAQ and Troubleshooting section](https://github.com/kottans/frontend-2022-homeworks/#%D0%B4%D0%BE%D0%B2%D1%96%D0%B4%D0%BA%D0%BE%D0%B2%D1%96-%D0%BC%D0%B0%D1%82%D0%B5%D1%80%D1%96%D0%B0%D0%BB%D0%B8-%D1%82%D0%B0-%D1%83%D1%81%D1%83%D0%BD%D0%B5%D0%BD%D0%BD%D1%8F-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC) for the cure.

2022-09-07 20:36 UTC, hisbvdis commented
@OleksiyRudenko , 
Думаю, мне просто не следовало удалять файлы из папки с другой задачей.
Я думал, что в данной ветке их быть не должно.
Но я вроде ошибся.
Например, если я сейчас создам новую ветку, в ней будут папки других задач.
Я отменил коммит, в котором удалял те файлы (`git revert ...`)
Может этого достаточно будет?

P.S. Потому что инструкцию вообще не понял :(

2022-09-07 23:09 UTC, OleksiyRudenko commented
> @OleksiyRudenko , Думаю, мне просто не следовало удалять файлы из папки с другой задачей. Я думал, что в данной ветке их быть не должно. Но я вроде ошибся. Например, если я сейчас создам новую ветку, в ней будут папки других задач. Я отменил коммит, в котором удалял те файлы (`git revert ...`) Может этого достаточно будет?

Now PR looks good.

> 
> P.S. Потому что инструкцию вообще не понял :(

There is a safe space to ask questions when anything is not clear - Students' chat. Use the opportunity to learn from dozens of helpful people

2022-09-20 12:10 UTC, OleksiyRudenko requested changes
@hisbvdis very well done!
Yet a bit of demystification and human-friendliness will make code easier to extend and maintain.

2022-09-20 12:10 UTC, OleksiyRudenko commented on submissions/hisbvdis/task_js_oop/app.js
> +  this.enemyWidth = 83;
`enemy` part looks redundant. `enemy.enemyWidth`. Class name already provides context.

2022-09-20 12:10 UTC, OleksiyRudenko commented on submissions/hisbvdis/task_js_oop/app.js
> +      const randomSpeed = [200, 300, 400][i <= 2 ? i : getRandom(0, 2)];
Numbers 60, 120, -300 still look mysterious.
If I am tasked to add the 4th track for enemies, what number should I add?

Also I can comprehend the concept of rows. I'd prefer the ~calculator~ computer to convert comprehensible concepts into pixels.

2022-09-20 19:00 UTC, OleksiyRudenko approved these changes
@hisbvdis great job!

2022-09-20 19:00 UTC, merged