add oop-exercise
kottans/frontend-2022-homeworks pull request #350
Opened 2022-08-29 15:09 UTC by pashapushak1996

### OOP Exercise

[Demo](https://pashapushak1996.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/pashapushak1996/a-tiny-JS-world)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-29 19:03 UTC, pashapushak1996 commented
I have completed self-check)

2022-09-20 18:24 UTC, OleksiyRudenko requested changes
@pashapushak1996 good job!
Let's leverage JS OOP mechanics.

2022-09-20 18:24 UTC, OleksiyRudenko commented on submissions/pashapushak1996/oop-exercise/index.js
> +        this.species = this.constructor.name.toLowerCase();
Good solution!

2022-09-20 18:24 UTC, OleksiyRudenko commented on submissions/pashapushak1996/oop-exercise/index.js
> +};
This can be a part of class behaviour.
Also check for method overloading and extended `super` API.

2022-09-20 18:24 UTC, OleksiyRudenko commented on submissions/pashapushak1996/oop-exercise/index.js
> +        .filter((key) => inhabitant[key])
`key` is a generic term. Living beings are characterized by properties or features.

2022-09-20 19:23 UTC, OleksiyRudenko requested changes
@pashapushak1996 good improvement.
Let's make the code OOP/SOLID compliant.

2022-09-20 19:23 UTC, OleksiyRudenko commented on submissions/pashapushak1996/oop-exercise/index.js
> +        return inhabitantProps
Check OOP encapsulation and SOLID open-closed principles.
No need in external variable. A class should be self-sufficient.
Also every class should handle only properties it owns.

Method overloading and extended `super` API to the rescue.

2022-09-26 21:42 UTC, OleksiyRudenko approved these changes
@pashapushak1996 well done!

One note: do not let classes handle properties they do not own, even undirectly (in this code the root class actually forms output for properties owned by child classes), unless there is a really good reason for this. Imagine you change the way you handle way a child class stores hands (e.g. not a number but rather an array [left, right]) but still need to output their number.
To accomodate this you'd need to change the method in the root class. With a proper design a child class handles its own properties end-to-end.

2022-09-26 21:42 UTC, merged