Task js DOM
kottans/frontend-2022-homeworks pull request #356
Opened 2022-08-29 21:48 UTC by loki13btz

### side-menu (dom-api-task)

[Demo](https://loki13btz.github.io/side-menu/) |
[Code base](https://github.com/loki13btz/side-menu)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-01 18:44 UTC, madmaxWMFU requested changes
Don't use any library. In this task only vanilla JS.

2022-09-05 18:07 UTC, loki13btz commented
@madmaxWMFU I have removed the use of jQuery, please take a look;)

2022-09-07 09:44 UTC, madmaxWMFU requested changes

2022-09-07 09:44 UTC, madmaxWMFU commented on submissions/loki13btz/dom-api-task/script.js
> +      let menuItemId = Number(e.currentTarget.dataset.id);
Add listener, not for all items of the menu. Only for the parent (menuItems)

2022-09-07 09:44 UTC, madmaxWMFU commented on submissions/loki13btz/dom-api-task/script.js
> +        renderContent(menuItemId);
DRY

2022-09-07 09:44 UTC, madmaxWMFU commented on submissions/loki13btz/dom-api-task/script.js
> +  renderContent(1);
Set a value to the initial variable.

2022-09-07 09:44 UTC, madmaxWMFU commented on submissions/loki13btz/dom-api-task/script.js
> +  let menuItems = document.querySelectorAll(".side-menu_item");
All variables in your context must be `const`.

2022-09-07 09:44 UTC, madmaxWMFU commented on submissions/loki13btz/dom-api-task/script.js
> +document.addEventListener('DOMContentLoaded', function() {
Everything else can be moved beyond the body of the function and into separate created functions.
```suggestion
document.addEventListener('DOMContentLoaded', function() {
  renderContent(initialValue);
}
```

2022-09-08 10:07 UTC, madmaxWMFU requested changes

2022-09-08 10:07 UTC, madmaxWMFU commented on submissions/loki13btz/dom-api-task/script.js
> +  });
```suggestion
  menuItemList.addEventListener("click", function ({ target }) {
    addActive(target);
  });
  menuItemList.addEventListener("keydown", function ({ keyCode, target }) {
    if (keyCode == 32) {
      addActive(target);
    }
  });
```

2022-09-08 10:07 UTC, madmaxWMFU commented on submissions/loki13btz/dom-api-task/script.js
> +  const pageContent = document.querySelector(".content .content-wrapper");
```suggestion
  const pageContent = document.querySelector(".content-wrapper");
```

2022-09-08 10:07 UTC, madmaxWMFU commented on submissions/loki13btz/dom-api-task/script.js
> +  menuContent.style.backgroundImage = `url(${img})`;
Do it by the rules in CSS and class to the element.

2022-09-09 13:28 UTC, loki13btz commented
@madmaxWMFU please, take a look the changes

2022-09-11 09:58 UTC, madmaxWMFU requested changes

2022-09-11 09:58 UTC, madmaxWMFU commented on submissions/loki13btz/dom-api-task/style.css
> +    margin-top: 28%;
`padding-top: 28%`
And in line 214 `padding-top: 15%`

2022-09-11 09:58 UTC, madmaxWMFU commented on submissions/loki13btz/dom-api-task/style.css
> +    .side-menu_content {
Mabey you want to write `#side-menu_content`?

2022-09-14 04:26 UTC, madmaxWMFU approved these changes
Great, I approve of your work. Good luck with future tasks!

2022-09-14 04:26 UTC, madmaxWMFU commented
Update your demo!

2022-09-14 04:26 UTC, merged