Html task
kottans/frontend-2022-homeworks pull request #358
Opened 2022-08-29 22:23 UTC by Rybchynskyi

### HTML & CSS Practice
[Demo](https://rybchynskyi.github.io/HTML-CSS-Practice-menu/) |
[Code base](https://github.com/Rybchynskyi/HTML-CSS-Practice-menu)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-29 22:24 UTC, Rybchynskyi commented
Task "HTML & CSS Practice"

2022-09-08 09:51 UTC, HannaSyn requested changes
Good work, please, check your navigation with keyboard after you fix comments below to make sure that it is working properly

2022-09-08 09:51 UTC, HannaSyn commented on submissions/Rybchynskyi/app-Popup/css/style.css
> +body {
Please, check all this file and format it by one style: add 1 empty line after each block, start each rule from new line and remove necessary comments

2022-09-08 09:51 UTC, HannaSyn commented on submissions/Rybchynskyi/app-Popup/css/style.css
> +}
remove empty block please

2022-09-08 09:51 UTC, HannaSyn commented on submissions/Rybchynskyi/app-Popup/index.html
> +    <title>Document</title>
Add name of your app

2022-09-08 09:51 UTC, HannaSyn commented on submissions/Rybchynskyi/app-Popup/index.html
> +        <div class="header__row">
Use `nav>ul>li>a` for list of navigation

2022-09-08 09:51 UTC, HannaSyn commented on submissions/Rybchynskyi/app-Popup/index.html
> +                    <div class="menu__items">
Use `ul>li>a` for list of menu

2022-09-08 09:51 UTC, HannaSyn commented on submissions/Rybchynskyi/app-Popup/index.html
> +                                <div class="grid__second__section">
This is a list too

2022-09-08 09:51 UTC, HannaSyn commented on submissions/Rybchynskyi/app-Popup/index.html
> +                    <img class="header__img__menu" src="img/popup-button.png" alt="menu">
For icons it's better set an empty alt attribute, read more [here](https://accessibility.psu.edu/images/imageshtml/#empty)

2022-09-08 09:51 UTC, HannaSyn commented on submissions/Rybchynskyi/app-Popup/index.html
> +                <label class="check_1">
Please, add `:focus` state for this element

2022-09-08 09:51 UTC, HannaSyn commented on submissions/Rybchynskyi/app-Popup/index.html
> +                            <div class="menu__items__separator">
Please, add :focus state for this element

2022-09-29 14:29 UTC, closed without merging