Memory Pair Game
kottans/frontend-2022-homeworks pull request #361
Opened 2022-08-30 12:00 UTC by hisbvdis

### Memory Pair Game

[Demo](https://hisbvdis.github.io/kottans-frontend/pages/memory-pair-game) |
[Code base](https://github.com/hisbvdis/kottans-frontend/tree/main/pages/memory-pair-game)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-19 12:55 UTC, OleksiyRudenko commented
Up

2022-10-02 17:22 UTC, kasionio requested changes
Good job! Please look at the comments and try improve naming

2022-10-02 17:22 UTC, kasionio commented on submissions/hisbvdis/memory-pair-game/script.js
> +            <img class="card__img" src="img/${option}.png" width="100" height="100" alt="${option}"/>
you can add width and height to css file to make code cleaner

2022-10-02 17:22 UTC, kasionio commented on submissions/hisbvdis/memory-pair-game/script.js
> +    .map((elem) => elem.querySelector(".card__img").alt)
`elem` is `card` here? Please try using clear naming, then your code will be easier to read

2022-10-02 17:22 UTC, kasionio commented on submissions/hisbvdis/memory-pair-game/script.js
> +function changeGameSide() {
let's move to the evil game side :) Please improve the naming a bit. Try to read your code and understand what it does in every step

2022-10-02 17:22 UTC, kasionio commented on submissions/hisbvdis/memory-pair-game/script.js
> +  cardFlippers.forEach((cardInner) => flipCard(cardInner));
![image](https://user-images.githubusercontent.com/21179601/193467149-c6edf7e8-6f77-4201-b619-65b3a129fea0.png)

2022-10-02 17:22 UTC, kasionio commented on submissions/hisbvdis/memory-pair-game/script.js
> +    .map((elem) => elem.querySelector(".card__img").alt)
Using `alt` attribute to compare cards is a bad approach, you can use alt only for describing images, that's it. So, you can compare unique identifiers `id` for example

2022-10-02 17:31 UTC, hisbvdis commented on submissions/hisbvdis/memory-pair-game/css/flipper.css
> +/* ========================================================================== */
Удалил.

Коммит:  ff500c8

2022-10-02 17:31 UTC, hisbvdis commented on submissions/hisbvdis/memory-pair-game/index.html
> +            <!-- <li class="card  flipper">
Удалил.

Коммит: ff500c8

2022-10-02 17:34 UTC, hisbvdis commented on submissions/hisbvdis/memory-pair-game/index.html
> +    <main class="board  flipper">
Разделяю классы двумя пробелами, чтобы легче было различать.
Удалил.

Коммит:  77980d8

2022-10-02 17:35 UTC, hisbvdis commented on submissions/hisbvdis/memory-pair-game/script.js
> +  score = score + 1;
Исправил

Коммит:  372cad9

2022-10-02 17:50 UTC, hisbvdis commented on submissions/hisbvdis/memory-pair-game/script.js
> +  for (
Переделал с помощью метода `sort`

Коммит:  85c9987

2022-10-02 17:53 UTC, hisbvdis commented on submissions/hisbvdis/memory-pair-game/script.js
> +
Мне тоже тяжело определить границы функции.
Но когда внутри функции нет отступов, тяжело отделить действия внутри.

Удалил.
Коммит:  202d2a1

2022-10-02 18:14 UTC, hisbvdis commented on submissions/hisbvdis/memory-pair-game/script.js
> +            <img class="card__img" src="img/${option}.png" width="100" height="100" alt="${option}"/>
Насколько я знаю, HTML-атрибуты `width` и `height` полезны для изображений для того, чтобы браузер ещё до начала загрузки изображения выделял для них пространство.

Например, вот здесь я статью переводил когда-то: https://habr.com/ru/post/524918/

Я сейчас задал изображениям размер 100%, чтобы в случае изменения размера ячеек сетки, изображения занимали всё доступное пространство. А "флипперу" задал `aspecti-ratio`, чтобы он всегда был квадратным

Коммит:  1474bd7

2022-10-02 18:21 UTC, hisbvdis commented on submissions/hisbvdis/memory-pair-game/script.js
> +    .map((elem) => elem.querySelector(".card__img").alt)
> `elem` is `card` here?
Да

> elem is card here? Please try using clear naming, then your code will be easier to read
Понял.
Исправил и постараюсь учесть на будущее.

> Using `alt` attribute to compare cards is a bad approach, you can use alt only for describing images, that's it. So, you can compare unique identifiers `id` for example
Вместо атрибута `alt` использовал значение `src`

Коммит:  76975f9

2022-10-02 18:37 UTC, hisbvdis commented on submissions/hisbvdis/memory-pair-game/script.js
> +function changeGameSide() {
Заменил "игру" на "доску" в названии функции

Коммит:  9026d23

2022-10-02 18:50 UTC, hisbvdis commented on submissions/hisbvdis/memory-pair-game/script.js
> +  cardFlippers.forEach((cardInner) => flipCard(cardInner));
:)))))))
Смешно.
Но слово "flipper" я взял из [этой статьи](https://davidwalsh.name/css-flip).
Насколько я понимаю, значит что-то вроде "переворачивалка".
Не знаю, чем заменить.
Или заменять и не обязательно?

2022-10-22 19:35 UTC, hisbvdis commented
@kasionio , надеюсь, про мой PR не забыли?
Это последний мой непроверенный PR.
Что-то у меня сомнения появляются, пропустили ли меня на 2 этап

2022-11-30 14:35 UTC, closed without merging