Dom
kottans/frontend-2022-homeworks pull request #366
Opened 2022-08-30 20:56 UTC by YarHadi

### DOM

[Demo](https://yarhadi.github.io/dom/) |
[Code base](https://github.com/YarHadi/dom)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-01 18:37 UTC, madmaxWMFU requested changes
Good work. Add some functionality to your code. Create DOM elements. Use event listener. Work with dataset property of elements.

2022-09-01 21:58 UTC, YarHadi commented
Hello, Master. Your comments was resolved.
Please, check again.

2022-09-02 05:00 UTC, madmaxWMFU requested changes

2022-09-02 05:00 UTC, madmaxWMFU commented on submissions/YarHadi/task_js_dom/form.js
> +  <img
Also, read about [desrtuction](https://javascript.info/destructuring-assignment)

2022-09-02 06:46 UTC, YarHadi commented on submissions/YarHadi/task_js_dom/form.js
> +showContent(1, characters);
I did not understand a little, but I did something)) 
Please check.

2022-09-02 06:47 UTC, YarHadi commented
Almost all comments was resolved)
Please check.

2022-09-03 19:47 UTC, madmaxWMFU requested changes

2022-09-03 19:47 UTC, madmaxWMFU commented on submissions/YarHadi/task_js_dom/form.js
> +  showContent(header,img,text);
```suggestion
function initPage(){
  const [{ header, img, text }] = character;
  showContent(header,img,text);
```

2022-09-04 06:36 UTC, YarHadi commented
Good morning.
The work is done.
Please check again.

2022-09-04 06:44 UTC, madmaxWMFU approved these changes
Great, I approve of your work. Good luck with future tasks!

2022-09-04 06:44 UTC, merged

2022-09-04 06:46 UTC, YarHadi commented
Thank you. Have a nice day.