friends-app
kottans/frontend-2022-homeworks pull request #367
Opened 2022-08-30 21:29 UTC by hisbvdis

### friends-app

[Demo](https://hisbvdis.github.io/kottans-frontend/pages/friends-app) |
[Code base](https://github.com/hisbvdis/kottans-frontend/tree/main/pages/friends-app)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-19 13:21 UTC, OleksiyRudenko commented
Up

2022-09-25 19:32 UTC, A-Ostrovnyy requested changes
Good work!

2022-09-25 19:32 UTC, A-Ostrovnyy commented on submissions/hisbvdis/friends-app/js/script.js
> +}
:fire:

2022-09-25 19:32 UTC, A-Ostrovnyy commented on submissions/hisbvdis/friends-app/js/script.js
> +  }
```suggestion
renderUserList(true);

function renderUserList(isFirstRender = false) {
  if (isFirstRender) {
    updateURL();
  }
```

2022-09-27 11:49 UTC, hisbvdis commented on submissions/hisbvdis/friends-app/index.html
> +      <ul class="users__list"  data-user-list></ul>
Обновил.
Коммит:  285197a

2022-09-27 11:52 UTC, hisbvdis commented on submissions/hisbvdis/friends-app/index.html
> +        </label>
Добавил.

Коммит:  26f7cdd

2022-09-27 11:58 UTC, hisbvdis commented on submissions/hisbvdis/friends-app/js/script.js
> +const dataArr = await getUserList().then(data => data);
Да, так действительно понятнее

Коммит:  cb8276a

2022-09-27 12:00 UTC, hisbvdis commented on submissions/hisbvdis/friends-app/js/randomuser.service.js
> +// const baseURL = "../../assets/data.json";
Удалил

Коммит:  f0af8cd

2022-09-27 12:11 UTC, hisbvdis commented on submissions/hisbvdis/friends-app/js/script.js
> +        .reduce((accum, [key, value]) => ({ ...accum, [key]: value }), {});
Обновил

Коммит:  acd90b3

2022-09-27 12:26 UTC, hisbvdis commented on submissions/hisbvdis/friends-app/js/script.js
> +    );
Использовал DocumentFragment

Коммит:  3eeac74

2022-09-27 12:28 UTC, hisbvdis commented on submissions/hisbvdis/friends-app/js/script.js
> +  let newArr = dataArr;
Да, так намного понятнее.

Коммит:  7666d26

2022-09-27 20:45 UTC, A-Ostrovnyy requested changes
Good progress

2022-09-27 20:45 UTC, A-Ostrovnyy commented on submissions/hisbvdis/friends-app/index.html
> +        <select name="sort" id="sort-select" data-sort-select>
Missed `cursor: pointer` :cry:

2022-09-28 13:38 UTC, hisbvdis commented on submissions/hisbvdis/friends-app/js/script.js
> +let searchValue = urlSearchParams.get("search") || "";
Поправил.

Коммит:  9d03382

2022-09-28 13:42 UTC, hisbvdis commented on submissions/hisbvdis/friends-app/index.html
> +        <select name="sort" id="sort-select" data-sort-select>
Не был уверен, нужно ли в выпадающем меню ставить ставить такой курсор.
Поставил

Коммит:   0df9181

2022-10-01 09:06 UTC, A-Ostrovnyy commented
@hisbvdis did you update your demo?)

2022-10-01 09:32 UTC, hisbvdis commented
@A-Ostrovnyy , только что обновил.

2022-10-04 18:31 UTC, A-Ostrovnyy requested changes
One last issue)

2022-10-04 18:31 UTC, A-Ostrovnyy commented on submissions/hisbvdis/friends-app/js/script.js
> +})
```suggestion
const filtersForm = document.querySelector('.filters');
filtersForm.addEventListener("change", ({target}) => {
const {name, value} = target;
 if (!['sort', 'gender'].includes(name))) {
     return
 }
  urlSearchParams.set(name, value);
  renderUserList();
});
```

2022-10-04 18:31 UTC, A-Ostrovnyy commented on submissions/hisbvdis/friends-app/js/script.js
> +})
Single eventListener for form.

2022-10-04 18:42 UTC, hisbvdis commented on submissions/hisbvdis/friends-app/js/script.js
> +})
@A-Ostrovnyy , была лишняя скобка.
Удалил.

Коммит:  305a051

P.S. Надеюсь, я тоже научусь писать такой хороший код

2022-10-04 18:46 UTC, hisbvdis commented
Обновил демо

2022-10-04 19:34 UTC, A-Ostrovnyy approved these changes
Congratulations.
Well done!

2022-10-04 19:35 UTC, merged