Complete task DOM API
kottans/frontend-2022-homeworks pull request #370
Opened 2022-08-31 08:13 UTC by deveLabR

### DOM API

[Demo](https://develabr.github.io/dom-js/) |
[Code base](https://github.com/deveLabR/dom-js)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-31 16:06 UTC, deveLabR commented
I finished the self-check. And I hope it's okay)

2022-09-01 18:30 UTC, madmaxWMFU requested changes
Good work. See some comments below.

2022-09-01 18:30 UTC, madmaxWMFU commented on submissions/develabr/dom-js/app.js
> +  btn.addEventListener('click', function () {
Read about [event delegation](https://javascript.info/event-delegation)

2022-09-01 18:30 UTC, madmaxWMFU commented on submissions/develabr/dom-js/app.js
> +		<img class="emblem" src="${item.emblem}" alt="Герб ${item.name}" />
Read about [destruction](https://javascript.info/destructuring-assignment)

2022-09-04 03:44 UTC, madmaxWMFU requested changes

2022-09-04 03:44 UTC, madmaxWMFU commented on submissions/develabr/dom-js/app.js
> +let [kyiv, lviv, mykolaiv, odesa, ternopil, kharkiv, kherson, chernivtsi] =
Must be const. To get the first element use: `const [ kyiv ] = cities;`

2022-09-04 03:44 UTC, madmaxWMFU commented on submissions/develabr/dom-js/app.js
> +  if (target && target.classList.contains('navbar-link')) {
If you read about destruction, use it.
```javascript
listBtn.onclick = function ({ target }) {
  if (target.classList.contains('navbar-link')) {
```

2022-09-04 03:44 UTC, madmaxWMFU commented on submissions/develabr/dom-js/app.js
>  const addContent = (item) => {
```
const addContent = (city) => {
 const {sourse, founded, population, ........ } = city;`

2022-09-07 08:15 UTC, madmaxWMFU approved these changes
Great, I approve of your work. Good luck with future tasks!

2022-09-07 08:15 UTC, merged