Hooli-style Popup
kottans/frontend-2022-homeworks pull request #38
Opened 2022-07-30 15:07 UTC by natalia-artsiukh

### Hooli-style Popup

[Demo](https://natalia-artsiukh.github.io/kottans_homework1/) |
[Code base](https://github.com/natalia-artsiukh/kottans_homework1.git)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-07-30 16:57 UTC, kasionio commented
Great job! Nice formatting, which is pretty easy to read, that's cool. The menu is also looking good 

Seems there is still some room for UI and accessibility improvements.
1. I can't reach the popup menu using just a keyboard. 
2. Hover effect "cursor: pointer" should appear only on clickable elements(buttons, links, etc.), not on the whole container.
3. "More" button should take 100% width of the popup container by design, seems more containers will be needed in code for this :)
4. Please take a look at the screenshot. Seems that the container needs to be better centered and also should have just one padding, the second looks redundant.
5. To prevent jumping on elements if you want to add some padding on hover can be done like so:
`
.element {
padding: 1px solid transparent;
}
.element: hover {
padding: 1px solid SOME_COLOR;
} 
`

![image](https://user-images.githubusercontent.com/21179601/181933482-3ea5a3ac-4eff-4e3c-bf26-17a7daac535c.png)

Don't hesitate to ask if something is not clear ;)

2022-07-31 17:44 UTC, natalia-artsiukh commented
I made the necessary changes to my files. please check)
I couldn't make a re-request review because I don't have reviewers

2022-07-31 18:42 UTC, A-Ostrovnyy requested changes
Good work!
See my comments below.

2022-07-31 18:42 UTC, A-Ostrovnyy commented on submissions/natalia-artsiukh/html-css-popup/index.html
> +                        <a href="#" class="popup-item">
Fix focus outline
![image](https://user-images.githubusercontent.com/16196199/182040454-d7ecd452-6efb-4f6f-b313-df80073c2feb.png)

2022-07-31 18:42 UTC, A-Ostrovnyy commented on submissions/natalia-artsiukh/html-css-popup/index.html
> +            <div class="nav-position">
For menu items especially if you have nested navigation use an unordered list.

2022-07-31 18:42 UTC, A-Ostrovnyy commented on submissions/natalia-artsiukh/html-css-popup/index.html
> +                            <img src="./img/calendar.png" alt="calendar" class="popup-img">
Read [this article](https://htmlacademy.ru/blog/articles/alt-text) about `alt` attribute. Sorry for rusisan but it's a good article.

2022-07-31 18:42 UTC, A-Ostrovnyy commented on submissions/natalia-artsiukh/html-css-popup/style.css
> +@media (width: 1920px) {
Don't forget about mobile view 
![image](https://user-images.githubusercontent.com/16196199/182040662-ef1ac665-e2c8-47ce-947a-8049933aac5d.png)

2022-07-31 19:22 UTC, kasionio requested changes
Great job! Last steps left

2022-07-31 19:22 UTC, kasionio commented on submissions/natalia-artsiukh/html-css-popup/style.css
> +    display: none;
two `display` is too much for one class :)

2022-07-31 19:22 UTC, kasionio commented on submissions/natalia-artsiukh/html-css-popup/style.css
> +    background-color: rgba(110, 120, 116, 0.598);
Why do you need so much accuracy on alpha channel value?

2022-07-31 19:22 UTC, kasionio commented on submissions/natalia-artsiukh/html-css-popup/style.css
> +    background-image: url(./img/ocean.jpg);
you can use `background` shorthand here

2022-07-31 19:22 UTC, kasionio commented on submissions/natalia-artsiukh/html-css-popup/style.css
> +    color: blanchedalmond;
Better to use HEX or RGB model

2022-07-31 19:22 UTC, kasionio commented on submissions/natalia-artsiukh/html-css-popup/style.css
> +    font-size: 18px;
To use a responsive design, even when a page will be scaled you can use `em` or `rem`

2022-08-01 14:01 UTC, A-Ostrovnyy approved these changes
Looks good to me.
@kasionio what's your input about it?

2022-08-01 14:34 UTC, kasionio commented
@A-Ostrovnyy, agree. @natalia-artsiukh, congrats 🎉

2022-08-01 14:34 UTC, kasionio approved these changes

2022-08-01 14:39 UTC, merged