Html css popup
kottans/frontend-2022-homeworks pull request #382
Opened 2022-08-31 22:10 UTC by d-pozniak

### HTML-CSS-Popup

[Demo](https://d-pozniak.github.io/html-css-popup/) |
[Code base](https://github.com/d-pozniak/html-css-popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-01 18:23 UTC, d-pozniak commented
I believe I`ve completed self-checks and fixed code accordingly.

2022-09-15 19:14 UTC, A-Ostrovnyy requested changes
Awesome work!

2022-09-15 19:14 UTC, A-Ostrovnyy commented on submissions/d-pozniak/html-css-popup/index.html
> +<div class="header">
div for page header? 
![image](https://user-images.githubusercontent.com/16196199/190488859-81b506ea-1f02-4ccf-8945-73221db8c43c.png)

[header](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header)

2022-09-15 19:14 UTC, A-Ostrovnyy commented on submissions/d-pozniak/html-css-popup/styles.css
> +    src: url(../fonts/AnticSlab-Regular.ttf);
Avoid using `.ttf` fonts for web, use `.woff2` + `.woff` instead.

2022-09-15 19:14 UTC, A-Ostrovnyy commented on submissions/d-pozniak/html-css-popup/styles.css
> +    font-family: Antic, Arial, sans-serif;
If you use this font for the whole page set this font for `html` or `body` elements.

2022-09-15 19:14 UTC, A-Ostrovnyy commented on submissions/d-pozniak/html-css-popup/index.html
> +            <div class="logo-img">
The logo should be a link and lead us to the home page.

2022-09-15 19:19 UTC, d-pozniak commented
Thanks for your review, I`ll try to resolve issues as soon as possible.

2022-09-16 16:20 UTC, A-Ostrovnyy requested changes
Good progress!
One last issue)

2022-09-16 16:20 UTC, A-Ostrovnyy commented on submissions/d-pozniak/html-css-popup/styles.css
> +    url(../fonts/AnticSlab-Regular.woff2);
Use `.woff2` before `.woff`.

2022-09-17 20:49 UTC, d-pozniak commented on submissions/d-pozniak/html-css-popup/styles.css
> +    url(../fonts/AnticSlab-Regular.woff2);
done :)

2022-09-18 13:46 UTC, A-Ostrovnyy approved these changes
Well done!

2022-09-18 13:46 UTC, merged