Popup task completed
kottans/frontend-2022-homeworks pull request #383
Opened 2022-09-01 09:13 UTC by marynatovtyn

### hooli-popup

[Demo](https://marynatovtyn.github.io/hooli-style-popup/) |
[Code base](https://github.com/marynatovtyn/hooli-style-popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-03 11:35 UTC, marynatovtyn commented
Completed self-checks, ready for review

2022-09-15 19:48 UTC, A-Ostrovnyy requested changes
Awesome work!

2022-09-15 19:48 UTC, A-Ostrovnyy commented on submissions/marynatovtyn/hooli-style-popup/style.css
> +    /* display: grid; */
Avoid commented code in your work.

2022-09-15 19:48 UTC, A-Ostrovnyy commented on submissions/marynatovtyn/hooli-style-popup/style.css
> +::-webkit-scrollbar {
This is an invalid selector: you can't set pseudoelement from an empty selector.

2022-09-15 19:48 UTC, A-Ostrovnyy commented on submissions/marynatovtyn/hooli-style-popup/style.css
> +    background-color: #EEE2DC;
You can add this style to the `body` and remove this element from markup)

2022-09-15 19:48 UTC, A-Ostrovnyy commented on submissions/marynatovtyn/hooli-style-popup/style.css
> +    outline: 0;
better use `outline: none`

2022-09-15 19:48 UTC, A-Ostrovnyy commented on submissions/marynatovtyn/hooli-style-popup/style.css
> +    position: relative;
Please fix indentation

2022-09-15 19:48 UTC, A-Ostrovnyy commented on submissions/marynatovtyn/hooli-style-popup/index.html
> +              </a>
Add styles on hover and focus state.

2022-09-18 13:48 UTC, marynatovtyn commented
Thanks for your review! I added requested changes

2022-09-18 13:58 UTC, A-Ostrovnyy approved these changes

2022-09-18 13:58 UTC, A-Ostrovnyy commented on submissions/marynatovtyn/hooli-style-popup/index.html
> +      <main class="main"></main>
Avoid unused markup in your work)

2022-09-18 13:58 UTC, merged