Dom task
kottans/frontend-2022-homeworks pull request #389
Opened 2022-09-01 12:32 UTC by nvklap

### Dom api task

[Demo](https://nvklap.github.io/dom-prjct/) |
[Code base](https://github.com/nvklap/dom-prjct)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-02 09:31 UTC, nvklap commented
I've completed self-checks.

2022-09-13 16:39 UTC, lysenko-sergey-developer commented
Awesome work 🚀

2022-09-13 16:40 UTC, lysenko-sergey-developer requested changes

2022-09-13 16:44 UTC, lysenko-sergey-developer commented
UI/UX Improvement:
Content reflow while image loading
[The Complete Guide to Lazy Loading Images | CSS-Tricks](https://css-tricks.com/the-complete-guide-to-lazy-loading-images/#aa-tip-3-avoid-content-reflow)
- change `max-width` to `width` on img
- add `aspect-ratio` with a value which your image has
![Screenshot 2022-09-13 at 19 41 58](https://user-images.githubusercontent.com/16616791/189959014-b6522a88-bb2e-4d3e-91cc-c7008348f1c2.png)

2022-09-14 13:44 UTC, nvklap commented
Thanks a lot for review and useful advise! I've fixed my code.

2022-09-14 20:28 UTC, lysenko-sergey-developer requested changes

2022-09-14 20:28 UTC, lysenko-sergey-developer commented on submissions/nvklap/dom/js/app.js
> +const navList = document.querySelector('.series-list');
Move `navList` to other selectors.

2022-09-14 20:28 UTC, lysenko-sergey-developer commented on submissions/nvklap/dom/js/app.js
> +function showContent({ target }) {
`addNavigation`, `createContentList` and `showContent` do too much stuff. Try to decompose them into smaller functions.

2022-09-15 17:10 UTC, lysenko-sergey-developer commented
LGTM! 😃

2022-09-15 17:16 UTC, merged