add files
kottans/frontend-2022-homeworks pull request #396
Opened 2022-09-02 06:35 UTC by VasylRosokha

### Hooli-style Popup

[Demo](https://vasylrosokha.github.io/Hooli-style-Popup/) |
[Code base](https://github.com/VasylRosokha/Hooli-style-Popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-03 10:15 UTC, VasylRosokha commented
I  have completed self-checks

2022-09-16 18:12 UTC, A-Ostrovnyy requested changes
Good work!

2022-09-16 18:12 UTC, A-Ostrovnyy commented on submissions/VasylRosokha/Popup/index.html
> +    <header class="header">
Add a mobile version of your popup.
![image](https://user-images.githubusercontent.com/16196199/190704559-64e64ee6-6782-486b-8390-ce01a5732eed.png)

2022-09-16 18:12 UTC, A-Ostrovnyy commented on submissions/VasylRosokha/Popup/index.html
> +                            <label for="popup-more" class="more-label">More</label>
Logically when the second part of the popup is open this button should be hidden.

2022-09-19 15:52 UTC, A-Ostrovnyy requested changes
One last issue.

2022-09-19 15:52 UTC, A-Ostrovnyy commented on submissions/VasylRosokha/Popup/index.html
> +                            <div class="more-menu">
Avoid horizontal scroll except if you need it
![image](https://user-images.githubusercontent.com/16196199/191059693-d43093ab-9644-4592-b11c-a7f4cd619bd3.png)

2022-09-19 16:10 UTC, VasylRosokha commented
> One last issue.

What I need to do?

2022-09-19 17:11 UTC, A-Ostrovnyy commented
> > One last issue.
> 
> What I need to do?

Remove horizontal scroll when the second part is open

2022-09-20 18:31 UTC, A-Ostrovnyy commented on submissions/VasylRosokha/Popup/css/style.css
>  }
Fo the future put an empty line at the end of every file. [Reason](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline?noredirect=1&lq=1). Tune your code editor's settings so it does this for you.

2022-09-20 18:32 UTC, A-Ostrovnyy approved these changes
Well done!

2022-09-20 18:32 UTC, merged