A tiny world js task
kottans/frontend-2022-homeworks pull request #402
Opened 2022-09-02 11:01 UTC by franchukv

### A Tiny JS World

[Demo](https://franchukv.github.io/a-tiny-JS-world/) | [Code base](https://github.com/franchukv/a-tiny-JS-world)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-02 19:13 UTC, franchukv commented
Self-check done.

2022-09-07 14:28 UTC, OleksiyRudenko requested changes
@franchukv good job!
Also a few of improvements are needed.

2022-09-07 14:28 UTC, OleksiyRudenko commented on submissions/franchukv/a-tiny-js-world/index.js
> +   return propValuesArr.join('; ');
CLassic use case for `Array#map`. You won't also need interim variables.

2022-09-07 14:28 UTC, OleksiyRudenko commented on submissions/franchukv/a-tiny-js-world/index.js
> +   const propNames = Object.getOwnPropertyNames(obj);
> - [ ] `Object` methods like `keys`, `values`, `entries` shouldn't be used when a particular order is required as these do not guarantee any particular order of keys/values. Same refers to `for...of` and `for...in` when applied to objects.

The key message here ^^ is **as these do not guarantee any particular order of keys/values**. Same refers to any other `Object` methods. Please use approach when order is controllable and manageable.

2022-09-07 14:28 UTC, OleksiyRudenko commented on submissions/franchukv/a-tiny-js-world/index.js
> +const objToString = (obj) => {
> - Give variables and functions meaningful names. Avoid generic names like `item`, `element`, `key`, `object`, `array` or their variations. Exception: helper functions that are specifically and intentionally designed to be multipurpose.

2022-09-07 14:28 UTC, OleksiyRudenko commented on submissions/franchukv/a-tiny-js-world/index.js
> +function greetings(arr, func) {
> - Give variables and functions meaningful names. Avoid generic names like `item`, `element`, `key`, `object`, `array` or their variations. Exception: helper functions that are specifically and intentionally designed to be multipurpose.

2022-09-07 18:36 UTC, OleksiyRudenko requested changes
@franchukv still need to master `Array#map`

2022-09-07 18:36 UTC, OleksiyRudenko commented on submissions/franchukv/a-tiny-js-world/index.js
> +   return temporaryArray.join('; ');
rows 68-74 are classic use case for `Array#map`. Learn it. You will often use it.

2022-09-07 19:47 UTC, OleksiyRudenko approved these changes
@franchukv well done!

2022-09-07 19:47 UTC, merged

2022-09-07 19:50 UTC, franchukv commented
> @franchukv well done!

Thanks for ur review)