js-dom task
kottans/frontend-2022-homeworks pull request #408
Opened 2022-09-03 06:58 UTC by andreymashko7

### task_js_dom

[Demo](https://andreymashko7.github.io/side-menu/) |
[Code base](https://github.com/andreymashko7/side-menu)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-07 19:15 UTC, andreymashko7 commented
Please rewiew

2022-09-08 09:26 UTC, madmaxWMFU requested changes
Good work! See some comments below.

2022-09-08 09:26 UTC, madmaxWMFU commented on submissions/AndriyM/js-dom/index.js
> +sideBarContainer.addEventListener("click", onsideBarElementClick)
Format your code. It is helpful to use [Prettier](https://prettier.io/).

2022-09-08 09:26 UTC, madmaxWMFU commented on submissions/AndriyM/js-dom/index.js
> +    let currentActivetLink = target.dataset.id
Must be `const`

2022-09-11 07:12 UTC, andreymashko7 commented
All ready, please check

2022-09-11 11:05 UTC, madmaxWMFU commented
You always forget to put `;`.
Use [prettier](https://prettier.io/) to pretty format your code.

2022-09-11 11:06 UTC, madmaxWMFU approved these changes
Great, I approve of your work. Good luck with future tasks!

2022-09-11 11:06 UTC, merged