Frogger-game
kottans/frontend-2022-homeworks pull request #419
Opened 2022-09-03 18:21 UTC by ASTkach

### Frogger-game

[Demo](https://astkach.github.io/frontend-nanodegree-arcade-game/) |
[Code base](https://github.com/ASTkach/frontend-nanodegree-arcade-game/tree/frogger-game)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-04 14:32 UTC, ASTkach commented
Hope I did a good self-check.

2022-09-19 13:12 UTC, OleksiyRudenko requested changes
@ASTkach very well done!
However one important fix is yet required.

2022-09-19 13:12 UTC, OleksiyRudenko commented on submissions/ASTkach/frogger-game/app.js
> +            player.y + CELL_HEIGHT - 10 < this.y
Bot's requirements re OOP addresses exactly this situation.
Please double check and fix as appropriate.

2022-09-20 11:05 UTC, OleksiyRudenko commented
Up

2022-12-10 08:40 UTC, closed without merging