created folder and uploaded files
kottans/frontend-2022-homeworks pull request #426
Opened 2022-09-04 11:52 UTC by vl-shevchenko

###dom-api-task

[Demo](https://vl-shevchenko.github.io/dom/) |
[Code base](https://github.com/vl-shevchenko/dom)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-04 20:48 UTC, vl-shevchenko commented
Hey!
My code has been validated.
I took into account all the tips from common mistakes when writing code.

2022-09-18 19:38 UTC, lysenko-sergey-developer commented
@vl-shevchenko Nice work! 💯

2022-09-18 19:39 UTC, lysenko-sergey-developer requested changes

2022-09-18 19:39 UTC, lysenko-sergey-developer commented on submissions/vl-shevchenko/dom-api-task/script.js
> +        color: 'url(images/kyiv5-904w.jpg)',
Colour is a link to image? Should have another name. And remove `url`.

2022-09-18 19:39 UTC, lysenko-sergey-developer commented on submissions/vl-shevchenko/dom-api-task/script.js
> +let defaultContent = document.querySelector('.container');
If you do not change a variable(with `=` operator) always use const.

2022-09-18 19:39 UTC, lysenko-sergey-developer commented on submissions/vl-shevchenko/dom-api-task/script.js
> +defaultContent.innerHTML = `<p class='info'>${city[0].info}</p>`;
Should be in function for setting default content.

2022-09-18 19:39 UTC, lysenko-sergey-developer commented on submissions/vl-shevchenko/dom-api-task/script.js
> +    document.querySelector('.nav__bloc').innerHTML = `<ul class='container-list'></ul>`;
`.nav__block` functional and `city` should be in different functions.

2022-09-18 19:39 UTC, lysenko-sergey-developer commented on submissions/vl-shevchenko/dom-api-task/script.js
> +        document.querySelector('.container-list').appendChild(nameCity);
You already have var for `.container-list` on line [53](https://github.com/kottans/frontend-2022-homeworks/pull/426/files#diff-67c3e77f177ce6616994c08bfed32b00d13bc21085c15f08c825ebb6e7cfb2eeR53). Why you reselect it?

2022-09-18 19:39 UTC, lysenko-sergey-developer commented on submissions/vl-shevchenko/dom-api-task/style.css
> +
Remove redundant empty lines.

2022-09-18 19:39 UTC, lysenko-sergey-developer commented on submissions/vl-shevchenko/dom-api-task/script.js
> +    let color = '';
It is not a color.

2022-09-18 19:39 UTC, lysenko-sergey-developer commented on submissions/vl-shevchenko/dom-api-task/script.js
> +    document.body.style.backgroundImage = color;
Remove temp `let` vars, move this logic to `if` at line [62](https://github.com/kottans/frontend-2022-homeworks/pull/426/files#diff-67c3e77f177ce6616994c08bfed32b00d13bc21085c15f08c825ebb6e7cfb2eeR53) and move `if` body to function.

2022-09-18 19:39 UTC, lysenko-sergey-developer commented on submissions/vl-shevchenko/dom-api-task/script.js
> +    e.preventDefault();
Why do we need here `preventDefault`?

2022-09-18 19:39 UTC, lysenko-sergey-developer commented on submissions/vl-shevchenko/dom-api-task/style.css
> +    background: rgba(255, 237, 224, 0.56);
Move colors to css3 vars.

2022-09-18 19:42 UTC, lysenko-sergey-developer commented
UI/UX Improvements:
Research more about [Glassmorphism](https://www.freecodecamp.org/news/glassmorphism-design-effect-with-html-css/). Try to make your texts more readable.

2022-10-09 21:26 UTC, closed without merging