A tiny js world
kottans/frontend-2022-homeworks pull request #449
Opened 2022-09-05 17:51 UTC by vl-shevchenko

### A tiny js world

[Demo](https://vl-shevchenko.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/vl-shevchenko/a-tiny-JS-world)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-05 17:57 UTC, vl-shevchenko commented
Hey!
I took into account all the tips from common mistakes when writing code.

2022-09-06 10:34 UTC, vl-shevchenko commented
Hi!
In last commit I changed the method.

2022-09-07 14:43 UTC, OleksiyRudenko requested changes
@vl-shevchenko good job. Although requires improvements.

2022-09-07 14:43 UTC, OleksiyRudenko commented on submissions/vl-shevchenko/js-world/index.js
> +let arr = [dog, cat, woman, man];
From the checklist:
> - Give variables and functions meaningful names. Avoid generic names like `item`, `element`, `key`, `object`, `array` or their variations. Exception: helper functions that are specifically and intentionally designed to be multipurpose.

2022-09-07 14:43 UTC, OleksiyRudenko commented on submissions/vl-shevchenko/js-world/index.js
> +   print(`${species}; <strong>${name}</strong>; ${gender}; ${legs}; ${hands}; <em>${saying}</em>`);
From the checklist:
> - [ ] Code is [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), which means that whenever you see a pattern in your code those should be eliminated as much as possible. Examples:
>    - `print(dog); print(cat); etc ... ` should be refactored employing `Array.forEach` as the least
>    - `` `${obj.legs}; ${obj.name}; etc...` `` (yes, strings are also code) must be refactored employing appropriate `Array` methods

2022-09-07 18:18 UTC, vl-shevchenko commented
@OleksiyRudenko, I corrected all comments

2022-09-07 18:22 UTC, OleksiyRudenko approved these changes
@vl-shevchenko great job!

2022-09-07 18:23 UTC, OleksiyRudenko commented
BTW there is a way to keep extra content even with current `.map` approach.
See [this](https://github.com/kottans/frontend-2022-homeworks/pull/391/files) for inspiration.

2022-09-07 18:23 UTC, merged