Document Object Model
kottans/frontend-2022-homeworks pull request #459
Opened 2022-09-06 15:09 UTC by SableVector

### Document Object Model

[demo](https://sablevector.github.io/myPortfolio/kottansFrontend/document_object_model/)

[Code base](https://github.com/SableVector/myPortfolio/tree/main/kottansFrontend/document_object_model)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-06 18:14 UTC, SableVector commented
I’ve completed the self-assessment and corrected the code accordingly. :)

2022-09-20 07:57 UTC, madmaxWMFU requested changes
Good work! See some comments below.

2022-09-20 07:57 UTC, madmaxWMFU commented on submissions/SableVector/main.js
> +        });
Try to use the method `reduce ` of the _Array_

2022-09-20 07:57 UTC, madmaxWMFU commented on submissions/SableVector/main.js
> +        }
```suggestion
            const selectedBook = books.find(({title}) => title === target.textContent);
            createBook(selectedBook);
        }
```

2022-09-20 07:57 UTC, madmaxWMFU commented on submissions/SableVector/main.js
> +        if (target && target.closest('.sidebar-list-item__button')) {
```suggestion
        if (target.closest('.sidebar-list-item__button')) {
```

2022-09-20 07:57 UTC, madmaxWMFU commented on submissions/SableVector/main.js
> +    }
```suggestion
    const [initialBook] = books;
    if (pageContainer.querySelector('.book')) {
        removeBook();
    } 
    createBook(initialBook);
```

2022-10-11 09:55 UTC, closed without merging