update tiny js world with classes
kottans/frontend-2022-homeworks pull request #464
Opened 2022-09-07 10:10 UTC by Yuliiadd

### OOP Exercise

[Demo](https://yuliiadd.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/Yuliiadd/a-tiny-JS-world)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-24 07:53 UTC, Yuliiadd commented
@OleksiyRudenko
Hi! I did self-checks. Please, review.

2022-09-26 14:23 UTC, OleksiyRudenko requested changes
@Yuliiadd improvements needed

2022-09-26 14:23 UTC, OleksiyRudenko commented on submissions/YuliiaDyka/oop-exercise/index.js
> +   }
Requirements re `Object` methods are still valid.

Also read about (and use) methods overloading/overriding and extended `super` API (calling inherited methods versions). You may want to revisit JS OOP educational materials.

2022-09-26 14:23 UTC, OleksiyRudenko commented on submissions/YuliiaDyka/oop-exercise/index.js
> +      this.legs = 4;
Why `name` is defined in the base class and `legs` in all classes that have legs?

2022-09-28 18:48 UTC, OleksiyRudenko commented
A side note: looks like a PR (code submission) for https://github.com/kottans/frontend/blob/master/tasks/js-pre-oop.md is missing.

2022-09-29 07:40 UTC, Yuliiadd commented
@OleksiyRudenko could you give me more hints?)
In first version i used this constructions in parent class method and this worked for all child classes without extending the parent method in them: 

> Object.getOwnPropertyNames(this).map(prop => this[prop]).join('; ')

But after your first comment i thought that i have to change this method extending in child classes.  I did not fully understand your comment, but I changed this method and it turned out that I did not meet the requirements((( I'm confused((  Could you help me to understand whats wrong with this construction? Why i can not use it like in first version?

I can rewrite this method like this, but i don't know this resolve my problem? I will not extend parent method in child class this way: 
```
      let properties = [];
      for(let prop in this){
         properties.push(this[prop]);
      }
      return properties.join('; ');
   }
```

2022-09-29 21:28 UTC, OleksiyRudenko commented
`Object.*` methods as well as `for..in` and `for..of` are OK when a particular order of keys/values is not important.
We shouldn't rely on order of class properties definition nor should we change the order of definition when we need to change order of their usage (output in our case).

You are on the right path:

> `` `${this.species}; ${this.name}; ${this.gender}; ${this.saying}; ${this.legs}` ``

This is a classic use case for `Array.join`. You also do not need to revert to a good ol' `['name', 'gender'].map(...)`
What we want to eliminate here is repetition of `"; "`. Also if I am tasked to add yet another class property and add it to the output I would prefer to add it twice (in constructor and in output method) without any curly braces etc. I simply can forget to add a space between two properties.

Any valid expression can be an element of an array. Consider the following example:
```
[
  "strings. we already know they are good",
  somePoorlyNamedVariable,
  this.someProperty,
  doSomething(), // a value returned by function will become an array's element
  doSomething, // a function per se; we can call it later
  [], // a nested array
]
```

Your case is simpler then the one above. Hope this helps.

2022-09-30 08:15 UTC, Yuliiadd commented
@OleksiyRudenko updated classes methods. 
I hope I understood everything correctly)
Please, re-review)

2022-09-30 08:54 UTC, OleksiyRudenko approved these changes
@Yuliiadd great job!

2022-09-30 08:54 UTC, OleksiyRudenko commented on submissions/YuliiaDyka/oop-exercise/index.js
> +};
You may see, how this class breaks OOP, DRY etc
Not your fault.
Here is the learning: OOP is not appropriate for hybrids, non strictly hierarchical relations in the system.
Read about compostion vs inheritance to recognize situations where either is more appropriate.

2022-09-30 08:54 UTC, merged