html-css-popup
kottans/frontend-2022-homeworks pull request #48
Opened 2022-08-02 08:45 UTC by KonstantinOkhorzin

### HTML і CSS практика: Hooli-style Popup

[Demo](https://konstantinokhorzin.github.io/popup-html-css/) |
[Code base](https://github.com/KonstantinOkhorzin/popup-html-css)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-02 10:04 UTC, HannaSyn requested changes
Good work! See some comments below =)

2022-08-02 10:04 UTC, HannaSyn commented on submissions/KostiantynOkhorzin/html-css-popup/index.html
> +                            <input class="popap__input-more" id="popap__more" type="checkbox">
You need move this `input` because when you navigate with `tab`, focus should be at icons first, and on `More` after icons.

2022-08-03 09:57 UTC, KonstantinOkhorzin commented
I fixed all. Please, check the changes.

2022-08-04 13:13 UTC, HannaSyn commented
Great work! Almost done
When I navigate with tab, I can see "hidden" icons without click on `More` button, but expected, that only click on the button should show them.

2022-08-05 09:14 UTC, merged