Complete Frogger Game
kottans/frontend-2022-homeworks pull request #484
Opened 2022-09-08 14:25 UTC by deveLabR

### Object-Oriented JavaScript

[Demo](https://develabr.github.io/frontend-nanodegree-arcade-game/) |
[Code base](https://github.com/deveLabR/frontend-nanodegree-arcade-game)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-10 10:28 UTC, deveLabR commented
Self-check done.

2022-09-20 16:42 UTC, OleksiyRudenko requested changes
@deveLabR more than 1 requirements from those posted/linked by bot are not met.

Please copy/paste the requirements, go through them thoroughly, mark those that are met by the code, ask questions here and/or Students' chat if anything is not clear, fix code accordingly.

2022-09-20 16:42 UTC, OleksiyRudenko commented on submissions/develabr/frogger/app.js
> +  }
Requirements posted/linked by bot address two issues with method `update` specifically.
Please identify those, copy/paste them as a comment in this PR and fix code accrodingly.

2022-09-21 13:46 UTC, deveLabR commented
If I understood correctly, I need to make corrections according to the following points:

- All numbers like block dimensions, initial locations are defined as constants.
- There are core constants and derived (calculated) constants (e.g. const FIELD_WIDTH = BLOCK_WIDTH * BLOCKS_NUMBER;).
- Separation of Concerns principle is followed (e.g. update method only updates character coordinates and doesn't contain any inline code to check e.g. collisions; calling other methods from update is legitimate).

Did I miss something?

2022-09-21 14:42 UTC, deveLabR commented
I hope that I understood what is required of me)) now I will try to fix everything

2022-09-26 10:19 UTC, OleksiyRudenko approved these changes
@deveLabR great job!

2022-09-26 10:19 UTC, merged