task_js_oop ( frogger)
kottans/frontend-2022-homeworks pull request #512
Opened 2022-09-11 07:05 UTC by andreymashko7

### frogger-game

[Demo](https://andreymashko7.github.io/frontend-nanodegree-arcade-game/) |
[Code base](https://github.com/andreymashko7/frontend-nanodegree-arcade-game)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-17 07:30 UTC, andreymashko7 commented
self-check is done

2022-09-26 12:41 UTC, OleksiyRudenko requested changes
@andreymashko7 very good job!
A couple of improvements and we're done

2022-09-26 12:41 UTC, OleksiyRudenko commented on submissions/AndriyM/task_js_oop/app.js
> +        player.reset();
See items 4.iii and 4.iv of the requirements.

2022-09-26 12:41 UTC, OleksiyRudenko commented on submissions/AndriyM/task_js_oop/app.js
> +    START_POSITION_Y: [60, 145, 228],
You are tasked to add three more rows for enemies.
Optimize this so it refers to something human-comprehensible (rows) and pixel calculations are done by a computer.

2022-09-26 12:41 UTC, OleksiyRudenko commented on submissions/AndriyM/task_js_oop/app.js
> +            player.reset();
4.iii

2022-09-26 19:43 UTC, andreymashko7 commented on submissions/AndriyM/task_js_oop/app.js
> +            player.reset();
Please, review again

2022-09-26 19:44 UTC, andreymashko7 commented
Please, review again

2022-09-26 20:49 UTC, OleksiyRudenko approved these changes
@andreymashko7 well done!

2022-09-26 20:49 UTC, OleksiyRudenko commented on submissions/AndriyM/task_js_oop/app.js
> +		this.player.reset();
It was good to have a setTimeout. You could keep both setTimeout and meet the requirement.
It was an opportunity to learn through questions.
There is still one. Ask in Students' chat, you will learn one fundamental thing about asynchronous code and use case for async operations in similar situations..

2022-09-26 20:49 UTC, merged