Add frogger game task
kottans/frontend-2022-homeworks pull request #522
Opened 2022-09-12 02:12 UTC by AriadnaKravchuk

### Classic Frogger Game

[Demo](https://ariadnakravchuk.github.io/frontend-nanodegree-arcade-game) |
[Code base](https://github.com/AriadnaKravchuk/frontend-nanodegree-arcade-game)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-13 21:01 UTC, AriadnaKravchuk commented
I completed self-checks

2022-09-26 12:29 UTC, OleksiyRudenko requested changes
@AriadnaKravchuk very well done!
We could skip minor naming issues, but one thing with objects behaviour scoping is important.

2022-09-26 12:29 UTC, OleksiyRudenko commented on submissions/AriadnaKravchuk/frogger-game/app.js
> +function changeChar(player) {
Avoid abbreviations. We write variable/function names once, then IDE helps to autcomplete.
Does `Char` mean `character`, `charcoal`, `Charizard`? (a rhetoric question)

2022-09-26 12:29 UTC, OleksiyRudenko commented on submissions/AriadnaKravchuk/frogger-game/app.js
> +Enemy.prototype.collision = function () {
By convention, function names should start with a verb.

2022-09-26 12:29 UTC, OleksiyRudenko commented on submissions/AriadnaKravchuk/frogger-game/app.js
> +function checkRock(player, allRocks) {
Why this is not a class method?
Or why `collision` is a part of `Enemy` class?

2022-09-26 15:45 UTC, AriadnaKravchuk commented
> @AriadnaKravchuk very well done! We could skip minor naming issues, but one thing with objects behaviour scoping is important.

I changed functions names and made collision checking like player methods.

2022-09-26 16:09 UTC, OleksiyRudenko approved these changes
@AriadnaKravchuk great job!

2022-09-26 16:09 UTC, merged