Complete OOP Exercise
kottans/frontend-2022-homeworks pull request #524
Opened 2022-09-12 12:04 UTC by deveLabR

### OOP exercise

[Demo](https://develabr.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/deveLabR/a-tiny-JS-world)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-26 22:29 UTC, OleksiyRudenko requested changes
@deveLabR pretty good job!
Let's make it more OOP compliant.
Also let's improve naming skill.

2022-09-26 22:29 UTC, OleksiyRudenko commented on submissions/develabr/oop/index.js
> +    this.leg = 4;
What makes `leg` so different from `name` or gender to handle `leg` property in a different way?

2022-09-26 22:29 UTC, OleksiyRudenko commented on submissions/develabr/oop/index.js
> +    this.args = ['species', 'name', 'gender', 'saying', 'friends'];
Inhabitants are characterized rather by properties or features. No one says 'Name is my arg` or `Gender is my arg`

2022-09-26 22:29 UTC, OleksiyRudenko commented on submissions/develabr/oop/index.js
> +    return this.args.map((key) => this[key]).join('; ');
`key` is a generic, technical term.

2022-09-27 07:13 UTC, OleksiyRudenko requested changes
@deveLabR please revisit the requirements and education materials and make the code OOP-compliant.
Feel free asking questions here or in Students' chat.

2022-09-27 07:13 UTC, OleksiyRudenko commented on submissions/develabr/oop/index.js
> +    this.hands = hands;
From the [requirements](https://kottans.org/documentation/docs/doc/code-review/#oop-exercise):
> Classes for species that do not have hands by natural design do not consequently have hands or any equivalent property

Subclasses inherit all properties from parent classes, which means they have it.

2022-09-27 07:21 UTC, deveLabR commented
Oops, I wanted it to be better, but it turned out as usual (( I'll fix it now

2022-09-27 07:30 UTC, OleksiyRudenko commented
Use method overloading and `super` API. `super` can do more than just call parent's constructor.

2022-09-27 09:38 UTC, deveLabR commented
I hope I understood correctly how to use overloading methods

2022-09-27 11:30 UTC, OleksiyRudenko approved these changes
@deveLabR great job!

2022-09-27 11:30 UTC, merged