create frogger-game
kottans/frontend-2022-homeworks pull request #53
Opened 2022-08-02 21:09 UTC by Pozzitive11

### Frogger game

[Demo](https://pozzitive11.github.io/frogger-game-/) |
[Code base](https://github.com/Pozzitive11/frogger-game-)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-06 10:18 UTC, OleksiyRudenko requested changes
@Pozzitive11 well done!
Let's use the opportunity to improve the code and be ready for a massive expansion of game characters to be added by our peer developers.

2022-08-06 10:18 UTC, OleksiyRudenko commented on submissions/pozzitive11/frogger-game/app.js
> +  collision() {
BY convention method/function names should start with a verb.

2022-08-06 10:18 UTC, OleksiyRudenko commented on submissions/pozzitive11/frogger-game/app.js
> +  new Enemy(tileSize.height * 1 - enemy.enemyCenter, 100),
What are these magic numbers - 90, 150, 100?
Let the code explain them.

2022-08-06 10:18 UTC, OleksiyRudenko commented on submissions/pozzitive11/frogger-game/app.js
> +  }
ENemy class has exactly the same method. Let's make this [DRY](https://www.digitalocean.com/community/tutorials/what-is-dry-development). Consider having a base class for both Player and Enemy, that would handle all shared properties and behaviour.

2022-08-06 16:51 UTC, OleksiyRudenko requested changes
@Pozzitive11 your changes feel unfinished. Let's polish it.

2022-08-06 16:51 UTC, OleksiyRudenko commented on submissions/pozzitive11/frogger-game/app.js
> +    super(y, sprite);
Super class doesn't have a constructor. This operation is effectively void. Same is applicable to the `Player` class. However the idea to have similar properties and similar behaviour in a base class is great.
Can you fix this and implement shared properties and methods via the base class?

2022-08-06 16:51 UTC, OleksiyRudenko commented on submissions/pozzitive11/frogger-game/app.js
> +class gameObjectRender {
Think of class hierarchy as of bilogical taxonomy. Humans inherit features from apes, apes from mammals, mammals from vertebraes, and so on.
In this fictional game world bugs and player have a common fictional predecessor whose name could be saying something to the developers that may want to contribute to your game. May be a both bugs and player are instances of a character?

2022-08-06 17:34 UTC, Pozzitive11 commented
sorry for making the same mistakes 🥲

2022-08-15 21:24 UTC, OleksiyRudenko approved these changes
@Pozzitive11 great job!

2022-08-15 21:24 UTC, merged