Frogger-api-task
kottans/frontend-2022-homeworks pull request #532
Opened 2022-09-12 16:15 UTC by Conversee12

### frogger-api-task

[Demo](https://conversee12.github.io/frontend-nanodegree-arcade-game/) |
[Code base](https://github.com/Conversee12/frontend-nanodegree-arcade-game.git)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-13 12:53 UTC, Conversee12 commented
I've completed self-checks, did'nt find any common errors

2022-09-26 10:23 UTC, OleksiyRudenko requested changes
@Conversee12 good job. Although further improvements are required.
The comments below refer items from the [requirements](https://kottans.org/documentation/docs/doc/code-review/#oo-js-frogger)

2022-09-26 22:47 UTC, OleksiyRudenko requested changes
@Conversee12 
Feel free asking questions if anything is not clear

2022-09-26 22:47 UTC, OleksiyRudenko commented on submissions/Conversee12/Frogger-api-task/app.js
> +            player.y = InitialPosition_Y;
`player` is a global variable. 4.iii provides a hint on how to fix the issue.

2022-09-27 11:05 UTC, Conversee12 commented
![image](https://user-images.githubusercontent.com/108477577/192508779-d24b90a0-d39f-440a-9b5e-cec70a774323.png)
Is this "allEnemies" a global variable? (if yes) Honestly, i don't know how to change this. Please, explain.

2022-09-27 17:34 UTC, OleksiyRudenko commented
> ![image](https://user-images.githubusercontent.com/108477577/192508779-d24b90a0-d39f-440a-9b5e-cec70a774323.png) Is this "allEnemies" a global variable? (if yes) Honestly, i don't know how to change this. Please, explain.

Original requirement referred specifically to classes definitions, but yes, writing clean functions (functions that use only what is passed to them explicitly via parameters) is a good practice. What blocks you to re-use your experience with global `player`?

You do not need to fix this.

2022-09-27 17:35 UTC, OleksiyRudenko commented
```
setTimeout(function () {
            player.x = InitialPosition_X;
            player.y = InitialPosition_Y;
})
```

Check what makes arrow functions different from regular functions. `setTimeout` is a classic example for this.

2022-09-27 18:11 UTC, Conversee12 commented
> > ![image](https://user-images.githubusercontent.com/108477577/192508779-d24b90a0-d39f-440a-9b5e-cec70a774323.png) Is this "allEnemies" a global variable? (if yes) Honestly, i don't know how to change this. Please, explain.
> 
> Original requirement referred specifically to classes definitions, but yes, writing clean functions (functions that use only what is passed to them explicitly via parameters) is a good practice. What blocks you to re-use your experience with global `player`?
> 
> You do not need to fix this.

Something went wrong, I'll try again to figure it out myself

2022-09-27 18:14 UTC, Conversee12 commented
> ```
> setTimeout(function () {
>             player.x = InitialPosition_X;
>             player.y = InitialPosition_Y;
> })
> ```
> 
> Check what makes arrow functions different from regular functions. `setTimeout` is a classic example where arrow functions really help.

Read an article about this; understood and corrected

2022-09-29 19:22 UTC, OleksiyRudenko approved these changes
@Conversee12 great job!

2022-09-29 19:22 UTC, merged