popup done
kottans/frontend-2022-homeworks pull request #54
Opened 2022-08-03 07:55 UTC by ZjeniiaSt

_**УВАЖНО прочитайте і виконайте всі інструкції нижче перед тим як подати код на рев'ю.**_
1. Відформатуйте код, виправте неправильні відступи, видаліть непотрібні рядки, додайте пустий рядок у кінці кожного файлу, щоб ревʼюверу було зручно читати ваш код. Відформатувати код можна за допомогою [Prettier](https://prettier.io/playground). 
1. Перевірте свій код на наявність [типових помилок](https://kottans.org/documentation/docs/doc/code-review/#typical-mistakes). Пройдіться по всім пунктам відповідно до вашого завдання і виправте знайдені помилки.
1. Опублікуйте свою програму на [сторінках GitHub](https://github.com/kottans/frontend-2021-homeworks/blob/main/publish-your-app.md).
1. Переконайтеся, що назва вашого PR містить назву завдання.
1. Ваш код розміщено у бранчі, створеній спеціально для цього завдання (не `main`, не `master`, не бранча для іншого завдання).
1. Додайте тільки ті файли, які необхідні для рев'ю (код, CSS, HTML, які написані вами; не додавайте картинки, бо це робить репозиторій важким і відволікає рев'юерів)
1. Відредагуйте це повідомлення, як описано в наступних пунктах.
1. Змініть відповідно назву завдання та посилання нижче.
1. Видаліть весь текст вище із цим рядком включно.

### task name

[Demo](https://your-username.github.io/app-repo-name) |
[Code base](https://github.com/your-username/app-repo-name)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-03 08:29 UTC, Eugene-CG commented
Change PR description please.
Delete text above ## task name
Change task name to popup or something
Fix Demo/Code base links also
:3

2022-08-03 08:47 UTC, ZjeniiaSt commented
> ### first task popup
> [Demo](https://https://zjeniiast.github.io/kottans-popup/) | [Code base](https://github.com/ZjeniiaSt/kottans-popup)



> Change PR description please. Delete text above ## task name Change task name to popup or something Fix Demo/Code base links also :3

Thanks. Done

2022-08-03 10:11 UTC, A-Ostrovnyy requested changes
Good work!
See my comments below.

2022-08-03 10:11 UTC, A-Ostrovnyy commented on submissions/ZjeniiaSt/html-css-popup/index.html
> +    <main></main>
Avoid adding empty or unused tags

2022-08-03 10:11 UTC, A-Ostrovnyy commented on submissions/ZjeniiaSt/html-css-popup/index.html
> +            <li class="nav-item"><a href=""></a>Mail</li>
Add styles on `:hover` and `:focus` state.

2022-08-03 10:11 UTC, A-Ostrovnyy commented on submissions/ZjeniiaSt/html-css-popup/styles.css
> +* {
:fire:

2022-08-03 10:11 UTC, A-Ostrovnyy commented on submissions/ZjeniiaSt/html-css-popup/styles.css
> +  display: none;
[Watch video](https://www.youtube.com/watch?v=E6kLaaQFctU&t=413s) to find out how to hide checkbox in the right way.

2022-08-03 10:11 UTC, A-Ostrovnyy commented on submissions/ZjeniiaSt/html-css-popup/styles.css
> +:focus {
Check this selector looks like there typo.

2022-08-03 13:48 UTC, ZjeniiaSt commented
I`ve tried to fix if

2022-08-03 15:34 UTC, A-Ostrovnyy requested changes
Good work!
Remove Readme.md from PR. PR should contain only files for review.

2022-08-03 15:34 UTC, A-Ostrovnyy commented on submissions/ZjeniiaSt/html-css-popup/styles.css
> +  --background-color: rgba(229, 229, 229, 1);
In case when you have `rgba` color scheme and alpha channel with value 1, better use `rgb`)

2022-08-03 15:34 UTC, A-Ostrovnyy commented on submissions/ZjeniiaSt/html-css-popup/index.html
> +            <li class="nav-item"><a href="#"></a>Mail</li>
Add styles on `:focus` state to top-level navigation.

2022-08-03 15:34 UTC, A-Ostrovnyy commented on submissions/ZjeniiaSt/html-css-popup/index.html
> +                    <a href="#"><img src="./images/maps.png" alt="" /></a
On hover better to scale just icon.

2022-08-03 15:34 UTC, A-Ostrovnyy commented on submissions/ZjeniiaSt/html-css-popup/index.html
> +                    <a href="#"><img src="./images/videos.png" alt="" /> </a
Set the equal height to all icons inside the popup.
![image](https://user-images.githubusercontent.com/16196199/182648471-cfe5e323-80ef-4128-98f8-e785427865c5.png)

2022-08-03 15:34 UTC, A-Ostrovnyy commented on submissions/ZjeniiaSt/html-css-popup/styles.css
> +.menu {
Don't forget about mobile view)
![image](https://user-images.githubusercontent.com/16196199/182648660-d7f765f6-add4-4992-8607-be8b77c09346.png)

2022-08-03 15:34 UTC, A-Ostrovnyy commented on submissions/ZjeniiaSt/html-css-popup/index.html
> +            <li class="nav-item"><a href=""></a>Mail</li>
Not fixed yet

2022-08-05 08:29 UTC, ZjeniiaSt commented
Hi. I`v tried to fix it again

2022-08-05 09:00 UTC, A-Ostrovnyy requested changes
Good work!

2022-08-05 09:02 UTC, A-Ostrovnyy commented
For future Pull requests press re-request button when you push your changes
![image](https://user-images.githubusercontent.com/16196199/183042801-a38d4728-d989-46c7-b583-43b0f182f433.png)

2022-08-05 09:08 UTC, ZjeniiaSt commented
Wow, this is really helpful. Thank you.))

[image: width=]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вірусів.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

пт, 5 серп. 2022 р. о 11:02 Alexandr ***@***.***> пише:

> For future Pull requests press re-request button when you push your changes
> [image: image]
> <https://user-images.githubusercontent.com/16196199/183042801-a38d4728-d989-46c7-b583-43b0f182f433.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kottans/frontend-2022-homeworks/pull/54#issuecomment-1206218194>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATZI5QRHYPOWWJVBSDUTXFTVXTKEDANCNFSM55N2QDYA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-05 09:27 UTC, A-Ostrovnyy requested changes
Remove Readme.md and file from another student

2022-08-05 09:27 UTC, A-Ostrovnyy commented on submissions/ZjeniiaSt/html-css-popup/index.html
> +            <li class="nav-item"><a href="#"></a>Mail</li>
Still not fixed(

2022-08-05 09:27 UTC, A-Ostrovnyy commented on submissions/ZjeniiaSt/html-css-popup/index.html
> +              <input type="checkbox" id="popup" />
Still not fixed(

2022-08-05 09:27 UTC, A-Ostrovnyy commented on submissions/antonkottans/hooli-style-popup/index.html
>  <!DOCTYPE html>
You make changes to the file of another student. Don't do that)

2022-08-05 09:27 UTC, A-Ostrovnyy commented on submissions/ZjeniiaSt/html-css-popup/index.html
> +              <input type="checkbox" id="popup" />
Something goes wrong and I can't open the popup using a keyboard. Also, check opening inside popup)

2022-08-05 14:19 UTC, A-Ostrovnyy commented on submissions/antonkottans/hooli-style-popup/index.html
>  <!DOCTYPE html>
Stil not fixed (

2022-08-05 14:24 UTC, A-Ostrovnyy requested changes
Almost done)
Remove files not for review: Readme.md and [antonkottans/hooli-style-popup/index.html
Your PR should contain only 2 files

2022-08-07 12:52 UTC, A-Ostrovnyy commented
@ZjeniiaSt Why do you change the file of another student? Your PR should contain your index.html and styles.css
![image](https://user-images.githubusercontent.com/16196199/183291362-ad8e1628-ce6e-46ec-bcca-a49f1ef1e815.png)

2022-08-07 12:53 UTC, A-Ostrovnyy requested changes
Remove file from another student!

2022-08-07 13:20 UTC, ZjeniiaSt commented
I am trying to undo an accidental change in this file. And I can't do it
correctly(((. I will think about a solution

нд, 7 серп. 2022, 14:53 користувач Alexandr ***@***.***> пише:

> ***@***.**** requested changes on this pull request.
>
> Remove file from another student!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kottans/frontend-2022-homeworks/pull/54#pullrequestreview-1064419502>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATZI5QUJRUZ2SBYULJDDXWDVX6WTRANCNFSM55N2QDYA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-07 13:49 UTC, A-Ostrovnyy commented
1. Find commit when you add changes to the file of another student.
2. Copy sha of the previous commit
3. In the terminal go to his folder
4, Run `git checkout COPIED_SHA`
5. Push changes
If it's not worked text me in discord and we will fix it in screen sharing mode)

2022-08-07 17:44 UTC, closed without merging

2022-08-07 17:45 UTC, A-Ostrovnyy commented
@ZjeniiaSt Why did you close PR?

2022-08-07 18:16 UTC, ZjeniiaSt commented
by accident((( I deleted too many commits((( And the request closed. And
when I restored the commit, git already offered to create a new request.
aaaaaaa🤦🤦🤦🤦🤦

нд, 7 серп. 2022, 19:45 користувач Alexandr ***@***.***> пише:

> @ZjeniiaSt <https://github.com/ZjeniiaSt> Why did you close PR?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kottans/frontend-2022-homeworks/pull/54#issuecomment-1207454392>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATZI5QVFC3UWZQIBTMTA7HDVX7Y4VANCNFSM55N2QDYA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>