OOP Tiny-JS-World
kottans/frontend-2022-homeworks pull request #569
Opened 2022-09-14 17:34 UTC by Conversee12

### oop-tiny-js-world

[Demo](https://conversee12.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/Conversee12/a-tiny-JS-world.git)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-15 08:48 UTC, Conversee12 commented
I've completed self-checks, did'nt find any common errors

2022-09-26 22:42 UTC, OleksiyRudenko requested changes
@Conversee12 let's make code more OOP compliant.

2022-09-26 22:42 UTC, OleksiyRudenko commented on submissions/Conversee12/OOP Tiny-Js-World/index.js
> +      return `${this.species}; ${this.name}; ${this.gender}; ${this.saying}`;
Please employ `Array` methods. Starting array may not necessarily consist of strings. Actually, anything can be an array's element.

2022-09-26 22:42 UTC, OleksiyRudenko commented on submissions/Conversee12/OOP Tiny-Js-World/index.js
> +      return `${this.species}; ${this.name}; ${this.gender}; ${this.hands}; ${this.legs}; ${this.saying}`;
Use method overloading.
If we add a new universally shared property, current implementation will require changes to multiple classes' code. The point of encapsulation is that every class handles its own properties and re-uses inherited methods versions to build on top of whatever they provide us with.

Let's disregard the fact that we want to "insert" information about limbs before saying, for simplification.

2022-09-27 12:22 UTC, Conversee12 commented
Fixed this. Please, review

2022-09-27 17:21 UTC, OleksiyRudenko approved these changes
@Conversee12 great job done!

2022-09-27 17:21 UTC, merged