OOP Exercise (update tiny JS world)
kottans/frontend-2022-homeworks pull request #578
Opened 2022-09-15 12:46 UTC by andreymashko7

### OOP Exercise

[Demo](https://andreymashko7.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/andreymashko7/a-tiny-JS-world)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-09-21 08:05 UTC, andreymashko7 commented
self-check is done

2022-10-09 14:55 UTC, OleksiyRudenko requested changes
@andreymashko7 well done.
Let's polish it to see that you embraced DRY ideology.

2022-10-09 14:55 UTC, OleksiyRudenko commented on submissions/AndriyM/oop_exercise_tiny_world/index.js
> +        return `${this.species}; ${this.name}; ${this.gender}; ${this.legs}; ${this.saying}`;
Make this fragment DRY

2022-10-09 16:41 UTC, andreymashko7 commented
Please, review again

2022-10-09 19:38 UTC, OleksiyRudenko requested changes
@andreymashko7 quite a decent job.
Let's polish it.

2022-10-09 19:38 UTC, OleksiyRudenko commented on submissions/AndriyM/oop_exercise_tiny_world/index.js
> +		return keys.map((key) => this[key]).join("; ");
`keys` and `key` are generic terms.
Any good reason to keep list of properties outside class definition?

2022-10-09 19:53 UTC, andreymashko7 commented
Better now? I hope I got it right.

2022-10-09 19:54 UTC, OleksiyRudenko commented
@andreymashko7 only second half of mentor's comment is addressed.

2022-10-09 20:09 UTC, andreymashko7 commented
Fixed,please check

2022-10-11 07:52 UTC, andreymashko7 commented
@OleksiyRudenko , please check

2022-10-13 21:32 UTC, OleksiyRudenko approved these changes
@andreymashko7 great job!

2022-10-13 21:32 UTC, merged