popup
kottans/frontend-2022-homeworks pull request #7
Opened 2022-07-25 07:53 UTC by maximmorenko

_**УВАЖНО прочитайте і виконайте всі інструкції цього шаблону PR перед тим як подати код на рев'ю.**_
1. Опублікуйте свою програму на [сторінках GitHub](https://github.com/kottans/frontend-2021-homeworks/blob/main/publish-your-app.md).
1. Переконайтеся, що назва вашого PR містить назву завдання.
1. Ваш код розміщено у бранчі, створеній спеціально для цього завдання (не `main`, не `master`, не бранча для іншого завдання).
1. Додайте тільки ті файли, які необхідні для рев'ю (код, CSS, HTML, які написані вами; не додавайте картинки, бо це робить репозиторій важким і відволікає рев'юерів)
1. Змініть назву завдання та посилання в цьому шаблоні нижче.
1. Видаліть весь текст вище із цим рядком включно.

### task name

[Demo](https://your-username.github.io/app-repo-name) |
[Code base](https://github.com/your-username/app-repo-name)

The code is submitted in a dedicated feature branch.
Please, review.

2022-07-25 09:39 UTC, OleksiyRudenko requested changes
@maximmorenko please undo changes to `.github/pull_request_template.md`. You were supposed to change the Pull Request initial message body.

2022-07-26 07:07 UTC, A-Ostrovnyy requested changes
Awesome disign!
But some issues must be fixed.
Also if interesting and you have some time check your work in firefox)

2022-07-26 07:07 UTC, A-Ostrovnyy commented on submissions/morenko/html-css-popup/style.css
> +
Try to keep your code style cleaner: space between code blocks, no unused lines inside code block(in CSS)

2022-07-26 07:07 UTC, A-Ostrovnyy commented on submissions/morenko/html-css-popup/style.css
> +:root {
:fire:

2022-07-26 07:07 UTC, A-Ostrovnyy commented on submissions/morenko/html-css-popup/style.css
> +/* ======================================= */
What is this for? If you want to add some divider try to add some explanation/title to make it clear to your college.

2022-07-26 07:07 UTC, A-Ostrovnyy commented on submissions/morenko/html-css-popup/style.css
> +.popup-btn-menu{
Watch [video](https://www.youtube.com/watch?v=E6kLaaQFctU&t=413s) to find out how to hide checkbox in the right way

2022-07-26 07:39 UTC, maximmorenko commented on submissions/morenko/html-css-popup/index.html
> +                <a href="#"><img src="./assets/icons/001_logo.png" alt="logo"></a>
I think that the logo can be a link to the main page, which means it is a navigation element) but if it's a problem, then I can remove it

2022-07-26 07:47 UTC, maximmorenko commented on submissions/morenko/html-css-popup/index.html
> +                            <li class="popup-item"><a href="#" ><img src="./assets/icons/sport/01.png" alt="a"></a></li>
да, я прекрасно понимаю, что альт должен описывать картинку) но ведь там два десятка иконок, мне показалось что на учебном проекте не принципиально давать каждой своё описание. или нет)? sorry for russians

2022-07-26 07:50 UTC, maximmorenko commented on submissions/morenko/html-css-popup/index.html
> +</html>
причины нет) предполагалось что что-то будет в будущем

2022-07-26 07:51 UTC, maximmorenko commented on submissions/morenko/html-css-popup/style.css
> +    /* background: url(../assets/img/1637352650_71-krot-info-p-goluboe-more-peizazh-krasivoe-foto-80.jpg) no-repeat center fixed;
ok

2022-07-26 08:15 UTC, maximmorenko commented on submissions/morenko/html-css-popup/style.css
> +/* ======================================= */
хорошо, почищу, удалю всё лишнее, поколдую с чекбоксом. Скажите пожалуйста, есть ли способ установить  фокус на li елемент? Нашел инфо, что должен помочь tabindex атрибут, но он не помог. Фокус работает но только через таб. при клике - нет. Сделал вариант без li, на ссылках и обернул в див, тогда работает. Но потом отдал предпочтение семантике, и вернул список

2022-07-26 19:19 UTC, A-Ostrovnyy commented on submissions/morenko/html-css-popup/index.html
> +                <a href="#"><img src="./assets/icons/001_logo.png" alt="logo"></a>
In 99.999% of cases, logo must be a link and leads to the home page. Logo is a reusable component, better keep it outside navigation. Also if we will have another block of links (login/signup etc.) should we add him into this navigation, or keep hin as an independent component?

2022-07-26 19:22 UTC, A-Ostrovnyy commented on submissions/morenko/html-css-popup/index.html
> +                            <li class="popup-item"><a href="#" ><img src="./assets/icons/sport/01.png" alt="a"></a></li>
According to an article, you must fill `alt` attribute for content images. the icon is a decorative image(not content) and for him, `alt` must be empty. Read more carefully.

2022-07-26 19:25 UTC, A-Ostrovnyy commented on submissions/morenko/html-css-popup/index.html
> +</html>
I mean word Reason is a link to page with explanation why you should add an empty line at the end of each file.)

2022-07-26 19:36 UTC, A-Ostrovnyy commented on submissions/morenko/html-css-popup/style.css
> +/* ======================================= */
1. Avoid adding focus state to non-interactive elements.
2. Keep your markup as simple as possible, as you can use custom interactive element focus to highlight the desired element when you want the interactive element in focus

2022-07-26 19:41 UTC, A-Ostrovnyy requested changes
Good work!
Some issues need to fix)

2022-07-26 19:41 UTC, A-Ostrovnyy commented on submissions/morenko/html-css-popup/style.css
> +    -webkit-appearance: none;
If you write property with vendor prefix don't forget about the property without him for different browsers.

2022-07-26 23:04 UTC, maximmorenko commented on submissions/morenko/html-css-popup/style.css
> +/* ======================================= */
Где фокус уместен, а где нет это понятно) вопрос стоял как это сделать) интерактивные элементы внутри элемента списка тоже могут быть списком. Есть способы установить фокус на элемент списка li?

2022-07-26 23:30 UTC, maximmorenko commented on submissions/morenko/html-css-popup/index.html
> +                <a href="#"><img src="./assets/icons/001_logo.png" alt="logo"></a>
компонент с функцией навигации изъять из списка навигации, ок) вам виднее)

2022-07-26 23:32 UTC, maximmorenko commented on submissions/morenko/html-css-popup/index.html
> +</html>
не совсем понял) должна появиться пустая 74я строка?

2022-07-27 06:40 UTC, A-Ostrovnyy commented on submissions/morenko/html-css-popup/index.html
> +</html>
Yes, add the line.
An empty line at the end of the file avoids the wrong concatenation of files.

2022-07-27 07:23 UTC, A-Ostrovnyy commented on submissions/morenko/html-css-popup/style.css
> +/* ======================================= */
You can add focus to the non-interactive element just by adding `tabindex` attribute, but in this case, at first, the focus goes to this non-interactive element, and then he goes to the interactive element inside this element
You can check demo [https://codepen.io/a-ostrovnyy/pen/ZExXXvq](https://codepen.io/a-ostrovnyy/pen/ZExXXvq)

2022-07-27 08:47 UTC, maximmorenko commented on submissions/morenko/html-css-popup/style.css
> +/* ======================================= */
ясно, спасибо)

2022-07-27 08:58 UTC, maximmorenko commented on submissions/morenko/html-css-popup/index.html
> +</html>
пустую строку добавил еще вчера, но она не отображается в коммите. 
![image](https://user-images.githubusercontent.com/60241469/181204726-6a126c5a-41e7-4ad2-b15a-f64cb9421bb8.png)
![image](https://user-images.githubusercontent.com/60241469/181205947-6dd78ad6-8445-451b-ae46-f000c5d0cdbe.png)
![image](https://user-images.githubusercontent.com/60241469/181206452-03825396-f2fb-404b-908c-da22dac3c887.png)
что делать? где я не прав?)

2022-07-27 09:00 UTC, A-Ostrovnyy requested changes
Good progress!

2022-07-27 09:04 UTC, A-Ostrovnyy commented on submissions/morenko/html-css-popup/index.html
> +</html>
By default, Github hides the last empty line.
If you see this icon at the end of your file that means you forget to add an empty line, and you should add it.
![image](https://user-images.githubusercontent.com/16196199/181207909-759b4721-163a-445d-91fd-83509c2e5b37.png)

2022-07-27 09:06 UTC, A-Ostrovnyy commented
If you want to discuss something in voice we can schedule a call in discord and discuss what you want.

2022-07-27 09:15 UTC, maximmorenko commented on submissions/morenko/html-css-popup/index.html
> +                    <a  href="#"><img src="./assets/icons/03_baseline_email.png" alt="email"></a>
я их прозевал) извините
![image](https://user-images.githubusercontent.com/60241469/181210505-b613e6c6-f8ee-4ee8-8306-6b840efdcac2.png)

2022-07-27 16:08 UTC, A-Ostrovnyy commented
Well done!
For future Pull Requests: after pushing changes click the re-request button to inform the reviewer about your changes
![image](https://user-images.githubusercontent.com/16196199/181296001-4823c026-c634-4d32-8712-7dd0512ea50f.png)

2022-07-27 16:08 UTC, merged