friends-app
kottans/frontend-2022-homeworks pull request #731
Opened 2022-09-30 20:52 UTC by kirill8210

### friends-app

[Demo](https://kirill8210.github.io/kottans_friends) |
[Code base](https://github.com/kirill8210/kottans_friends)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-10-02 12:59 UTC, artem-trubin requested changes
Hi! I would like to request some changes without looking at the code yet since you have some strange behaviors in your project. First of all, pressing `all gender` seems to reverse the array of displayed users for some reason. Secondly, if you write a name in the search and then click any of the gender options - it clears out the search input (which it should not do). 

Also, please include your other code files, not only the JS one.

2022-10-05 10:21 UTC, kirill8210 commented
Made edits. Also added other project files

2022-10-15 20:03 UTC, artem-trubin requested changes
Hi, sorry for the long delay.

Nice work, but there's a lot to fix and improve here. I'm not going to do a very thorough review, rather guide your thinking to another path and we'll work it out from there. Please follow comments in the code. 

Besides, found a couple of bugs/rough edges in your work, make sure to fix them too:
1. You can only search by users' first names in your work. Last names should be included too.
2. In mobile version, I believe you set your menu to hide every time users changes something. This isn't a good place for such behaviour because:
    1. This isn't a navigation menu where you would like to close it after, for example, navigating to another page. This is a complicated "settings"-like menu, where user possibly would like to change several inputs at once before turning to content.
    2. This behaviour introduced a bug, where the menu would close each time you type a button in the search input, what makes it practically unusable.

Also, please include all code files that you worked with, not only js. html and  css could still contain some mistakes and potential room for improvements.

2022-10-21 15:36 UTC, kirill8210 commented on submissions/kirill8210/friends-app/getData.js
> +let URL_API = 'https://randomuser.me/api/?results=50&nat=us,gb,ua&inc=gender,name,email,dob,phone,picture';
corrected

2022-10-21 15:37 UTC, kirill8210 commented on submissions/kirill8210/friends-app/index.js
> +const createCard = (data2) => {
corrected

2022-10-21 15:37 UTC, kirill8210 commented on submissions/kirill8210/friends-app/index.js
> +    const { name, gender, email, phone, picture, dob } = data2;
corrected

2022-10-21 15:40 UTC, kirill8210 commented on submissions/kirill8210/friends-app/index.js
> +const inputAll = document.querySelector('#all');
did not understand what to do. move to a separate file, into a function and export the names of the constants?

2022-10-21 15:40 UTC, kirill8210 commented on submissions/kirill8210/friends-app/index.js
> +        const fByG = filterByGender()
corrected

2022-10-21 15:40 UTC, kirill8210 commented on submissions/kirill8210/friends-app/index.js
> +        console.log(sortIdName.value);
corrected

2022-10-21 15:41 UTC, kirill8210 commented on submissions/kirill8210/friends-app/index.js
> +reset.addEventListener('click', e => {
honored Google, applied

2022-10-21 15:47 UTC, kirill8210 commented
fixed bugs and comments

2022-11-06 20:43 UTC, kirill8210 commented
error correction

2022-11-06 20:57 UTC, merged