add hooli-style-popup homework
kottans/frontend-2022-homeworks pull request #79
Opened 2022-08-06 16:57 UTC by bmukha

### hooli-style-popup

[Demo](https://bmukha.github.io/hooli-style-popup/) |
[Code base](https://github.com/bmukha/hooli-style-popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-08 17:41 UTC, HannaSyn requested changes
Good work! 
See my comments below

2022-08-08 17:41 UTC, HannaSyn commented on submissions/bmukha/hooli-style-popup/index.html
> +          <li class="header__nav__item__main" tabindex="2">Menu</li>
Logically, items in navigation should be links, so please add `a` inside `li`

2022-08-08 17:41 UTC, HannaSyn commented on submissions/bmukha/hooli-style-popup/index.html
> +                  tabindex="5"
`tabindex` is not necessary in this task, and in your case, it cause problems - when you navigate with tab, focus should appear on icons first, and then on `More` button. 
Also when focus on `More` , hidden menu is not opens by clicking space on keyboard.

2022-08-08 17:41 UTC, HannaSyn commented on submissions/bmukha/hooli-style-popup/index.html
> +            <label for="menu__toggle">
Please, add `:focus` state to this element

2022-08-08 17:41 UTC, HannaSyn commented on submissions/bmukha/hooli-style-popup/index.html
> +                          alt="apps"
For icons it's better set an empty alt attribute, read more [here](https://accessibility.psu.edu/images/imageshtml/#empty)

2022-08-08 17:41 UTC, HannaSyn commented on submissions/bmukha/hooli-style-popup/style.css
> +}
Please, add empty line after each block

2022-08-08 17:41 UTC, HannaSyn commented on submissions/bmukha/hooli-style-popup/style.css
> +input[type="checkbox"]:checked + label::after {
Please, avoid styling by tags [link](https://frontstuff.io/you-need-to-stop-targeting-tags-in-css)

2022-08-10 18:28 UTC, bmukha commented
Tnx for the feedback. Provided links have been very insightful. Please, review my submission again - I believe all aforementioned issues have been addressed.

2022-08-16 09:24 UTC, merged