Sadoharu html css popup
kottans/frontend-2022-homeworks pull request #8
Opened 2022-07-25 13:21 UTC by Sadoharu

### task name

[Demo](https://sadoharu.github.io/html-css-popup) |
[Code base](https://github.com/Sadoharu/html-css-popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-07-26 17:35 UTC, HannaSyn commented
Great job! 
See my comments below

2022-07-26 17:38 UTC, HannaSyn commented
Please, follow all the instructions from task, you missed some of them:
1. All interactive elements must be marked as such on hover - header menu items included
2. You should be able to switch between all interactive elements using only the keyboard (no mouse, don't forget the styles for the :focus state) - now you can only open/close menus

2022-07-26 17:51 UTC, HannaSyn requested changes

2022-07-26 17:51 UTC, HannaSyn commented on submissions/sadoharu/html-css-popup/index.html
> +    <nav class="nav-bar">
Please, move `nav` tag to list with navigation, it is not necessary to include `logo` in it.

2022-07-26 17:51 UTC, HannaSyn commented on submissions/sadoharu/html-css-popup/style.css
> +
Please, remove unnecessary white-spaces, only 1 is required

2022-07-26 17:51 UTC, HannaSyn commented on submissions/sadoharu/html-css-popup/style.css
> +}
You should add white-space here =)

2022-07-26 17:51 UTC, HannaSyn commented on submissions/sadoharu/html-css-popup/style.css
> +
Please, remove unnecessary white-spaces, only 1 is required

2022-07-26 17:51 UTC, HannaSyn commented on submissions/sadoharu/html-css-popup/style.css
> +
Please, remove unnecessary white-spaces

2022-07-27 11:50 UTC, Sadoharu commented
Please, review, again.

2022-07-27 15:55 UTC, HannaSyn commented
> Please, review, again.

You did a great work! 
Let's fix one more small but important detail - when you tab through navigation, it would be great to have possibility after opening the popup menu, immediately tab to the first icon of the menu, and not go further along the navigation list in header. Also, after clicking on `Show more`, be able to continue following the list of icons, and only after the popup icons, continue navigation in the header.

2022-07-27 16:33 UTC, A-Ostrovnyy requested changes
Good Work!

2022-07-27 16:33 UTC, A-Ostrovnyy commented on submissions/sadoharu/html-css-popup/index.html
> +                <li class="nav-bar_list_item images"><a tabindex="1" href="#">Images</a></li>
For this small page using `tabindex` attribute is redundant.
When user opened popup and presses the Tab key focus must go to the first element in popup In your case focus goes through the rest menu items and after all, items go inside popup. Remove `tabindex` attribute and see how behavior will change.

2022-07-27 16:33 UTC, A-Ostrovnyy commented on submissions/sadoharu/html-css-popup/style.css
> +.nav-bar .nav-bar_list_item.popup-button .popup-icon:checked ~ .popup {
Avoid styling elements using a too-specific CSS selector.
[Read more](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) about specificity in CSS

2022-07-27 16:33 UTC, A-Ostrovnyy commented on submissions/sadoharu/html-css-popup/style.css
> +.nav-bar .nav-bar_list_item.popup-button input{
Avoid styling by HTML tag. [Reason](https://frontstuff.io/you-need-to-stop-targeting-tags-in-css)

2022-07-27 19:51 UTC, Sadoharu commented
okay. I fix this. pls review

2022-07-28 08:31 UTC, HannaSyn approved these changes

2022-07-28 15:07 UTC, A-Ostrovnyy requested changes
Good work!
You still have too specific CSS selectors, try to reduce their specificity.

2022-07-28 15:07 UTC, A-Ostrovnyy commented on submissions/sadoharu/html-css-popup/index.html
> +                                    <li class="popup-item"><a class="link" href="#"><img class="img" src="./img/documents.png" alt="Documents">Documents</a></li>
Read about how to populate `alt` attribute in the right way.
Sorry for russian but it's a good [article](https://htmlacademy.ru/blog/articles/alt-text)

2022-07-28 17:07 UTC, Sadoharu commented
i tried to fix it, pls review

2022-07-28 18:40 UTC, A-Ostrovnyy requested changes
Good work!
But for icons better an empty `alt` attribute)

2022-07-28 19:19 UTC, Sadoharu commented
done

2022-07-29 04:53 UTC, A-Ostrovnyy approved these changes
Well done

2022-07-29 04:53 UTC, merged