HTML-CSS-Popup task
kottans/frontend-2022-homeworks pull request #87
Opened 2022-08-08 09:39 UTC by kosh3n

### HTML-CSS-Popup

[Demo](https://kosh3n.github.io/HTML-CSS-Popup/) |
[Code base](https://github.com/kosh3n/HTML-CSS-Popup)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-08 18:11 UTC, HannaSyn reviewed
Nice work! 
Please, see my comments below

2022-08-08 18:11 UTC, HannaSyn commented on submissions/kosh3n/HTML-CSS-Popup/index.html
> +                    <span tabindex="0"> <img src="dots-menu.png" alt="dots-menu.png"></span></label>
For icons it's better set an empty alt attribute, read more [here](https://accessibility.psu.edu/images/imageshtml/#empty)

2022-08-08 18:11 UTC, HannaSyn commented on submissions/kosh3n/HTML-CSS-Popup/index.html
> +                    <li><a href="#">
```suggestion
                    <li>
                        <a href="#mail">
                            <figure>
                                <img src="https://img.icons8.com/stickers/100/000000/mail-contact.png" alt="mail">
                                <figcaption>Mail</figcaption>
                            </figure>
                        </a>
                    </li>
                    <li>
                        <a href="#">
```
Please, format your file to make it more readable

2022-08-08 18:11 UTC, HannaSyn commented on submissions/kosh3n/HTML-CSS-Popup/index.html
> +                    <!-- and this section is hide by default -->
Please, avoid redundant comments

2022-08-08 18:11 UTC, HannaSyn commented on submissions/kosh3n/HTML-CSS-Popup/index.html
> +                <label for="hamburger">
Please, add possibility to open menu with keyboard

2022-08-08 18:11 UTC, HannaSyn commented on submissions/kosh3n/HTML-CSS-Popup/index.html
> +                    <li> <label for="show-more">
Please, add possibility to view hidden icons with keyboard

2022-08-08 18:11 UTC, HannaSyn commented on submissions/kosh3n/HTML-CSS-Popup/style.css
> +header {
Please, avoid styling by tags [link](https://frontstuff.io/you-need-to-stop-targeting-tags-in-css)

2022-08-08 18:11 UTC, HannaSyn commented on submissions/kosh3n/HTML-CSS-Popup/style.css
> +/*menu*/
Get rid of unnecessary comments in code

2022-08-08 18:11 UTC, HannaSyn commented on submissions/kosh3n/HTML-CSS-Popup/style.css
> +figcaption {
Please, avoid styling by tags [link](https://frontstuff.io/you-need-to-stop-targeting-tags-in-css)

2022-08-08 18:11 UTC, HannaSyn commented on submissions/kosh3n/HTML-CSS-Popup/style.css
> +input {
Please, avoid styling by tags [link](https://frontstuff.io/you-need-to-stop-targeting-tags-in-css)

2022-08-17 17:15 UTC, kosh3n commented
I had rewrite code so now it should work properly now. Had deleted all comments and now the navigation from keybord is working. Please, check out my work again.

2022-08-18 10:40 UTC, HannaSyn requested changes
Good, please, fix one comment below

2022-08-18 10:40 UTC, HannaSyn commented on submissions/kosh3n/HTML-CSS-Popup/index.html
> +                                <img class="menu-img" src="https://img.icons8.com/stickers/100/000000/video.png" alt="video">
For icons it's better set an empty alt attribute, read more [here](https://accessibility.psu.edu/images/imageshtml/#empty)
Please, check All icons in your project

2022-08-19 09:44 UTC, kosh3n commented
Sorry, I was thinking that an empty alt attr should be only in first img with "logo", my mistake.  I fixed all alt in img, please, check out my work again.

2022-08-21 11:25 UTC, artem-trubin requested changes
Hi, there are some problems.

1. Focus on the popup button looks strange, see screenshot below. 
![image](https://user-images.githubusercontent.com/11278566/185788611-c10141a0-c880-455f-8dc1-dee77517a5ee.png)
2. `More` button should hide after it is pressed. 
3. When the `More` menu is open it is possible to select the `More` twice while going through elements with the keyboard. But I guess this problem will disappear when you hide this button after resolving the previous problem.

2022-09-11 14:04 UTC, closed without merging