Html css popup
kottans/frontend-2022-homeworks pull request #97
Opened 2022-08-08 18:08 UTC by Tedzury

### HTML_CSS_POPUP

[Demo](https://tedzury.github.io/HTML_CSS_PopUp/) |
[Code base](https://github.com/Tedzury/HTML_CSS_PopUp.git)

The code is submitted in a dedicated feature branch.

Only code files are submitted.

Please, review.

2022-08-10 16:53 UTC, A-Ostrovnyy requested changes
Good work!

2022-08-10 16:53 UTC, A-Ostrovnyy commented on submissions/Oleksii_Drohachov/HTML_CSS_PopUp/index.html
> +            <div class="main__wrapper">
Why you don't use `ul` inside `li` Logically it looks like the second level of navigation.

2022-08-10 16:53 UTC, A-Ostrovnyy commented on submissions/Oleksii_Drohachov/HTML_CSS_PopUp/index.html
> +                <div class="menu__item__main" tabindex="0">
Just use interactive elements and you don't need a `tabindex` attribute

2022-08-10 16:53 UTC, A-Ostrovnyy commented on submissions/Oleksii_Drohachov/HTML_CSS_PopUp/index.html
> +                    <div><img src="icons/apps.png" alt="icon logo" /></div>
[Read this article](https://htmlacademy.ru/blog/articles/alt-text) to find out how and when populate `alt` attribute

2022-08-10 16:53 UTC, A-Ostrovnyy commented on submissions/Oleksii_Drohachov/HTML_CSS_PopUp/index.html
> +              >My Kottans in TG</a
Don't forget about mobile version
![image](https://user-images.githubusercontent.com/16196199/183967117-d8a9ce0a-e6f2-40b2-9a8a-77870b709572.png)

2022-08-10 16:53 UTC, A-Ostrovnyy commented on submissions/Oleksii_Drohachov/HTML_CSS_PopUp/index.html
> +              <label class="second_label" for="second">Even more icons !</label>
Hide this button when the second part of popup is open
![image](https://user-images.githubusercontent.com/16196199/183967773-b587e9de-5996-4c1f-aeba-b94b30191d3c.png)

2022-08-10 16:53 UTC, A-Ostrovnyy commented on submissions/Oleksii_Drohachov/HTML_CSS_PopUp/index.html
> +                      <div><img alt="icon logo" src="icons/videos.png" /></div>
[Read this article](https://jakearchibald.com/2022/img-aspect-ratio/) about how to handle image aspect ratio.

2022-08-10 16:53 UTC, A-Ostrovnyy commented on submissions/Oleksii_Drohachov/HTML_CSS_PopUp/index.html
> +                        <img alt="icon logo" src="icons/contacts.png" />
Fix styles on hover state: menu items moving, avoid that situation

2022-08-10 16:53 UTC, A-Ostrovnyy commented on submissions/Oleksii_Drohachov/HTML_CSS_PopUp/style.css
> +
Add an empty line at the end of each file. [Reason](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline?noredirect=1&lq=1)

2022-08-10 16:53 UTC, A-Ostrovnyy commented on submissions/Oleksii_Drohachov/HTML_CSS_PopUp/style.css
> +  .item_box > div > img {
Avoid styling by HTML tag. [Reason](https://frontstuff.io/you-need-to-stop-targeting-tags-in-css)
Also, avoid using too specific CSS selectors. [Read more](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)

2022-08-12 19:00 UTC, Tedzury commented
Good evening. Humbly asking for review, hope I fixed everything, what is needed. :)

2022-08-12 20:50 UTC, A-Ostrovnyy requested changes
Good progress!
Two small issue left)

2022-08-12 20:50 UTC, A-Ostrovnyy commented on submissions/Oleksii_Drohachov/HTML_CSS_PopUp/index.html
> +                  <nav class="second_wrapper">
This nav is unnecessary because this content already inside `nav` tag)

2022-08-12 20:50 UTC, A-Ostrovnyy commented on submissions/Oleksii_Drohachov/HTML_CSS_PopUp/index.html
> +                      </li>
Add one single border on focus state instead of two.

2022-08-13 15:46 UTC, Tedzury commented
Good evening, hope, now I fixed everything )

2022-08-13 19:18 UTC, A-Ostrovnyy requested changes
Check your markup in [validator](https://validator.w3.org/)

2022-08-13 19:18 UTC, A-Ostrovnyy commented on submissions/Oleksii_Drohachov/HTML_CSS_PopUp/index.html
> +                    ><div>
This `div` is redundant, move all div styles to the parent element link.

2022-08-16 19:47 UTC, Tedzury commented
Good evening again!) Sorry for my abcence for few day. Fixed useless divs, validation error and cursor.

2022-08-17 05:25 UTC, A-Ostrovnyy approved these changes
Well done!

2022-08-17 05:25 UTC, merged